/**
 * Bee Flow's Android config plugin — the manifest and resource edits that no
 * off-the-shelf Expo plugin makes for us.
 *
 * Everything here exists because `expo prebuild` regenerates android/ from
 * scratch on every build. Hand-editing the generated manifest would work
 * exactly once. Four changes, each with a reason:
 *
 *  1. allowBackup=false + dataExtractionRules. This is a zero-knowledge
 *     product: the device holds a session token and, once unlocked, the
 *     unwrapped DEK. Android's default auto-backup would copy the app's
 *     private storage into the user's Google Drive, which is precisely the
 *     "your data leaves the EU without you asking" failure the product exists
 *     to prevent. Off, and off explicitly rather than by omission.
 *
 *  2. A network security config that permits cleartext only where a
 *     self-hoster genuinely needs it (loopback and RFC1918 hostnames cannot be
 *     expressed as domains, so this is a documented, deliberate allowance
 *     paired with an in-app warning banner — see src/features/settings/
 *     ServerScreen.tsx, which flags any non-HTTPS server URL).
 *
 * Recording's foreground service is NOT here any more, and deliberately. This
 * file used to declare one itself, named `expo.modules.audio.AudioFocusService`
 * — a class that does not exist in the expo-audio we ship. The manifest entry
 * was inert, pointing at nothing, while the real service
 * (`expo.modules.audio.service.AudioRecordingService`) went undeclared, so
 * prepareToRecordAsync() rejected at runtime. Worse, the entry looked like the
 * problem had been handled. expo-audio's own plugin declares the correct
 * service, with foregroundServiceType="microphone" and the matching
 * permissions, as soon as `enableBackgroundRecording: true` is passed — which
 * app.config.ts now does. One declaration, from the package that owns the class.
 *
 * The share-sheet intent filters (ACTION_SEND / ACTION_SEND_MULTIPLE) are NOT
 * here — expo-share-intent's own plugin writes them, because the filters are
 * only half the job: something native has to read Intent.EXTRA_STREAM and hand
 * it to JS, and that module is the half we would otherwise have to write.
 */

const {
    AndroidConfig,
    withAndroidManifest,
    withDangerousMod,
    createRunOncePlugin,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const { getMainApplicationOrThrow } = AndroidConfig.Manifest;

function withPrivacyHardening(config) {
    return withAndroidManifest(config, (cfg) => {
        const app = getMainApplicationOrThrow(cfg.modResults);
        app.$['android:allowBackup'] = 'false';
        app.$['android:fullBackupContent'] = 'false';
        app.$['android:dataExtractionRules'] = '@xml/data_extraction_rules';
        app.$['android:networkSecurityConfig'] = '@xml/network_security_config';
        return cfg;
    });
}

/** Write the two res/xml files the manifest attributes above point at. */
function withSecurityXml(config) {
    return withDangerousMod(config, [
        'android',
        async (cfg) => {
            const xmlDir = path.join(
                cfg.modRequest.platformProjectRoot,
                'app',
                'src',
                'main',
                'res',
                'xml',
            );
            fs.mkdirSync(xmlDir, { recursive: true });

            fs.writeFileSync(
                path.join(xmlDir, 'data_extraction_rules.xml'),
                `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by mobile/plugins/withBeeFlowAndroid.js — do not edit. -->
<!-- Bee Flow holds session tokens and, while unlocked, an unwrapped data
     encryption key. Neither cloud backup nor device-to-device transfer may
     carry them off the device. -->
<data-extraction-rules>
    <cloud-backup>
        <exclude domain="root" />
        <exclude domain="database" />
        <exclude domain="sharedpref" />
        <exclude domain="file" />
        <exclude domain="external" />
    </cloud-backup>
    <device-transfer>
        <exclude domain="root" />
        <exclude domain="database" />
        <exclude domain="sharedpref" />
        <exclude domain="file" />
        <exclude domain="external" />
    </device-transfer>
</data-extraction-rules>
`,
                'utf8',
            );

            fs.writeFileSync(
                path.join(xmlDir, 'network_security_config.xml'),
                `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by mobile/plugins/withBeeFlowAndroid.js — do not edit. -->
<!-- Cleartext is permitted because a self-hosted Bee Flow on a LAN may not
     have a certificate, and refusing http:// outright would make the app
     unusable for exactly the users the product is built for. The app does not
     stay quiet about it: ServerScreen flags any non-HTTPS server with a
     persistent warning, and the connection test refuses to remember an
     http:// host without an explicit confirmation. -->
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
            <!-- User-installed CAs are trusted so an admin can run an internal
                 CA for their own Bee Flow host. This is a self-hosted product;
                 an internal PKI is the normal case, not an attack. -->
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
`,
                'utf8',
            );

            return cfg;
        },
    ]);
}

/**
 * Gradle needs to know the release signing config exists. We do NOT write
 * keystore material here — CI injects it as files + gradle properties (see
 * .github/workflows/android-release.yml). This only makes the build read them
 * when present and fall back to debug signing when they are not, so that a
 * fork with no secrets configured still produces an installable APK.
 */
function withReleaseSigning(config) {
    return withDangerousMod(config, [
        'android',
        async (cfg) => {
            const gradle = path.join(cfg.modRequest.platformProjectRoot, 'app', 'build.gradle');
            let contents = fs.readFileSync(gradle, 'utf8');
            if (contents.includes('BEEFLOW_RELEASE_SIGNING')) return cfg;

            const block = `
    // BEEFLOW_RELEASE_SIGNING — injected by mobile/plugins/withBeeFlowAndroid.js
    //
    // A release build signs with the upload keystore when CI has provided one
    // (BEEFLOW_UPLOAD_STORE_FILE et al, written into gradle.properties by the
    // workflow) and falls back to the debug key otherwise. The fallback is the
    // point: a contributor's fork, or a PR build with no access to secrets,
    // still produces an APK you can install and try. Such an APK is signed with
    // a publicly-known key and is marked unsigned in the workflow's artifact
    // name — it is for testing, never for distribution.
    signingConfigs {
        beeflowRelease {
            if (project.hasProperty('BEEFLOW_UPLOAD_STORE_FILE')) {
                storeFile file(BEEFLOW_UPLOAD_STORE_FILE)
                storePassword BEEFLOW_UPLOAD_STORE_PASSWORD
                keyAlias BEEFLOW_UPLOAD_KEY_ALIAS
                keyPassword BEEFLOW_UPLOAD_KEY_PASSWORD
            }
        }
    }
`;
            contents = contents.replace(/android\s*\{/, (m) => `${m}\n${block}`);

            // Point the release buildType at it, replacing Expo's default
            // `signingConfig signingConfigs.debug` line inside buildTypes.
            contents = contents.replace(
                /(release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/,
                `$1signingConfig project.hasProperty('BEEFLOW_UPLOAD_STORE_FILE') ? signingConfigs.beeflowRelease : signingConfigs.debug`,
            );

            fs.writeFileSync(gradle, contents, 'utf8');
            return cfg;
        },
    ]);
}

/** @type {import('expo/config-plugins').ConfigPlugin} */
const withBeeFlowAndroid = (config) => {
    config = withPrivacyHardening(config);
    config = withSecurityXml(config);
    config = withReleaseSigning(config);
    return config;
};

module.exports = createRunOncePlugin(withBeeFlowAndroid, 'withBeeFlowAndroid', '1.0.0');
