/**
 * App Studio action executor — fill_document: render a Document the OWNER
 * designed in Studio, filled with this run's values, into a PDF in the app's
 * attachment store.
 *
 * THE SIBLING OF generate_file, deliberately down to the last step of the
 * pipeline: render → size gate before any I/O → storage availability → quota →
 * blob → AV scan → ledger row → the bare `studio_attachment` descriptor. Every
 * consumer of that descriptor (file_preview, send_email.attachments, a
 * file-column record write) therefore takes a filled invoice without learning
 * anything new. What differs is the artefact: generate_file writes ROWS into a
 * machine-readable file, this renders a DESIGNED page a person receives.
 *
 * WHOSE DOCUMENT, AND WHY THAT IS THE OWNER'S. An app runs acts-as-owner, the
 * letterhead it prints on is the company's, and `documentId` is authored INTO
 * the app by whoever built it — it is never a viewer's input. So the lookup is
 * scoped to `app.userId`, and a viewer cannot reach their own documents (or
 * anybody else's) through an app.
 *
 * GENERATED BYTES ARE SCANNED like any upload — not because we distrust our own
 * renderer, but because `scanned:true` on a ledger row must always mean "these
 * bytes were scanned"; three consumers key off that flag, and writing it
 * without scanning would make it a lie.
 */

'use strict';

const studioAppDataStore = require('../../stores/studioAppDataStore');
const { buildServerScope, resolveBinding, coerceRecordId } = require('./shared');
const log = require('../../telemetry/log');

// A document is a page of paper. The same cap the automation step and the
// validator use, so "how many values may a document be filled with" has one
// answer across the product.
const MAX_VALUES = 200;

/**
 * Resolve the `values` map: placeholder name → whatever the binding yields.
 *
 * Bindings are resolved WHOLE, so a records/aggregate binding bound to a list
 * placeholder arrives as a real array. That is the one thing a caller can get
 * wrong invisibly: a value flattened to text makes `{{#each lines}}` render
 * nothing, which reads as a broken template rather than a flattened binding.
 *
 * Dotted keys ("customer.name") are expanded into the nested object the filler
 * looks up, so each hole is its own field in the inspector instead of one JSON
 * blob nobody can edit.
 */
function buildValues(raw, ctx, scope) {
    const out = {};
    if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return out;
    if (Object.keys(raw).length > MAX_VALUES) throw new Error('Too many document values');
    for (const key of Object.keys(raw)) {
        const value = resolveBinding(raw[key], ctx, scope);
        if (value === undefined) continue;          // let the filler report the hole
        if (!require('../../core/documents/documentContract').safePath(key)) throw new Error('Unsafe document parameter path');
        const parts = String(key).split('.').filter(Boolean);
        if (!parts.length) continue;
        let cur = out;
        for (let i = 0; i < parts.length - 1; i++) {
            if (!cur[parts[i]] || typeof cur[parts[i]] !== 'object' || Array.isArray(cur[parts[i]])) cur[parts[i]] = {};
            cur = cur[parts[i]];
        }
        cur[parts[parts.length - 1]] = value;
    }
    return out;
}

/** Safe as a download attribute, a Content-Disposition value and a MIME header. */
function sanitizeFileName(name, fallback) {
    const flat = String(name == null ? '' : name).replace(/[/\\\r\n\0"<>|?*:;]/g, '').trim().slice(0, 120);
    return flat || fallback;
}

async function fillDocumentStep(app, model, step, ctx) {
    const scope = buildServerScope(ctx);

    const documentId = typeof step.documentId === 'string' ? step.documentId.trim() : '';
    if (!documentId) return { ok: false, error: 'This step has no document to fill' };

    const documentStore = require('../../stores/documentStore');
    const doc = await documentStore.getDocumentVersion(documentId, app.userId, step.documentVersionId);
    // Owner-scoped: a missing document and somebody else's are the same answer,
    // which is what keeps a document id from being an IDOR.
    if (!doc) return { ok: false, error: 'That document no longer exists' };

    const values = buildValues(step.values, ctx, scope);

    const { renderFilledDocument } = require('../../core/documents/renderFilledDocument');
    // A presentation document is a real .pptx (or the PDF deck when asked);
    // a page document is always a PDF.
    const isDeck = doc.docType === 'presentation';
    const format = isDeck ? (step.format === 'pdf' ? 'pdf' : 'pptx') : 'pdf';
    let rendered;
    try {
        rendered = await renderFilledDocument({
            document: doc,
            sectionOverrides: buildValues(step.sectionOverrides, ctx, scope),
            values,
            // The app's organisation decides the letterhead — an app prints on
            // the company's paper, not on the viewer's.
            orgId: app.organizationId || ctx.orgId || null,
            marking: null,
            format,
            resolveImage: isDeck ? require('../../services/presentationRenderer').makeUserImageResolver(app.userId) : null,
        });
    } catch (e) {
        // document_empty is the author's mistake and worth saying plainly; the
        // rest collapse to a generic message like every other step's failure.
        if (e && e.errorClass === 'document_empty') return { ok: false, error: 'That document is empty, so there is nothing to render' };
        if (e?.errorClass?.startsWith('document_')) return {ok:false,error:e.message,code:e.errorClass,issues:e.issues || [],documentVersionId:doc.versionId};
        throw e;
    }
    const { buffer, contentType, degraded, fill } = rendered;

    // Size gate BEFORE any I/O.
    const { DATA_LIMITS } = require('../dataModel');
    if (buffer.length > DATA_LIMITS.MAX_ATTACHMENT_BYTES) {
        return { ok: false, error: `The document is larger than the ${Math.round(DATA_LIMITS.MAX_ATTACHMENT_BYTES / (1024 * 1024))} MB attachment limit` };
    }

    const storageStore = require('../../stores/storageStore');
    if (!storageStore.isAvailable()) return { ok: false, error: 'File storage is not available' };

    // Quota before bytes — a 409 must not cost an upload.
    const studioAppQuota = require('../studioAppQuota');
    const { assertAttachmentTotalBytes } = require('../mailboxAttachments');
    await studioAppQuota.assertAttachmentQuota(app, buffer.length);
    await assertAttachmentTotalBytes(app, buffer.length);

    const fileName = `${sanitizeFileName(resolveBinding(step.fileName, ctx, scope) || doc.name, 'document').replace(new RegExp(`\\.${format}$`, 'i'), '')}.${format}`;

    const crypto = require('crypto');
    const sha256 = crypto.createHash('sha256').update(buffer).digest('hex');
    const key = storageStore.buildStudioAppAttachmentKey(app.userId, app.id, sha256);
    await storageStore.uploadFile(key, buffer, contentType);

    const { scanBuffer } = require('../../middleware/uploadGuard');
    const verdict = await scanBuffer(buffer);
    if (!verdict.clean) {
        await storageStore.deleteFile(key).catch(() => {});
        return { ok: false, error: 'The generated document failed a malware scan and was discarded' };
    }

    // attachTo — the access path for everyone but the owner. Resolved AFTER the
    // scan so a dirty file never gets a ledger row, linked or not.
    const attachToRecordId = coerceRecordId(resolveBinding(step.attachToRecordId, ctx, scope));
    const fieldKey = typeof step.attachToFieldKey === 'string' && step.attachToFieldKey ? step.attachToFieldKey : null;

    let ledger;
    try {
        ledger = await studioAppDataStore.addAttachment(app.id, app.userId, {
            recordId: attachToRecordId || null,
            fieldKey: attachToRecordId ? fieldKey : null,
            mimeType: contentType,
            sha256,
            size: buffer.length,
        });
        await studioAppDataStore.setAttachmentScan(ledger.id, app.id, app.userId, { scanned: true, quarantined: false });
    } catch (e) {
        // Never orphan a blob behind a failed ledger write.
        await storageStore.deleteFile(key).catch(() => {});
        throw e;
    }

    if (degraded) {
        log.warn(`[fill_document] app ${app.id}: rendered without a browser — the PDF uses the plain fallback layout, so the document's own styling is lost.`);
    }

    return {
        ok: true,
        result: {
            kind: 'studio_attachment',
            fileId: ledger.id,
            name: fileName,
            mime: contentType,
            size: buffer.length,
            documentId: doc.id,
            documentVersionId: doc.versionId,
            documentName: doc.name,
            format,
            ...(isDeck ? { slideCount: rendered.slideCount || 0 } : {}),
            // The NAMES of the placeholders nothing filled — never the values.
            // A screen can show "3 fields were left blank" and a condition can
            // branch on it; the alternative is finding out on the paper.
            missing: fill.missing,
        sections: fill.sections,
        validation: fill.issues,
            ...(degraded ? { degraded: true } : {}),
        },
    };
}

module.exports = { fillDocumentStep, _test: { buildValues, sanitizeFileName } };
