/**
 * App Studio action executor — generate_file (extracted verbatim from
 * actionExecutor.js): render rows into a real CSV/spreadsheet in the app's
 * attachment store — size gates, quota, blob, AV scan, ledger row.
 */

'use strict';

const studioAppDataStore = require('../../stores/studioAppDataStore');
const { buildServerScope, resolveBinding, coerceRecordId, writeViewer } = require('./shared');

// ── generate_file ───────────────────────────────────────────────────

// Export ceilings. Rows: far above the prompt cap (an export legitimately
// wants every project line where a prompt wants a summary) but still under the
// query compiler's own MAX_RESULT_ROWS, so no binding can escape the hard
// limit. Cells: a second axis, so a 100-column table cannot smuggle a huge
// render through a modest row count.
const MAX_EXPORT_ROWS = 1000;
const MAX_EXPORT_CELLS = 100000;

// The display name lands in a download attribute, a Content-Disposition-ish
// context and (via send_email) a MIME header — never on a filesystem path,
// but path characters and CR/LF have no business in any of those either.
function sanitizeGeneratedFileName(name, fallback) {
    // Colon: Windows-illegal, and thread keys ('gmail:…') are the obvious
    // binding to reach for. Semicolon: it is the CSV delimiter this feature
    // exists to write, and a delimiter in the NAME confuses every downstream.
    const flat = String(name == null ? '' : name).replace(/[/\\\r\n\0"<>|?*:;]/g, '').trim().slice(0, 120);
    return flat || fallback;
}

/**
 * Normalise the resolved `columns` binding into [{ name, from?, value? }].
 *
 * Rows may come straight from a portal-format TABLE (that is the point: the
 * file format is data the admin edits, not code), so entries are filtered on
 * `active !== false`, sorted by a numeric `order` when one is present, and
 * anything without a printable `name` is dropped.
 */
function normalizeExportColumns(raw) {
    const list = Array.isArray(raw) ? raw : [];
    const cols = [];
    for (const entry of list) {
        if (typeof entry === 'string' && entry.trim()) { cols.push({ name: entry.trim(), from: entry.trim() }); continue; }
        if (!entry || typeof entry !== 'object') continue;
        if (entry.active === false || entry.active === 0) continue;
        const name = typeof entry.name === 'string' ? entry.name.trim() : '';
        if (!name) continue;
        cols.push({
            name,
            from: typeof entry.from === 'string' && entry.from ? entry.from : null,
            value: entry.value === undefined ? null : entry.value,
            order: Number.isFinite(Number(entry.order)) ? Number(entry.order) : null,
        });
    }
    // Stable: entries without an order keep their list position, after the
    // ordered ones — matches how the seeded portal-format table reads.
    return cols
        .map((c, i) => ({ ...c, _i: i }))
        .sort((a, b) => {
            if (a.order !== null && b.order !== null) return a.order - b.order || a._i - b._i;
            if (a.order !== null) return -1;
            if (b.order !== null) return 1;
            return a._i - b._i;
        })
        .map(({ _i, order, ...c }) => c);
}

/**
 * Render rows into a real file in the app's attachment store.
 *
 * The full flow, cheap refusals first: resolve rows (data bindings run through
 * stepDataSource under the VIEWER's access filter) → render → size gate before
 * any I/O → storage availability → quota → blob → AV scan → ledger row. The
 * result is the BARE studio_attachment descriptor, which file_preview,
 * send_email.attachments and file-column record writes all already accept.
 *
 * Generated bytes are scanned like any upload — not because we distrust our
 * own CSV writer, but because `scanned:true` on a ledger row must always mean
 * "these bytes were scanned"; three consumers key off that flag, and writing
 * it without scanning would make it a lie.
 */
async function generateFileStep(app, model, step, ctx) {
    const scope = buildServerScope(ctx);
    const stepDataSource = require('../stepDataSource');

    // rows — the one binding here that may READ.
    let rows;
    if (stepDataSource.isDataBinding(step.rows)) {
        rows = await stepDataSource.resolveDataBinding(app, model, step.rows, {
            viewer: writeViewer(ctx),
            role: ctx.role ?? null,
            resolveValue: (b) => resolveBinding(b, ctx, scope),
            maxRows: MAX_EXPORT_ROWS,
        });
    } else {
        rows = resolveBinding(step.rows, ctx, scope);
    }
    if (rows && typeof rows === 'object' && !Array.isArray(rows)) rows = [rows];
    if (!Array.isArray(rows)) return { ok: false, error: 'This step has no rows to write' };
    // A zero-row file that downloads as a lone header line is the failure
    // nobody notices until the portal import comes back empty. Refuse loudly.
    if (rows.length === 0) return { ok: false, error: 'There are no rows to put in the file' };
    let truncated = false;
    if (rows.length > MAX_EXPORT_ROWS) { rows = rows.slice(0, MAX_EXPORT_ROWS); truncated = true; }

    // columns — the editable format profile.
    const officegen = require('../../integrations/officegen');
    const columns = normalizeExportColumns(
        stepDataSource.isDataBinding(step.columns)
            ? await stepDataSource.resolveDataBinding(app, model, step.columns, {
                viewer: writeViewer(ctx),
                role: ctx.role ?? null,
                resolveValue: (b) => resolveBinding(b, ctx, scope),
                maxRows: 100,
            })
            : resolveBinding(step.columns, ctx, scope),
    );

    let matrix;
    if (columns.length) {
        if (rows.length * columns.length > MAX_EXPORT_CELLS) {
            return { ok: false, error: 'The file would be too large to generate' };
        }
        const header = columns.map((c) => c.name);
        matrix = rows.map((row) => columns.map((c) => {
            if (c.from) return row?.[c.from] ?? '';
            if (c.value !== null && c.value !== undefined) return c.value;
            return row?.[c.name] ?? '';
        }));
        if (step.includeHeader !== false) matrix.unshift(header);
    } else {
        matrix = officegen.rowsToMatrix(rows);
        if (matrix.length && matrix[0].length && matrix.length * matrix[0].length > MAX_EXPORT_CELLS) {
            return { ok: false, error: 'The file would be too large to generate' };
        }
        if (step.includeHeader === false) matrix.shift();
    }

    const format = officegen.CONTENT_TYPES[step.format] ? step.format : 'csv';
    const fileNameRaw = resolveBinding(step.fileName, ctx, scope);
    const fileName = officegen.ensureExt(
        sanitizeGeneratedFileName(fileNameRaw, 'export'),
        format,
    );

    let rendered;
    if (format === 'csv') {
        // `bom !== false` rather than a truthy check: the spec default is ON
        // (Excel needs it for accented characters), so only an explicit false
        // turns it off — for a CSV a MACHINE imports, where three extra bytes
        // in front of the first header cell are a parse error waiting to happen.
        rendered = officegen.buildCsv({ matrix, delimiter: step.delimiter || ';', bom: step.bom !== false });
    } else {
        rendered = await officegen.buildSpreadsheet({
            matrix,
            sheetName: step.sheetName || fileName.replace(/\.[a-z0-9]+$/i, ''),
            format,
        });
    }
    const { buffer, contentType } = rendered;

    // Size gate BEFORE any I/O.
    const { DATA_LIMITS } = require('../dataModel');
    if (buffer.length > DATA_LIMITS.MAX_ATTACHMENT_BYTES) {
        return { ok: false, error: `The generated file is larger than the ${Math.round(DATA_LIMITS.MAX_ATTACHMENT_BYTES / (1024 * 1024))} MB attachment limit` };
    }

    const storageStore = require('../../stores/storageStore');
    if (!storageStore.isAvailable()) return { ok: false, error: 'File storage is not available' };

    // Quota before bytes — a 409 must not cost an upload. Both asserts throw
    // the frozen quota shape; executeDataStep's catch maps it for the client.
    const studioAppQuota = require('../studioAppQuota');
    const { assertAttachmentTotalBytes } = require('../mailboxAttachments');
    await studioAppQuota.assertAttachmentQuota(app, buffer.length);
    await assertAttachmentTotalBytes(app, buffer.length);

    const crypto = require('crypto');
    const sha256 = crypto.createHash('sha256').update(buffer).digest('hex');
    const key = storageStore.buildStudioAppAttachmentKey(app.userId, app.id, sha256);
    await storageStore.uploadFile(key, buffer, contentType);

    const { scanBuffer } = require('../../middleware/uploadGuard');
    const verdict = await scanBuffer(buffer);
    if (!verdict.clean) {
        await storageStore.deleteFile(key).catch(() => {});
        return { ok: false, error: 'The generated file failed a malware scan and was discarded' };
    }

    // attachTo — the access path for everyone but the owner. Resolved AFTER the
    // scan so a dirty file never gets a ledger row, linked or not.
    const attachToRecordId = coerceRecordId(resolveBinding(step.attachToRecordId, ctx, scope));
    const fieldKey = typeof step.attachToFieldKey === 'string' && step.attachToFieldKey ? step.attachToFieldKey : null;

    let ledger;
    try {
        ledger = await studioAppDataStore.addAttachment(app.id, app.userId, {
            recordId: attachToRecordId || null,
            fieldKey: attachToRecordId ? fieldKey : null,
            mimeType: contentType,
            sha256,
            size: buffer.length,
        });
        await studioAppDataStore.setAttachmentScan(ledger.id, app.id, app.userId, { scanned: true, quarantined: false });
    } catch (e) {
        // Never orphan a blob behind a failed ledger write — same healing the
        // mailbox redemption does.
        await storageStore.deleteFile(key).catch(() => {});
        throw e;
    }

    return {
        ok: true,
        result: {
            kind: 'studio_attachment',
            fileId: ledger.id,
            name: fileName,
            mime: contentType,
            size: buffer.length,
            rowCount: rows.length,
            ...(truncated ? { truncated: true } : {}),
        },
    };
}

module.exports = { generateFileStep };
