/**
 * Expo app config for Bee Flow on Android.
 *
 * Dynamic (`.ts`, not `app.json`) for two reasons the build actually depends on:
 *
 *   1. `versionCode` has to be an integer that never repeats and never goes
 *      down, across every repository this app is ever built in. CI computes
 *      it from the build time (see .github/workflows/android-release.yml) and
 *      passes it as `BEEFLOW_VERSION_CODE`; locally it falls back to 1 so
 *      `expo run:android` works with no env at all.
 *   2. The default server URL is a BUILD-TIME choice. A self-hoster forks this
 *      repo and builds their own APK against their own host, so it comes from
 *      `BEEFLOW_DEFAULT_SERVER_URL` rather than being hard-coded to beeflow.nl.
 *      Users can still change it in-app (Settings → Server); this only seeds it.
 *
 * The native `android/` directory is NOT committed — it is generated by
 * `expo prebuild` from this file on every build (Expo's "continuous native
 * generation"). That means this file is the single source of truth for the
 * manifest, permissions, icons and Gradle properties: never hand-edit a
 * generated android/ file, it will be thrown away on the next build.
 */

import type { ConfigContext, ExpoConfig } from 'expo/config';

/**
 * The oldest server this APK is known to work against — a build DATE, because
 * the server has no orderable version number (see src/core/api/contract.ts, where
 * the app reads this from). A LITERAL here, not an import: expo's config
 * loader transpiles only this file, so a `./src/...` import cannot resolve at
 * config time. contract.test.ts pins the two copies to the same value.
 */
const minServerBuild = '2026-09-01';

/** CI passes a time-based code; a local build just wants *something* valid. */
const versionCode = Number(process.env.BEEFLOW_VERSION_CODE || '1');

/** Marketing version — kept in step with package.json so there is one number. */
const version = require('./package.json').version as string;

/**
 * Where a fresh install points before the user says otherwise. Empty string is
 * a deliberate, meaningful value: it makes the first-run screen ASK for a
 * server instead of silently defaulting to the SaaS, which is the correct
 * behaviour for a self-host-first product.
 */
const defaultServerUrl = process.env.BEEFLOW_DEFAULT_SERVER_URL || '';

/**
 * Which channel is being built. Only 'prod' pays for the expensive parts of a
 * release build; a dev APK exists to be installed on a phone and tried.
 */
const isProdBuild = process.env.BEEFLOW_BUILD_PROFILE === 'prod';

/**
 * The publisher's privacy policy, linked from Settings → About → Privacy.
 * Google Play requires one inside the app as well as on the store listing,
 * and it is the PUBLISHER's policy (whoever uploads this build), not the
 * organisation's: an org's own privacy notice lives in its compliance
 * settings, which only admins can read. A self-hoster who publishes their own
 * build sets BEEFLOW_PRIVACY_POLICY_URL.
 *
 * TODO(owner): confirm https://beeflow.nl/privacy is live and covers the
 * Android app before the first Play submission.
 */
const privacyPolicyUrl = process.env.BEEFLOW_PRIVACY_POLICY_URL || 'https://beeflow.nl/privacy';

// The documents someone shares into Bee Flow — to ask about in a chat, or
// to put in a knowledge base: PDF, Word, Excel, PowerPoint and their
// OpenDocument twins. (Text, CSV and Markdown are text/*.)
const SHARED_DOCUMENTS = [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.oasis.opendocument.text',
    'application/vnd.oasis.opendocument.spreadsheet',
    'application/rtf',
];

export default ({ config }: ConfigContext): ExpoConfig => ({
    ...config,
    name: 'Bee Flow',
    slug: 'bee-flow',
    version,
    orientation: 'default',
    icon: './assets/icon.png',
    scheme: 'beeflow',
    userInterfaceStyle: 'automatic',
    // The splash background must match the dark theme's --bg-primary, or the
    // app flashes white for a frame between the system splash and first paint.
    backgroundColor: '#0f0f13',
    primaryColor: '#9ca3af',
    assetBundlePatterns: ['**/*'],
    /**
     * This app targets Android only — there is no iOS build and no plan for
     * one. The block exists because expo-share-intent's plugin reads
     * `ios.bundleIdentifier` unconditionally while configuring its share
     * extension, and crashes prebuild with an unhelpful
     * "Cannot read properties of undefined" when it is absent. Declaring the
     * identifier costs nothing and keeps `expo prebuild --platform android`
     * working.
     */
    ios: {
        bundleIdentifier: 'nl.beeflow.app',
    },
    android: {
        package: 'nl.beeflow.app',
        versionCode,
        adaptiveIcon: {
            foregroundImage: './assets/adaptive-icon.png',
            monochromeImage: './assets/adaptive-icon-monochrome.png',
            // Brand yellow (--accent-primary of the Bee Flow theme) behind the
            // ink bee; the bee sits inside the 66dp safe circle of the 108dp layer.
            backgroundColor: '#ffd400',
        },
        // Edge-to-edge is unconditional from SDK 54 on (and mandatory on
        // Android 15), so there is no flag to set — every screen goes through
        // src/shared/ui/Screen.tsx, which is where the insets are actually handled.
        softwareKeyboardLayoutMode: 'pan',
        // No auto-backup and no device-to-device transfer of app data: the
        // session token and the sealed drafts are bound to a Keystore key
        // that never leaves this device, so a restored copy could not be
        // opened anyway — it could only leak. plugins/withBeeFlowAndroid.js
        // also forces this (and writes dataExtractionRules for Android 12+);
        // setting it here keeps Expo's own allowBackup mod from writing
        // "true" first.
        allowBackup: false,
        blockedPermissions: [
            // expo-audio and expo-image-picker each pull in permissions we do
            // not want on a privacy product. Recording needs the microphone,
            // not the user's location or phone state; the media library is
            // read through the system picker, which needs no broad read.
            'android.permission.ACCESS_COARSE_LOCATION',
            'android.permission.ACCESS_FINE_LOCATION',
            'android.permission.READ_EXTERNAL_STORAGE',
            'android.permission.WRITE_EXTERNAL_STORAGE',
            'android.permission.READ_MEDIA_IMAGES',
            'android.permission.READ_MEDIA_VIDEO',
            // "Display over other apps". React Native declares it in the MAIN
            // manifest, so without this it ships in the release APK and shows
            // up in the install prompt of a privacy product that has no use
            // for it. Removing it here does not affect development: the
            // manifest merger ranks a build-type manifest above main, and
            // android/app/src/debug/AndroidManifest.xml declares it for the
            // dev overlay.
            'android.permission.SYSTEM_ALERT_WINDOW',
            // Background PLAYBACK. expo-audio adds it by default and media3's
            // session library declares it again in its own manifest. The app
            // never plays audio in the background (no lock-screen controls,
            // enableBackgroundPlayback is off below), and on targetSdk 34+
            // every FOREGROUND_SERVICE_<type> permission is a Play Console
            // declaration with a demo video. Only the microphone type stays.
            'android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK',
            // No ads, no analytics SDK. Firebase (pulled in by
            // expo-notifications, never initialised: no google-services.json)
            // must not smuggle the advertising-ID permission into the
            // manifest, or Play's advertising-ID declaration has to say yes.
            'com.google.android.gms.permission.AD_ID',
        ],
        permissions: [
            'android.permission.RECORD_AUDIO',
            'android.permission.CAMERA',
            'android.permission.INTERNET',
            'android.permission.ACCESS_NETWORK_STATE',
            'android.permission.USE_BIOMETRIC',
            'android.permission.POST_NOTIFICATIONS',
            'android.permission.VIBRATE',
            // Recording a meeting must survive the screen turning off, which
            // on Android 14+ requires a typed foreground service.
            'android.permission.FOREGROUND_SERVICE',
            'android.permission.FOREGROUND_SERVICE_MICROPHONE',
        ],
        // NOTE: MainActivity's `launchMode` is `singleTask`, which Expo sets by
        // default and which the OAuth flow now DEPENDS ON. A beeflow:// link
        // arriving while sign-in is in progress must reach the RUNNING activity
        // via onNewIntent — that is what lets expo-web-browser's lifecycle
        // listener close the Custom Tab (WebBrowserPackage → finishAndRemoveTask),
        // and it is also how the pending auth promise survives. On a `standard`
        // activity the proxy's CLEAR_TOP relaunch would tear MainActivity down
        // and rebuild it, destroying the in-flight sign-in. android/ is
        // generated and gitignored, so this constraint has nowhere to live but
        // here. See mobile/src/features/onboarding/api/sso.ts.
        intentFilters: [
            {
                // beeflow://oauth — the OAuth handoff. Not a destination: it
                // exists to hand control back to the app, and
                // app/+native-intent.ts swallows it so the router does not try
                // to navigate anywhere.
                //
                // Unverified on purpose. Verified App Links would need an
                // assetlinks.json on the host, which a self-hoster may not
                // have; a private scheme needs no such thing, and carries
                // nothing worth intercepting (RFC 8252 §8.6 — any app may
                // register a scheme, so the link is deliberately empty).
                action: 'VIEW',
                autoVerify: false,
                data: [{ scheme: 'beeflow' }],
                category: ['BROWSABLE', 'DEFAULT'],
            },
        ],
    },
    plugins: [
        'expo-router',
        'expo-secure-store',
        'expo-localization',
        'expo-web-browser',
        [
            'expo-splash-screen',
            {
                image: './assets/splash-icon.png',
                imageWidth: 180,
                resizeMode: 'contain',
                backgroundColor: '#0f0f13',
                dark: { backgroundColor: '#0f0f13' },
            },
        ],
        [
            'expo-audio',
            {
                microphonePermission:
                    'Bee Flow needs the microphone to record meetings and voice notes for transcription.',
                // Without this the plugin never declares expo-audio's own
                // AudioRecordingService in the manifest, and never requests
                // FOREGROUND_SERVICE_MICROPHONE or POST_NOTIFICATIONS — so
                // prepareToRecordAsync() rejects at runtime with "Failed to
                // start the recording service" and Record is dead on arrival.
                //
                // It is also what the Record screen already promises out loud:
                // "keeps going when the screen locks". A meeting recording that
                // stops when the phone sleeps is worse than no recording, and
                // the copy was written for a capability the build did not have.
                enableBackgroundRecording: true,
                // The default (true) declares expo-audio's media-playback
                // foreground service for lock-screen controls, which nothing
                // in this app uses (no setActiveForLockScreen). Off, so the
                // manifest carries one foreground service type — microphone —
                // and Play asks for one declaration, not two.
                enableBackgroundPlayback: false,
            },
        ],
        [
            'expo-camera',
            {
                cameraPermission:
                    'Bee Flow needs the camera to scan documents into your knowledge base.',
                recordAudioAndroid: false,
            },
        ],
        [
            'expo-image-picker',
            {
                photosPermission: 'Bee Flow needs access to photos you choose to attach to a chat.',
                cameraPermission: 'Bee Flow needs the camera to attach a photo to a chat.',
            },
        ],
        [
            'expo-local-authentication',
            { faceIDPermission: 'Unlock Bee Flow with biometrics.' },
        ],
        [
            'expo-share-intent',
            {
                // Bee Flow appears in Android's share sheet for text, images,
                // audio and documents. Sharing a PDF from Drive straight into a
                // knowledge base is the thing a mobile client can do that a
                // browser tab cannot — so a SINGLE document has to be listed
                // too: Android offers an app for one shared PDF only when its
                // single-share filter names the type (it named text and media
                // only, so Bee Flow appeared for two PDFs but never for one).
                // src/meta/shareTargets.test.ts holds both lists to this.
                androidIntentFilters: ['text/*', 'image/*', 'audio/*', 'video/*', ...SHARED_DOCUMENTS],
                androidMultiIntentFilters: ['text/*', 'image/*', 'audio/*', 'video/*', ...SHARED_DOCUMENTS],
                disableAndroidLegacyIntentFilters: false,
            },
        ],
        [
            'expo-notifications',
            {
                icon: './assets/notification-icon.png',
                color: '#9ca3af',
                // Notifications are scheduled LOCALLY from polled server state.
                // There is no FCM sender id here on purpose — see
                // src/features/notifications/README.md.
                enableBackgroundRemoteNotifications: false,
            },
        ],
        [
            'expo-build-properties',
            {
                android: {
                    compileSdkVersion: 36,
                    targetSdkVersion: 36,
                    minSdkVersion: 24,
                    buildToolsVersion: '36.0.0',
                    // Shrink + strip, but ONLY for prod. An unshrunk release
                    // APK is ~30 MB larger, which matters for a direct
                    // download — and R8 is also several minutes of the build,
                    // which matters more when the artifact is a dev build
                    // somebody is waiting on to try a change. Size is worth
                    // paying for in a release; it is not worth paying for in
                    // a PR build.
                    enableProguardInReleaseBuilds: isProdBuild,
                    enableShrinkResourcesInReleaseBuilds: isProdBuild,
                    // A self-hoster on a LAN may only have http://, so
                    // cleartext stays allowed in release builds — a deliberate
                    // product decision, not an oversight. The network security
                    // config written by plugins/withBeeFlowAndroid.js is what
                    // Android actually reads (it overrides this flag on API
                    // 24+). It cannot be narrowed to "the host the user
                    // typed", because that host is chosen at runtime; the
                    // guard is the in-app warning on any http:// server
                    // instead.
                    usesCleartextTraffic: true,
                },
            },
        ],
        './plugins/withBeeFlowAndroid.js',
    ],
    experiments: {
        typedRoutes: true,
        reactCompiler: true,
    },
    extra: {
        defaultServerUrl,
        // Surfaced in Settings → About so a bug report names an exact build.
        buildProfile: process.env.BEEFLOW_BUILD_PROFILE || 'development',
        commitSha: process.env.BEEFLOW_COMMIT_SHA || '',
        // Stamped into the artifact so a build names the server it needs even
        // off-device (About screen, release notes, `expo config` output).
        minServerBuild,
        privacyPolicyUrl,
    },
});
