/**
 * Nextcloud Login Flow v2 — pairing a Nextcloud account from the desktop.
 *
 * The user's Bee Flow server already knows how to read their Nextcloud files;
 * what it needs is a credential (server/stores/user/appPasswords.js stores one
 * per user, sealed). Until now that credential came from an OAuth session or
 * from the user pasting an app password they generated by hand.
 *
 * A desktop client can do better, and Nextcloud has an interface built for
 * exactly this case. Login Flow v2 is the same handshake the Nextcloud desktop
 * client itself uses:
 *
 *   1. POST /index.php/login/v2 → a login URL and a poll token
 *   2. the login URL opens in the user's real browser, where their existing
 *      Nextcloud session, their SSO and their second factor all already work
 *   3. polling the endpoint returns an app password once they approve
 *
 * The password never passes through a page this app rendered, there is no
 * embedded login form to phish, and the credential that comes back is
 * app-scoped and individually revocable from the user's Nextcloud security
 * settings. Nothing here ever writes it to a log.
 */

import { loginFlowUrl } from './links.ts';
import { normaliseServerUrl } from '../server/url.ts';

export interface LoginFlowStart {
    /** Where to send the user's browser. */
    loginUrl: string;
    /** Where to poll, and with what. */
    pollEndpoint: string;
    pollToken: string;
}

export interface LoginFlowCredential {
    /** The server as Nextcloud itself reports it — not as the user typed it. */
    server: string;
    loginName: string;
    appPassword: string;
}

export type FetchLike = (
    url: string,
    init?: { method?: string; headers?: Record<string, string>; body?: string; signal?: AbortSignal },
) => Promise<{ ok: boolean; status: number; json(): Promise<unknown>; text(): Promise<string> }>;

export interface LoginFlowOptions {
    fetch: FetchLike;
    /** Poll interval. Nextcloud's own client uses one second. */
    intervalMs?: number;
    /** Give up after this long. Nextcloud expires the flow at 20 minutes. */
    timeoutMs?: number;
    /** Injected so tests do not wait in real time. */
    sleep?: (ms: number, signal?: AbortSignal) => Promise<void>;
    now?: () => number;
}

export const DEFAULT_POLL_INTERVAL_MS = 1_000;
export const DEFAULT_FLOW_TIMEOUT_MS = 20 * 60_000;

/** A User-Agent Nextcloud shows the user on the grant screen and in Security: an app name, not a username. */
// nosemgrep: ajinabraham.njsscan.generic.hardcoded_secrets.node_username
export const LOGIN_FLOW_USER_AGENT = 'Bee Flow Desktop';

/**
 * Begin the flow. Returns where to send the browser and how to poll.
 *
 * The `OCS-APIRequest` header is what makes Nextcloud answer with JSON rather
 * than the HTML login page; without it the response parses as garbage and the
 * failure looks like a broken server.
 */
export async function startLoginFlow(serverUrl: string, options: LoginFlowOptions): Promise<LoginFlowStart> {
    const normalised = normaliseServerUrl(serverUrl);
    if (!normalised.ok) throw new Error(normalised.error);

    const response = await options.fetch(loginFlowUrl(normalised.url), {
        method: 'POST',
        headers: {
            'User-Agent': LOGIN_FLOW_USER_AGENT,
            Accept: 'application/json',
            'OCS-APIRequest': 'true',
        },
    });

    if (!response.ok) {
        throw new Error(
            response.status === 404
                ? 'That server did not offer the Nextcloud login flow. Check the address, or whether it is a Nextcloud at all.'
                : `Nextcloud answered with HTTP ${response.status} when the sign-in was requested.`,
        );
    }

    const payload = (await response.json()) as { poll?: { token?: unknown; endpoint?: unknown }; login?: unknown };
    const loginUrl = typeof payload?.login === 'string' ? payload.login : '';
    const pollEndpoint = typeof payload?.poll?.endpoint === 'string' ? payload.poll.endpoint : '';
    const pollToken = typeof payload?.poll?.token === 'string' ? payload.poll.token : '';

    if (!loginUrl || !pollEndpoint || !pollToken) {
        throw new Error('That server answered the sign-in request with something unexpected.');
    }

    // The login and poll URLs come back from the server, and this app is about
    // to open one in a browser. A server that hands back a URL on a different
    // host is either misconfigured behind a proxy or redirecting the user
    // somewhere they did not ask to go; neither is worth following.
    assertSameHost(normalised.url, loginUrl, 'sign-in');
    assertSameHost(normalised.url, pollEndpoint, 'polling');

    return { loginUrl, pollEndpoint, pollToken };
}

/**
 * Poll until the user approves, the flow expires, or the caller cancels.
 *
 * Nextcloud answers 404 for "not yet" — which is why a plain `response.ok`
 * check is not enough to tell "still waiting" from "this endpoint is gone".
 */
export async function pollLoginFlow(
    start: LoginFlowStart,
    options: LoginFlowOptions & { signal?: AbortSignal },
): Promise<LoginFlowCredential> {
    const intervalMs = options.intervalMs ?? DEFAULT_POLL_INTERVAL_MS;
    const timeoutMs = options.timeoutMs ?? DEFAULT_FLOW_TIMEOUT_MS;
    const now = options.now ?? Date.now;
    const sleep = options.sleep ?? defaultSleep;
    const startedAt = now();

    for (;;) {
        if (options.signal?.aborted) throw new Error('The Nextcloud sign-in was cancelled.');
        if (now() - startedAt > timeoutMs) {
            throw new Error('The Nextcloud sign-in was not completed in time. Start it again when you are ready.');
        }

        const response = await options.fetch(start.pollEndpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                Accept: 'application/json',
                'User-Agent': LOGIN_FLOW_USER_AGENT,
            },
            body: new URLSearchParams({ token: start.pollToken }).toString(),
            ...(options.signal ? { signal: options.signal } : {}),
        });

        if (response.status === 404) {
            await sleep(intervalMs, options.signal);
            continue;
        }

        if (!response.ok) {
            throw new Error(`Nextcloud answered with HTTP ${response.status} while waiting for the sign-in.`);
        }

        const payload = (await response.json()) as { server?: unknown; loginName?: unknown; appPassword?: unknown };
        const server = typeof payload?.server === 'string' ? payload.server.replace(/\/+$/, '') : '';
        const loginName = typeof payload?.loginName === 'string' ? payload.loginName : '';
        const appPassword = typeof payload?.appPassword === 'string' ? payload.appPassword : '';

        if (!server || !loginName || !appPassword) {
            throw new Error('Nextcloud completed the sign-in but did not return a usable credential.');
        }

        assertSameHost(start.pollEndpoint, server, 'credential');
        return { server, loginName, appPassword };
    }
}

/**
 * Refuse a URL that moved to another host mid-flow.
 *
 * The message never contains the credential; only hosts.
 */
function assertSameHost(expected: string, actual: string, what: string): void {
    let expectedHost: string;
    let actualHost: string;
    try {
        expectedHost = new URL(expected).host;
        actualHost = new URL(actual).host;
    } catch {
        throw new Error(`The ${what} address Nextcloud returned is not a valid URL.`);
    }
    if (expectedHost !== actualHost) {
        throw new Error(`Nextcloud returned a ${what} address on ${actualHost}, which is not the server you asked for (${expectedHost}).`);
    }
}

function defaultSleep(ms: number, signal?: AbortSignal): Promise<void> {
    return new Promise((resolve, reject) => {
        const timer = setTimeout(resolve, ms);
        signal?.addEventListener(
            'abort',
            () => {
                clearTimeout(timer);
                reject(new Error('The Nextcloud sign-in was cancelled.'));
            },
            { once: true },
        );
    });
}
