/**
 * BeeFlow Install Wizard -- Backend Server
 *
 * Lightweight Express server that:
 * - Serves the wizard UI (static files)
 * - Detects GPU availability
 * - Builds config env vars and deploys containers
 * - Orchestrates container deployment via Docker socket
 *
 * All configuration is passed as environment variables directly
 * to the docker compose child process -- no .env file is written.
 */

const express = require('express');
const { execSync, spawn } = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { InstallBody, UpdateBody, buildInstallConfig, resolveUpdateServices } = require('./lib/installPlan');
const { createRemoteDigest, registryTransportOptions } = require('./lib/registryDigest');

const app = express();
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

const PROJECT_ROOT = '/project';
// Allow override via env var (used by install-from-registry.sh)
const COMPOSE_FILE = process.env.COMPOSE_FILE
    ? path.join(PROJECT_ROOT, process.env.COMPOSE_FILE)
    : path.join(PROJECT_ROOT, 'docker-compose.install.yml');

// HOST_PROJECT_DIR (passed by install.sh) reaches docker compose through
// process.env, which every compose spawn inherits, so bind-mount paths
// resolve on the Docker *host*, not inside this wizard container.

// Registry mode: pull images from Harbor instead of building locally
const REGISTRY_MODE  = process.env.REGISTRY_MODE === '1';
const REGISTRY_URL   = process.env.REGISTRY_URL   || '';
const REGISTRY_USER  = process.env.REGISTRY_USER  || '';
const REGISTRY_TOKEN = process.env.REGISTRY_TOKEN || '';
// Opt-ins for the update check against a registry without verified TLS
// (REGISTRY_INSECURE_TLS=1, REGISTRY_ALLOW_HTTP=1); both off by default.
const REGISTRY_TRANSPORT = registryTransportOptions(process.env);

// ── Auto-generate compose file in registry mode ─────────────────
// When the wizard runs as a container (Portainer stack), /project is
// an empty volume. In registry mode we generate the compose file so
// docker compose pull/up can work without any pre-existing files.
function ensureRegistryComposeFile() {
    if (!REGISTRY_MODE || !REGISTRY_URL) return;
    if (fs.existsSync(COMPOSE_FILE)) return; // already there

    console.log(`[wizard] Generating ${COMPOSE_FILE} for registry mode...`);
    const content = `# Auto-generated by BeeFlow install wizard (registry mode)
services:

  redis:
    image: redis:7-alpine
    container_name: beeflow-redis
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped

  rustfs:
    image: rustfs/rustfs:latest
    container_name: beeflow-rustfs
    environment:
      RUSTFS_ROOT_USER: \${RUSTFS_ACCESS_KEY}
      RUSTFS_ROOT_PASSWORD: \${RUSTFS_SECRET_KEY}
    volumes:
      - rustfs-data:/data
      - rustfs-logs:/logs
    restart: unless-stopped

  server:
    image: ${REGISTRY_URL}/beeflow/server:latest
    container_name: beeflow-server
    ports:
      - "\${SERVER_PORT}:3002"
    environment:
      NODE_ENV: production
      PORT: 3002
      SERVER_PROTOCOL: \${SERVER_PROTOCOL}
      SERVER_PUBLIC_HOST: \${SERVER_PUBLIC_HOST}
      CLIENT_PROTOCOL: \${CLIENT_PROTOCOL}
      CLIENT_PUBLIC_HOST: \${CLIENT_PUBLIC_HOST}
      CORS_ORIGIN: \${CORS_ORIGIN}
      COOKIE_NAME: beeflow.sid
      COOKIE_SECURE: \${COOKIE_SECURE}
      COOKIE_SAMESITE: \${COOKIE_SAMESITE}
      ENABLE_TASKS: \${ENABLE_TASKS}
      ENABLE_MONITORING: \${ENABLE_MONITORING}
      CORE_DATABASE_URL: postgresql://\${DB_USER}:\${DB_PASSWORD}@postgres:5432/\${DB_NAME}
      DATABASE_URL: postgresql://\${DB_USER}:\${DB_PASSWORD}@postgres:5432/\${DB_NAME}
      MONITORING_DATABASE_URL: postgresql://\${DB_USER}:\${DB_PASSWORD}@postgres:5432/\${DB_NAME}
      SESSION_SECRET: \${SESSION_SECRET}
      MASTER_ENCRYPTION_KEY: \${MASTER_ENCRYPTION_KEY}
      REDIS_URL: redis://redis:6379/0
      RUSTFS_ENDPOINT: http://rustfs:9000
      RUSTFS_ACCESS_KEY: \${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: \${RUSTFS_SECRET_KEY}
      SERVICES_API_KEY: \${SERVICES_API_KEY}
      INIT_ADMIN_PASSWORD: \${INIT_ADMIN_PASSWORD:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - beeflow-data:/app/data
    depends_on:
      - redis
      - rustfs
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  agent-hub:
    image: ${REGISTRY_URL}/beeflow/agent-hub:latest
    container_name: beeflow-agent-hub
    ports:
      - "\${CLIENT_PORT}:80"
    environment:
      SERVER_HOST: server
      SERVER_PORT: 3002
    depends_on:
      - server
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: beeflow-postgres
    environment:
      POSTGRES_USER: \${DB_USER}
      POSTGRES_PASSWORD: \${DB_PASSWORD}
      POSTGRES_DB: \${DB_NAME}
    volumes:
      - beeflow-pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${DB_USER} -d \${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - core

  pii:
    image: ${REGISTRY_URL}/beeflow/pii:latest
    container_name: beeflow-pii
    ports:
      - "8200:8200"
    volumes:
      - pii-model-cache:/cache/huggingface
    restart: unless-stopped
    profiles:
      - pii

  search-api:
    image: ${REGISTRY_URL}/beeflow/search-api:latest
    container_name: beeflow-search-api
    ports:
      - "8100:8000"
    environment:
      SEARCH_DATABASE_URL: postgresql://\${SEARCH_DB_USER}:\${SEARCH_DB_PASSWORD}@postgres:5432/\${SEARCH_DB_NAME}
      SEARCH_REDIS_URL: redis://redis:6379/1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    profiles:
      - search

volumes:
  beeflow-data:
  beeflow-pgdata:
  rustfs-data:
  rustfs-logs:
  pii-model-cache:
`;
    fs.mkdirSync(path.dirname(COMPOSE_FILE), { recursive: true });
    fs.writeFileSync(COMPOSE_FILE, content, 'utf-8');
    console.log(`[wizard] Generated ${COMPOSE_FILE}`);
}


// ── Helpers ─────────────────────────────────────────────────────

function generateSecret(length = 32) {
    return crypto.randomBytes(length).toString('hex');
}

function run(cmd, opts = {}) {
    try {
        return { ok: true, output: execSync(cmd, { encoding: 'utf-8', timeout: 30000, ...opts }).trim() };
    } catch (e) {
        return { ok: false, output: e.stderr || e.message };
    }
}

// ── In-memory env store ──────────────────────────────────────────
// Holds the full config env built during /api/install so that
// /api/status can reuse it when calling docker compose ps
// (which needs vars like DB_PASSWORD for the mandatory checks).
let currentEnv = null;

// Restore env from previous install (survives wizard container restarts)
const ENV_CACHE_PATH = path.join(PROJECT_ROOT, '.install-env.json');
try {
    if (fs.existsSync(ENV_CACHE_PATH)) {
        const saved = JSON.parse(fs.readFileSync(ENV_CACHE_PATH, 'utf-8'));
        currentEnv = { ...process.env, ...saved };
        console.log('[boot] Restored env from previous install (%d vars)', Object.keys(saved).length);
    }
} catch (e) {
    console.warn('[boot] Could not restore saved env:', e.message);
}

// ── API Routes ──────────────────────────────────────────────────

/**
 * GET /api/detect-gpu
 * Check if NVIDIA GPU runtime is available in Docker
 */
app.get('/api/detect-gpu', (req, res) => {
    const dockerInfo = run('docker info --format "{{json .Runtimes}}" 2>/dev/null');
    const hasNvidiaRuntime = dockerInfo.ok && dockerInfo.output.includes('nvidia');

    let gpuName = '';
    let gpuMemory = '';
    if (hasNvidiaRuntime) {
        const smi = run('docker run --rm --gpus all nvidia/cuda:12.0.0-base-ubuntu22.04 nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null');
        if (smi.ok && smi.output) {
            const parts = smi.output.split(',').map(s => s.trim());
            gpuName = parts[0] || '';
            gpuMemory = parts[1] || '';
        }
    }

    res.json({
        available: hasNvidiaRuntime,
        gpuName,
        gpuMemory,
        message: hasNvidiaRuntime
            ? `GPU detected: ${gpuName} (${gpuMemory})`
            : 'No NVIDIA GPU runtime found in Docker. GPU services will be unavailable.',
    });
});

/**
 * GET /api/docker-check
 * Verify Docker socket access and compose availability
 */
app.get('/api/docker-check', (req, res) => {
    const docker = run('docker version --format "{{.Server.Version}}"');
    const compose = run('docker compose version --short 2>/dev/null')
                 || run('docker-compose version --short 2>/dev/null');

    res.json({
        dockerOk: docker.ok,
        dockerVersion: docker.ok ? docker.output : null,
        composeOk: compose.ok,
        composeVersion: compose.ok ? compose.output : null,
    });
});

/**
 * POST /api/install
 * Main installation endpoint.
 *
 * Builds all configuration as a JS environment object and passes it
 * directly to docker compose via the child process env -- no .env
 * file is written to disk.
 */
app.post('/api/install', (req, res) => {
    const parsed = InstallBody.safeParse(req.body || {});
    if (!parsed.success) {
        const issue = parsed.error.issues[0];
        return res.status(400).json({ success: false, error: `${issue.path.join('.')}: ${issue.message}` });
    }

    try {
        // ── 1–8. Secrets, compose env and profiles (lib/installPlan.js) ──
        const { secrets, configEnv, profiles } = buildInstallConfig(parsed.data, generateSecret);

        // ── 9. Build compose command (no --env-file) ─────────
        const profileFlags = profiles.map(p => `--profile ${p}`).join(' ');
        const composeCmd = `docker compose -f ${COMPOSE_FILE} ${profileFlags}`;

        // ── 10. Store env for status checks + save metadata ──
        currentEnv = { ...process.env, ...configEnv };

        // Persist configEnv so it survives wizard container restarts
        try {
            fs.writeFileSync(ENV_CACHE_PATH, JSON.stringify(configEnv), 'utf-8');
        } catch (e) {
            console.warn('[install] Could not persist env cache:', e.message);
        }

        const configPath = path.join(PROJECT_ROOT, '.install-config.json');
        fs.writeFileSync(configPath, JSON.stringify({
            profiles,
            composeCmd,
            timestamp: Date.now(),
        }), 'utf-8');

        // ── 11. System resource limits (cap at 80%) ──────────
        const os = require('os');
        const totalCpus = os.cpus().length;
        const buildCpus = Math.max(1, Math.floor(totalCpus * 0.80));
        const totalMemMB = Math.floor(os.totalmem() / 1024 / 1024);
        const buildMemMB = Math.floor(totalMemMB * 0.80);

        const buildEnv = {
            ...currentEnv,
            COMPOSE_DOCKER_CLI_BUILD: '1',
            DOCKER_BUILDKIT: '1',
            BUILDKIT_CPU_LIMIT: `${buildCpus}`,
            BUILDKIT_MEMORY_LIMIT: `${buildMemMB}m`,
        };

        // ── 12. Pull / build / up ─────────────────────────────
        const logFile = path.join(PROJECT_ROOT, '.install-log.txt');
        const logHeader =
            `[${new Date().toISOString()}] Starting deployment...\n` +
            `Mode: ${REGISTRY_MODE ? 'registry (pulling from Harbor)' : 'local build'}\n` +
            `Profiles: ${profiles.join(', ')}\n` +
            `Compose file: ${COMPOSE_FILE}\n` +
            `Resource limits: ${buildCpus}/${totalCpus} CPUs, ~80% of ${Math.floor(totalMemMB / 1024)}GB RAM\n\n`;
        fs.writeFileSync(logFile, logHeader, 'utf-8');
        console.log('[install] ' + logHeader.replace(/\n/g, ' | '));

        // In registry mode: docker login first, then pull (no build)
        const loginCmd = REGISTRY_MODE && REGISTRY_URL && REGISTRY_USER && REGISTRY_TOKEN
            ? `echo '${REGISTRY_TOKEN}' | docker login ${REGISTRY_URL} -u '${REGISTRY_USER}' --password-stdin && `
            : '';
        const upCmd = REGISTRY_MODE
            ? `${composeCmd} pull && ${composeCmd} up -d`
            : `${composeCmd} up -d --build`;
        const fullShCmd = `${loginCmd}${upCmd} 2>&1 | tee -a ${logFile}; echo "\n[INSTALL_COMPLETE]" >> ${logFile}`;

        console.log('[install] Registry mode:', REGISTRY_MODE);
        console.log('[install] Registry URL:', REGISTRY_URL || '(none)');
        console.log('[install] Compose file:', COMPOSE_FILE);
        console.log('[install] Profiles:', profiles.join(', '));
        console.log('[install] Running:', REGISTRY_MODE ? `pull + up` : 'build + up');
        console.log('[install] Command:', upCmd);

        const child = spawn('sh', ['-c', fullShCmd], {
            cwd: PROJECT_ROOT,
            detached: true,
            stdio: ['ignore', process.stdout, process.stderr],
            env: buildEnv,
        });
        child.unref();
        console.log('[install] Deploy process spawned (pid:', child.pid, ')');

        res.json({
            success: true,
            profiles,
            message: 'Deployment started! Check /api/status for progress.',
            secrets: {
                dbPassword:          secrets.DB_PASSWORD,
                sessionSecret:       secrets.SESSION_SECRET,
                masterEncryptionKey: secrets.MASTER_ENCRYPTION_KEY,
                servicesApiKey:      secrets.SERVICES_API_KEY,
            },
        });
    } catch (e) {
        // The operator running the wizard is its only caller, and a failed
        // write under /project is the diagnostic they need; the UI shows it.
        // eslint-disable-next-line no-restricted-syntax
        res.status(500).json({ success: false, error: e.message });
    }
});

/**
 * GET /api/status
 * Check deployment progress and container health.
 * Reuses the stored currentEnv so docker compose ps can resolve
 * mandatory ${VAR:?err} checks without a .env file.
 */
app.get('/api/status', (req, res) => {
    const logFile    = path.join(PROJECT_ROOT, '.install-log.txt');

    let logs = '';
    let complete = false;
    try {
        logs = fs.readFileSync(logFile, 'utf-8');
        complete = logs.includes('[INSTALL_COMPLETE]');
    } catch { /* no log yet */ }

    // Use stored env so mandatory compose vars are satisfied
    const psEnv = currentEnv || process.env;
    const ps = run(`docker compose -f ${COMPOSE_FILE} ps --format json 2>/dev/null`, { env: psEnv });
    let containers = [];
    if (ps.ok && ps.output) {
        try {
            containers = ps.output.split('\n')
                .filter(line => line.trim().startsWith('{'))
                .map(line => {
                    const c = JSON.parse(line);
                    return {
                        name:    c.Name    || c.Service,
                        service: c.Service,
                        state:   c.State,
                        status:  c.Status,
                        health:  c.Health || '',
                    };
                });
        } catch { /* parse error, ignore */ }
    }

    res.json({
        deploying: !complete,
        complete,
        logs: logs.slice(-5000), // last 5 KB
        containers,
    });
});

/**
 * GET /api/logs
 * Stream the last N lines of the install log
 */
app.get('/api/logs', (req, res) => {
    const logFile = path.join(PROJECT_ROOT, '.install-log.txt');
    try {
        const logs = fs.readFileSync(logFile, 'utf-8');
        const lines = logs.split('\n');
        const last = parseInt(req.query.lines || '100', 10);
        res.type('text/plain').send(lines.slice(-last).join('\n'));
    } catch {
        res.type('text/plain').send('No logs yet...');
    }
});

/**
 * GET /api/running-services
 * Returns which BeeFlow services are currently running.
 * Used by the wizard to detect if there's an existing installation to update.
 */
app.get('/api/running-services', (req, res) => {
    const ps = run(
        'docker ps --filter "name=beeflow" --filter "name=search-api" ' +
        '--filter "name=search-postgres" --filter "name=search-redis" ' +
        '--filter "name=guard" --filter "name=whisperx" ' +
        '--format "{{json .}}" 2>/dev/null'
    );

    const containers = [];
    if (ps.ok && ps.output) {
        for (const line of ps.output.split('\n')) {
            const t = line.trim();
            if (!t || !t.startsWith('{')) continue;
            try {
                const c = JSON.parse(t);
                containers.push({
                    name:   c.Names || c.Name,
                    image:  c.Image,
                    state:  c.State,
                    status: c.Status,
                });
            } catch { /* skip */ }
        }
    }

    // Also check if a saved install config exists
    const configPath = path.join(PROJECT_ROOT, '.install-config.json');
    let savedConfig = null;
    try { savedConfig = JSON.parse(fs.readFileSync(configPath, 'utf-8')); } catch { /* none */ }

    res.json({ containers, savedConfig, registryMode: REGISTRY_MODE });
});

 /**
 * GET /api/check-updates
 * Compare local image digests against Harbor registry manifests.
 * Also checks the wizard's own image for self-update detection.
 */
app.get('/api/check-updates', async (req, res) => {
    if (!REGISTRY_MODE || !REGISTRY_URL || !REGISTRY_TOKEN) {
        return res.json({ available: false, reason: 'Registry mode not configured', services: [] });
    }

    const SERVICE_MAP = {
        'beeflow-wizard':          'beeflow/install-wizard',
        'beeflow-server':          'beeflow/server',
        'beeflow-agent-hub':       'beeflow/agent-hub',
        'search-api':              'beeflow/search-api',
        'search-inference-gpu':    'beeflow/search-inference-gpu',
        'beeflow-guard':           'beeflow/guard-service',
        'whisperx-service':        'beeflow/whisperx',
        'beeflow-pii':             'beeflow/pii-service',
    };

    // Get running containers
    const ps = run(
        'docker ps --filter "name=beeflow" --filter "name=search-api" ' +
        '--filter "name=search-inference-gpu" --filter "name=guard" ' +
        '--filter "name=whisperx" --format "{{json .}}" 2>/dev/null'
    );
    const running = [];
    if (ps.ok && ps.output) {
        for (const line of ps.output.split('\n')) {
            const t = line.trim();
            if (!t || !t.startsWith('{')) continue;
            try { running.push(JSON.parse(t)); } catch { /* skip */ }
        }
    }

    // ── Helper: local digest ─────────────────────────────────────
    function getLocalDigest(containerName) {
        // Step 1: Get the image reference the container was started with
        const imgRef = run(`docker inspect "${containerName}" --format "{{.Config.Image}}" 2>/dev/null`);
        if (!imgRef.ok || !imgRef.output) return { digest: null, error: 'container not found' };

        const imageName = imgRef.output.trim();
        // Parse repo + tag from "repo:tag" or "repo" (implies :latest)
        const colonIdx = imageName.lastIndexOf(':');
        const imgRepo = colonIdx > 0 ? imageName.substring(0, colonIdx) : imageName;
        const imgTag  = colonIdx > 0 ? imageName.substring(colonIdx + 1) : 'latest';

        // Step 2: Try `docker images --digests` — most reliable for pulled images
        const digestTable = run(`docker images --no-trunc --digests --format "{{.Repository}}\t{{.Tag}}\t{{.Digest}}" 2>/dev/null`);
        if (digestTable.ok && digestTable.output) {
            for (const line of digestTable.output.split('\n')) {
                const parts = line.trim().split('\t');
                if (parts.length < 3) continue;
                const [repo, tag, digest] = parts;
                if (repo === imgRepo && tag === imgTag && digest && digest !== '<none>') {
                    return { digest, imageName };
                }
            }
        }

        // Step 3: Fallback — inspect image by ID, read RepoDigests
        const imageId = run(`docker inspect "${containerName}" --format "{{.Image}}" 2>/dev/null`);
        if (!imageId.ok || !imageId.output) return { digest: null, error: 'image id not found', imageName };

        const digests = run(`docker image inspect "${imageId.output.trim()}" --format "{{json .RepoDigests}}" 2>/dev/null`);
        if (!digests.ok || !digests.output) return { digest: null, error: 'no RepoDigests', imageName };

        try {
            const arr = JSON.parse(digests.output);
            for (const d of arr) {
                const match = d.match(/@(sha256:[a-f0-9]+)/);
                if (match) return { digest: match[1], imageName };
            }
        } catch { /* skip */ }

        return { digest: null, error: 'empty RepoDigests (locally built image)', imageName };
    }

    // ── Helper: remote manifest digest ──────────────────────────
    // Verified TLS only, and the credentials never go over plain HTTP; see
    // lib/registryDigest.js for the two opt-ins.
    const getRemoteDigest = createRemoteDigest({
        registryUrl: REGISTRY_URL,
        user: REGISTRY_USER,
        token: REGISTRY_TOKEN,
        ...REGISTRY_TRANSPORT,
    });

    // ── Run checks ───────────────────────────────────────────────
    const checks = await Promise.all(
        running
            .filter(c => SERVICE_MAP[c.Names || c.Name])
            .map(async (c) => {
                const name = c.Names || c.Name;
                const repo = SERVICE_MAP[name];
                const local = getLocalDigest(name);
                const remote = await getRemoteDigest(repo);
                const hasUpdate = !!(remote.digest && local.digest && remote.digest !== local.digest);
                const isUnknown = !local.digest || !remote.digest;
                return {
                    name,
                    repo,
                    localDigest:    local.digest,
                    remoteDigest:   remote.digest,
                    hasUpdate,
                    isUnknown,
                    localError:     local.error  || null,
                    remoteError:    remote.error || null,
                    registryStatus: remote.status,
                };
            })
    );

    const anyUpdate  = checks.some(c => c.hasUpdate);
    const wizardSelf = checks.find(c => c.name === (process.env.CONTAINER_NAME || 'beeflow-wizard'));
    res.json({ available: anyUpdate, wizardHasUpdate: wizardSelf?.hasUpdate || false, services: checks });
});

/**
 * POST /api/self-update
 * Pull a newer wizard image from Harbor and restart this container.
 * Spawns a detached shell (waits 2s so HTTP response can be sent first).
 */
app.post('/api/self-update', (req, res) => {
    if (!REGISTRY_MODE || !REGISTRY_URL || !REGISTRY_TOKEN) {
        return res.status(400).json({ error: 'Registry mode not configured' });
    }

    const myName  = process.env.CONTAINER_NAME || 'beeflow-wizard';
    const myPort  = process.env.WIZARD_PORT    || '9090';
    const composeFileName = path.basename(COMPOSE_FILE);
    const wizardImage = `${REGISTRY_URL}/beeflow/install-wizard:latest`;

    const runArgs = [
        `--name ${myName}`,
        `-p ${myPort}:9090`,
        `-v /var/run/docker.sock:/var/run/docker.sock`,
        `-v ${PROJECT_ROOT}:/project`,
        `-e REGISTRY_MODE=1`,
        `-e REGISTRY_URL='${REGISTRY_URL}'`,
        `-e REGISTRY_USER='${REGISTRY_USER}'`,
        `-e REGISTRY_TOKEN='${REGISTRY_TOKEN}'`,
        `-e COMPOSE_FILE='${composeFileName}'`,
        `-e CONTAINER_NAME='${myName}'`,
        `-e WIZARD_PORT='${myPort}'`,
        // Keep the operator's transport opt-ins across the restart.
        ...(REGISTRY_TRANSPORT.insecureTls ? ['-e REGISTRY_INSECURE_TLS=1'] : []),
        ...(REGISTRY_TRANSPORT.allowHttp ? ['-e REGISTRY_ALLOW_HTTP=1'] : []),
        `--restart unless-stopped`,
    ].join(' ');

    const script = [
        `sleep 2`,
        `echo '${REGISTRY_TOKEN}' | docker login ${REGISTRY_URL} -u '${REGISTRY_USER}' --password-stdin`,
        `docker pull ${wizardImage}`,
        `docker rm -f ${myName}`,
        `docker run -d ${runArgs} ${wizardImage}`,
    ].join(' && ');

    const child = spawn('sh', ['-c', script], { detached: true, stdio: 'ignore' });
    child.unref();

    res.json({ success: true, message: 'Self-update in progress. Reconnect in ~5 seconds.' });
});

/**
 * POST /api/update
 * Pull latest images (in registry mode) and restart selected services.
 * Body: { services: ['beeflow-server', 'beeflow-agent-hub', ...] }
 *       If services is empty/omitted, updates ALL running beeflow containers.
 */
app.post('/api/update', (req, res) => {
    // The names end up in an `sh -c` command line: refuse anything that is not
    // a container name before building it.
    const parsed = UpdateBody.safeParse(req.body || {});
    if (!parsed.success) {
        return res.status(400).json({ success: false, error: 'services must be container names' });
    }
    const services = parsed.data.services || [];

    // Services that have a build context (Dockerfile) and should be rebuilt
    // from source in local mode. Other services use pre-built images.
    const BUILDABLE_SERVICES = new Set(['server', 'agent-hub', 'guard-service', 'search-api']);

    const logFile = path.join(PROJECT_ROOT, '.install-log.txt');
    fs.writeFileSync(logFile,
        `[${new Date().toISOString()}] Starting update...\n` +
        `Mode: ${REGISTRY_MODE ? 'registry' : 'local build'}\n` +
        `Services: ${services.length ? services.join(', ') : 'all running'}\n\n`,
        'utf-8'
    );

    // Use saved compose command from last install, or fall back to compose file + all profiles
    const configPath = path.join(PROJECT_ROOT, '.install-config.json');
    let composeCmd = `docker compose -f ${COMPOSE_FILE} --profile core --profile search --profile guard --profile whisperx --profile pii`;
    try {
        const saved = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
        if (saved.composeCmd) composeCmd = saved.composeCmd;
    } catch { /* use default */ }

    const loginCmd = REGISTRY_MODE && REGISTRY_URL && REGISTRY_USER && REGISTRY_TOKEN
        ? `echo '${REGISTRY_TOKEN}' | docker login ${REGISTRY_URL} -u '${REGISTRY_USER}' --password-stdin && `
        : '';

    // Translate container names → compose service names
    const serviceNames = resolveUpdateServices(services);
    const svcArgs = serviceNames.join(' ');

    let fullCmd;
    if (REGISTRY_MODE) {
        // Registry mode: pull new images, then recreate containers
        const pullCmd = `${composeCmd} pull ${svcArgs}`;
        const upCmd = `${composeCmd} up -d --no-build ${svcArgs}`;
        fullCmd = `${loginCmd}${pullCmd} 2>&1 | tee -a ${logFile} && ${upCmd} 2>&1 | tee -a ${logFile}; echo "\n[INSTALL_COMPLETE]" >> ${logFile}`;
    } else {
        // Local mode: rebuild from source, then recreate containers
        const toBuild = serviceNames.filter(s => BUILDABLE_SERVICES.has(s));
        const buildCmd = toBuild.length
            ? `${composeCmd} build --parallel ${toBuild.join(' ')}`
            : 'echo "No buildable services selected"';
        const upCmd = `${composeCmd} up -d --force-recreate ${svcArgs}`;
        fullCmd = `${buildCmd} 2>&1 | tee -a ${logFile} && ${upCmd} 2>&1 | tee -a ${logFile}; echo "\n[INSTALL_COMPLETE]" >> ${logFile}`;
    }

    console.log('[update] Registry mode:', REGISTRY_MODE);
    console.log('[update] Services:', serviceNames.length ? serviceNames.join(', ') : 'all');
    console.log('[update] Command:', fullCmd.substring(0, 200));

    const buildEnv = {
        ...process.env,
        ...(currentEnv || {}),
        COMPOSE_DOCKER_CLI_BUILD: '1',
        DOCKER_BUILDKIT: '1',
    };

    const child = spawn('sh', ['-c', fullCmd], {
        cwd: PROJECT_ROOT,
        detached: true,
        stdio: ['ignore', process.stdout, process.stderr],
        env: buildEnv,
    });
    child.unref();
    console.log('[update] Update process spawned (pid:', child.pid, ')');

    res.json({ success: true, message: 'Update started. Check /api/status for progress.' });
});


/**
 * POST /api/shutdown
 * Gracefully stop the wizard container after install
 */
app.post('/api/shutdown', (req, res) => {
    res.json({ message: 'Wizard shutting down...' });
    setTimeout(() => process.exit(0), 1000);
});

// ── Fallback: serve index.html for SPA-like navigation ──────
app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// ── Start ───────────────────────────────────────────────────
const PORT = process.env.WIZARD_PORT || 9090;

// Generate compose file if needed (registry mode + empty /project volume)
ensureRegistryComposeFile();

app.listen(PORT, '0.0.0.0', () => {
    console.log(`\n🐝 BeeFlow Install Wizard running at http://localhost:${PORT}`);
    console.log(`   Registry mode : ${REGISTRY_MODE ? 'ON (' + REGISTRY_URL + ')' : 'OFF (local build)'}`);
    console.log(`   Compose file  : ${COMPOSE_FILE}`);
    console.log(`   Project root  : ${PROJECT_ROOT}\n`);
    if (REGISTRY_TRANSPORT.insecureTls) {
        console.warn('   WARNING: REGISTRY_INSECURE_TLS=1 - the update check accepts ANY registry certificate;');
        console.warn('            the registry credentials can be read by anyone able to intercept that connection.');
    }
    if (REGISTRY_TRANSPORT.allowHttp) {
        console.warn('   WARNING: REGISTRY_ALLOW_HTTP=1 - the update check retries over plain HTTP (without credentials).');
    }
});
