/**
 * Knowledge Bases — single-KB detail and settings.
 *
 * GET    /:id         — the KB with its documents and derived aggregates
 * PATCH  /:id         — metadata (name, description, category, icon, contexts)
 * PATCH  /:id/publish — publish state + sharing scope
 * DELETE /:id         — delete the KB and cascade its chunks
 *
 * ── WHAT A CALLER MAY SEND ──────────────────────────────────────────
 * Every body and query is `.strict()`. A key this router does not read is a
 * client bug, and three shapes used to change something under a 200:
 *
 *   - `PATCH /:id/publish {"isPublished":"false"}` PUBLISHED the base: the
 *     string is truthy, so `!!isPublished` said yes — to the whole
 *     organisation when the base had no group restriction;
 *   - a publish body without `isPublished` (`{"sharedGroups":["g1"]}`, or a
 *     misspelled `published`) UNPUBLISHED it, since `!!undefined` is false;
 *   - `sharedGroups: [""]` lost its one entry to `filter(Boolean)` and arrived
 *     as `[]`, which on a knowledge base means the WHOLE organisation.
 *
 * ── THE `:id` IS NOT CHECKED HERE ───────────────────────────────────
 * Every knowledge-base id is a UUID (`knowledge_bases.id UUID`, generated by
 * the database, never supplied by a caller), so a path id that is not one
 * names no base. That answer — the 404 every route here already gives when
 * `getKB` finds nothing — belongs in the store, where it covers all fifteen
 * KB routers at once. A schema in this file would answer the same id with a
 * 400 on three of them and a 404 on the other twelve.
 */

const express = require('express');
const log = require('../../telemetry/log');
const router = express.Router();
const kbStore = require('../../stores/knowledgeBases');
const { requireAuth, requirePermission, validateSharedGroupsForOrg, assertUserCanUseOrg } = require('../../auth');
const {
    getUserId,
    canAccessKB,
    canManageKB,
    blockIfSystemKB,
    sanitizeUsageContexts,
    VALID_USAGE_CONTEXTS,
} = require('./shared');
const { validate } = require('../../core/http/validate');
const { z } = require('zod');

// ── What a caller may send ──────────────────────────────────────────

/** A string whose every refusal — including "you left it out" — is a sentence. */
const worded = (message) => z.string({ required_error: message, invalid_type_error: message });

/** Express 5 leaves `req.body` undefined without a body; read that as `{}`. */
const orEmpty = (schema) => z.preprocess((v) => (v === undefined || v === null ? {} : v), schema);

/** GET /:id takes no options: the base, its documents, its counts. */
const NoQuery = orEmpty(z.object({}).strict());
const NoBody = orEmpty(z.object({}, { invalid_type_error: 'This request takes no body.' }).strict());

const NAME_TEXT = 'A knowledge base needs a name.';
const CATEGORY_TEXT = 'categoryId is the id of a category, or null for none.';
const ORG_TEXT = 'organizationId is the id of an organisation.';
const CONTEXTS = [...VALID_USAGE_CONTEXTS];
const CONTEXT_TEXT = `A usage context is one of: ${CONTEXTS.join(', ')}.`;

const UpdateKbBody = orEmpty(z.object({
    name: worded(NAME_TEXT).trim().min(1, NAME_TEXT).max(200, 'A name is at most 200 characters.').optional(),
    description: worded('A description must be text.').optional(),
    // null clears the category (the store's CASE). An empty string used to be
    // WRITTEN as the category id — one no category has.
    categoryId: worded(CATEGORY_TEXT).trim().min(1, CATEGORY_TEXT).nullable().optional(),
    icon: worded('An icon must be text.').trim().max(64, 'An icon is at most 64 characters.').optional(),
    // A context is refused by name rather than filtered out: `['agnet']` used
    // to come back 200 with nothing changed. The empty list likewise: the
    // store never wrote one (sanitizeUsageContexts reads `[]` as "leave
    // as-is"), so accepting it promised a change that did not happen.
    usageContexts: z.array(
        z.enum(CONTEXTS, { errorMap: () => ({ message: CONTEXT_TEXT }) }),
        { invalid_type_error: 'usageContexts is a list of places this base may be used.' },
    ).min(1, 'A knowledge base has to be usable somewhere. Pick at least one place.').optional(),
    // Whether the caller may use this organisation is assertUserCanUseOrg's
    // answer; null means "leave it", exactly as before.
    organizationId: worded(ORG_TEXT).trim().min(1, ORG_TEXT).nullable().optional(),
}).strict());

const PUBLISHED_TEXT = 'Say whether the knowledge base is published: isPublished is true or false.';
const GROUP_TEXT = 'Each shared group is the id of a group.';
const PublishBody = orEmpty(z.object({
    // Required: a publish body without it used to UNPUBLISH the base.
    isPublished: z.boolean({ required_error: PUBLISHED_TEXT, invalid_type_error: PUBLISHED_TEXT }),
    // `[]` is the documented "whole organisation"; a blank entry is refused
    // rather than dropped, because dropping the only one is `[]` as well.
    // Absent or null: the groups stay as they are.
    sharedGroups: z.array(worded(GROUP_TEXT).trim().min(1, GROUP_TEXT),
        { invalid_type_error: 'sharedGroups is a list of group ids.' }).nullish(),
}).strict());

const CONFIRM_TEXT = 'confirm is 1 (or true) once the list of what breaks has been seen.';
const DeleteQuery = orEmpty(z.object({
    confirm: z.enum(['1', 'true', '0', 'false'], { errorMap: () => ({ message: CONFIRM_TEXT }) }).optional(),
}).strict());

/**
 * The Solution-stage lock of a base, through the store that enforces it
 * (stores/knowledgeBases.js `managedPayload`, `assertKbWrite`).
 *
 * The route tests that predate stages hand this router a store double
 * without these two functions (detail.k5 / detail.validation); such a double
 * holds no managed base, so it reports none and refuses nothing. The real
 * store always has both.
 */
const managedOf = (kbId) => (typeof kbStore.managedPayload === 'function' ? kbStore.managedPayload(kbId) : null);
const assertKbDeletable = (kbId) => (typeof kbStore.assertKbWrite === 'function' ? kbStore.assertKbWrite(kbId, ['delete']) : null);

/**
 * Get a single KB with documents
 */
router.get('/:id', requireAuth, validate({ query: NoQuery }), async (req, res) => {
    const kb = await kbStore.getKB(req.params.id);
    if (!kb) return res.status(404).json({ error: 'KB not found' });
    if (!(await canAccessKB(req, kb))) return res.status(403).json({ error: 'Access denied' });

    // Documents come back PROJECTED (stores/knowledgeBases DOCUMENT_COLUMNS):
    // the list never carries `original_content`. Nothing that renders a
    // list of titles needs the bodies, and shipping them made this endpoint
    // grow with the size of the corpus.
    const documents = await kbStore.listDocuments(kb.id);
    // The single-KB query (getKB) doesn't compute the chunk/document
    // aggregates that the list endpoint does, so the detail header showed
    // "0 chunks" even for indexed docs (BFSF-213). They are counted in SQL
    // rather than summed over `documents`, which is one capped page —
    // and they count ACTIVE rows only, so a failed or duplicate row never
    // inflates the header.
    const counts = await kbStore.countDocumentsByStatus(kb.id);
    let sourceCount = 0;
    try {
        const perKb = await require('../../stores/kbSources').countsByKb([kb.id]);
        sourceCount = Number((perKb[kb.id] || {}).sourceCount || 0);
    } catch (e) {
        log.warn('[KB] Source count unavailable for KB detail:', e.message);
    }
    res.json({
        ...kb,
        // Legacy names mobile and the pickers read — same meaning, still numbers.
        total_chunks: counts.totalChunks,
        document_count: counts.documentCount,
        document_count_all: counts.documentCountAll,
        documentCount: counts.documentCount,
        documentCountAll: counts.documentCountAll,
        totalChunks: counts.totalChunks,
        sourceCount,
        lastContentAt: kb.last_content_at || null,
        managed: await managedOf(kb.id),
        documents,
    });
});

/**
 * Update KB metadata
 */
router.patch('/:id', requireAuth, requirePermission('manage_knowledge'), validate({ body: UpdateKbBody }), async (req, res) => {
    const kb = await kbStore.getKB(req.params.id);
    if (!kb) return res.status(404).json({ error: 'KB not found' });
    if (!(await canManageKB(req, kb))) return res.status(403).json({ error: 'Access denied' });
    if (blockIfSystemKB(kb, res)) return;

    const { name, description, categoryId, icon, usageContexts, organizationId } = req.body;
    const cleanedContexts = sanitizeUsageContexts(usageContexts);

    /**
     * Moving a personal knowledge base INTO an organisation.
     *
     * There was no path for this. A base created without an organisation
     * could never be shared: `PATCH /:id/publish` refuses it ("must belong
     * to an organization before publishing"), and nothing else wrote the
     * column — so a base somebody had built up over months stayed
     * personal, and the only way to share it was to build it again.
     *
     * Two things make this safe to allow, and both are load-bearing:
     *
     *   • Only the OWNER may do it. `canManageKB` also admits an org admin
     *     with manage_knowledge, which is right for editing a base the org
     *     already owns and wrong for handing them somebody's personal one.
     *   • It does NOT publish. The base arrives in the organisation
     *     unpublished, so the move alone changes who may READ nothing —
     *     the owner still has to say "share with the organisation".
     *
     * What it does change is who may MANAGE it: org admins and
     * manage_knowledge holders gain that, which is what belonging to an
     * organisation means. That is the consequence worth naming out loud,
     * and the UI says it before the button.
     *
     * There is no way back. Un-setting the organisation on a base that
     * colleagues may already have attached to their agents would revoke
     * their access silently, so the field only ever goes from null to an
     * org, never the other way.
     */
    let adoptOrgId;
    if (organizationId !== undefined && organizationId !== null && organizationId !== kb.organization_id) {
        if (kb.organization_id) {
            return res.status(400).json({
                error: 'This knowledge base already belongs to an organisation.',
                code: 'org_already_set',
            });
        }
        if (String(kb.tenant_id) !== String(getUserId(req))) {
            return res.status(403).json({
                error: 'Only the owner can move a personal knowledge base into an organisation.',
                code: 'not_owner',
            });
        }
        try {
            adoptOrgId = await assertUserCanUseOrg(req, organizationId);
        } catch (err) {
            return res.status(err.status || 403).json({ error: err.message });
        }
    }

    const updated = await kbStore.updateKB(kb.id, {
        name, description, categoryId, icon,
        ...(cleanedContexts ? { usageContexts: cleanedContexts } : {}),
        ...(adoptOrgId ? { organizationId: adoptOrgId } : {}),
    });
    kbStore.snapshotKBVersion(kb.id, getUserId(req), adoptOrgId ? 'moved_to_organisation' : 'metadata_update').catch(() => {});
    res.json(updated);
});

/**
 * Toggle publish state + set sharing scope. Mirrors PATCH /api/agents/:id/publish.
 * Owner can always publish/unpublish; non-owners need same-org
 * manage_knowledge (canManageKB, BFSF-214).
 */
router.patch('/:id/publish', requireAuth, validate({ body: PublishBody }), async (req, res) => {
    const userId = getUserId(req);
    const kb = await kbStore.getKB(req.params.id);
    if (!kb) return res.status(404).json({ error: 'KB not found' });
    if (blockIfSystemKB(kb, res)) return;

    if (!(await canManageKB(req, kb))) {
        return res.status(403).json({ error: 'Permission denied' });
    }

    const { isPublished, sharedGroups } = req.body;

    // A KB must be attached to an organization to be published.
    if (isPublished && !kb.organization_id) {
        return res.status(400).json({ error: 'KB must belong to an organization before publishing' });
    }

    // Validate sharedGroups belong to the KB's org. `undefined` means
    // "leave as-is"; the validator returns undefined and the store
    // preserves the existing column value.
    let cleanedGroups;
    try {
        cleanedGroups = await validateSharedGroupsForOrg(kb.organization_id, sharedGroups);
    } catch (err) {
        return res.status(err.status || 500).json({ error: err.message });
    }
    const updated = await kbStore.setPublished(kb.id, isPublished, cleanedGroups);
    // Snapshot for audit/rollback. Fire-and-forget — versioning failure
    // must not unwind a successful publish.
    kbStore.snapshotKBVersion(kb.id, userId, isPublished ? 'publish' : 'unpublish').catch(() => {});
    res.json({ success: true, kb: updated });
});

/**
 * Delete a KB (cascades documents, chunks via search-service)
 */
router.delete('/:id', requireAuth, requirePermission('manage_knowledge'), validate({ query: DeleteQuery, body: NoBody }), async (req, res) => {
    const kb = await kbStore.getKB(req.params.id);
    if (!kb) return res.status(404).json({ error: 'KB not found' });
    /**
     * canMANAGE, not canACCESS.
     *
     * Reading a knowledge base and destroying it are different rights, and
     * this route asked for the reading one. Anyone in the org who could
     * see a published base — which is everyone it was published to —
     * could delete it, along with every document in it, as long as their
     * role happened to carry `manage_knowledge`.
     */
    if (!(await canManageKB(req, kb))) return res.status(403).json({ error: 'Access denied' });
    if (blockIfSystemKB(kb, res)) return;

    /**
     * ── WHAT BREAKS, BEFORE IT BREAKS ───────────────────────────
     * Deleting a knowledge base is not a local act: agents stop being able
     * to answer, AI steps start failing on their next run, and nothing
     * about either failure names this base. So the first DELETE answers
     * 409 with the list, and only a second one carrying `?confirm=1`
     * proceeds. The client renders that list in the danger zone, which is
     * where the decision actually gets made.
     *
     * `partial` is treated as "in use". A consumer the scan could not
     * reach is not a consumer that is absent, and this is the one moment
     * where guessing wrong is unrecoverable.
     */
    // A base a Solution stage manages is removed by a deploy, never here.
    // Asked BEFORE the chunk purge below, which cannot be undone: the store's
    // own refusal in deleteKB would come after the embeddings were gone.
    await assertKbDeletable(kb.id);

    const confirmed = req.query.confirm === '1' || req.query.confirm === 'true';
    if (!confirmed) {
        const { usageForKb } = require('../../core/kb/kbUsage');
        const { rows, partial } = await usageForKb(kb.id);
        if (rows.length > 0 || partial.length > 0) {
            return res.status(409).json({
                error: 'This knowledge base is still in use',
                code: 'in_use',
                usage: rows,
                // Named so the dialog can say "and I could not check apps"
                // rather than presenting an incomplete list as complete.
                unchecked: partial,
            });
        }
    }

    // Delete chunks from the search-service (skip when admin chose local-only).
    //
    // There is no KB-wide chunk delete to call: the search-service exposes
    // exactly one removal route, DELETE /kb/documents/{id}
    // (search-service/app/routers/ingest.py), and so does the Node shim
    // that production actually points SEARCH_SERVICE_URL at. The old
    // DELETE /kb/{id}/chunks call here hit nothing on either, silently, so
    // every deleted KB left its embeddings searchable. Walk the documents
    // instead — purgeDocumentChunks speaks the route that exists.
    try {
        const { resolveKbProvider } = require('../../core/kb/resolveProvider');
        const kbProvider = await resolveKbProvider();
        if (kbProvider !== 'local') {
            const { purgeDocumentChunks } = require('../../core/kb/kbIngestionHelpers');
            const PAGE = 200;
            for (let offset = 0; offset < PAGE * 200; offset += PAGE) {
                const docs = await kbStore.listDocuments(kb.id, { limit: PAGE, offset });
                if (!docs || docs.length === 0) break;
                for (const doc of docs) {
                    await purgeDocumentChunks(kb.id, doc.id, kb.tenant_id);
                }
                if (docs.length < PAGE) break;
            }
        }
    } catch (e) {
        log.warn('[KB] Search-service chunk cleanup failed:', e.message);
    }

    // Delete chunks from local vector store
    try {
        const { deleteChunksLocally } = require('../../core/kb/localKBIngest');
        await deleteChunksLocally(kb.tenant_id, kb.id);
    } catch (e) {
        log.warn('[KB] Local chunk cleanup failed:', e.message);
    }

    await kbStore.deleteKB(kb.id);

    /**
     * Scrub the references, so nothing is left pointing at a base that is
     * gone. `deleteKB` scrubs `projects` alone, so an agent kept a dead id
     * in its config for ever — invisible until somebody opened it and
     * wondered why a knowledge base they could not find was attached.
     *
     * After the delete, not before: the row is the thing that had to go,
     * and a scrub that ran first and then failed to delete would have
     * detached every consumer from a base that is still there.
     */
    let scrubbed = null;
    try {
        const { scrubReferences } = require('../../core/kb/kbUsage');
        scrubbed = await scrubReferences(kb.id);
    } catch (e) {
        log.warn('[KB] Reference scrub failed:', e.message);
    }

    /**
     * And the OTHER direction: a datatable source made this knowledge base
     * a consumer in the datatable's dependents index (K8). Those rows are
     * keyed on the knowledge base, not on the source, so nothing has
     * removed them — the table's "Used by" would go on naming a knowledge
     * base that is gone, and its delete guard would go on refusing over it.
     *
     * `purgeUsageFor` is keyed on the kind as well as the id, so this
     * cannot reach another kind's rows even in the impossible case of an
     * id collision.
     */
    try {
        await require('../../stores/datatableStore').purgeUsageFor('kb', kb.id);
    } catch (e) {
        log.warn('[KB] datatable usage purge failed:', e.message);
    }
    res.json({ success: true, scrubbed });
});
module.exports = router;
