/** Styles for the scanner's parts. The camera is always black-backed, whatever the theme. */

import { StyleSheet } from 'react-native';

export const scanStyles = StyleSheet.create({
    root: { flex: 1, backgroundColor: '#000' },
    centre: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    onDark: { color: '#fff' },
    onDarkMuted: { color: 'rgba(255,255,255,0.7)' },
    topBar: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 8,
        paddingBottom: 12,
        backgroundColor: 'rgba(0,0,0,0.45)',
    },
    topBarText: { color: '#fff', flex: 1 },
    filmstrip: { position: 'absolute', left: 0, right: 0, maxHeight: 80 },
    bottomBar: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingTop: 16,
        backgroundColor: 'rgba(0,0,0,0.45)',
    },
    side: { width: 88 },
    sideEnd: { width: 88, alignItems: 'flex-end' },
    shutter: {
        width: 72,
        height: 72,
        borderRadius: 36,
        borderWidth: 4,
        borderColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    shutterInner: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#fff' },
    thumb: { width: 54, height: 72 },
    discardBadge: {
        position: 'absolute',
        top: -4,
        right: -4,
        width: 18,
        height: 18,
        borderRadius: 9,
        backgroundColor: 'rgba(0,0,0,0.8)',
        alignItems: 'center',
        justifyContent: 'center',
    },
});
