// Generated from server/appStudio/builderTools/schemas.js by hand on 2026-09-13 — the tool
// names the App Studio builder ships. appToolCallDisplay.test.js checks every one has a verb;
// when a tool is added server-side, add it here and to VERBS.
export const TOOL_SCHEMAS_NAMES = [
    "app_set_meta",
    "app_set_theme",
    "app_set_nav_groups",
    "app_add_screen",
    "app_update_screen",
    "app_remove_screen",
    "app_add_section",
    "app_update_section",
    "app_add_components",
    "app_update_component",
    "app_move_node",
    "app_remove_node",
    "app_set_action",
    "app_remove_action",
    "app_bind_action",
    "app_set_plan",
    "app_link_datatable",
    "app_upsert_table",
    "app_remove_table",
    "app_set_roles",
    "app_set_variables",
    "app_set_public_access",
    "app_seed_records",
    "app_upsert_dataset",
    "app_get_data_model",
    "app_query_data",
    "app_list_connectors",
    "app_dry_run",
    "app_screenshot",
    "app_get_draft",
    "app_find_nodes",
    "app_list_automations",
    "app_inspect_automation",
    "app_propose_plan",
    "app_mark_phase",
    "app_list_templates",
    "app_apply_template",
    "app_save_as_template",
    "app_finalize"
];
