// @typecheck
/**
 * The bridge between a co-edited Yjs document and everything else that reads
 * or writes the content: the legacy HTML/Markdown columns, the AI, exports,
 * search and version history.
 *
 * The conversions themselves are not written here. They are the editor's own
 * code, bundled for the server (`core/markdown/editorCollab.cjs`, built from
 * agent-hub/src/editor/collab + serialization + diff), so the server reads and
 * writes EXACTLY the Yjs shape the browser editor does:
 *
 *   ydoc.getXmlFragment('content')   the document body
 *   fragmentToAst(fragment)          whitelisted, sanitised AST (read)
 *   astToFragment(ast, fragment)     first write into an empty fragment
 *   syncDocToFragment(fragment, ast) minimal diff-apply (every later write)
 *   astToHtml / astToMarkdown        the mirrors and exports
 *   htmlToAst / markdownToAst        legacy content and server-side edits
 *   diffDocs(a, b)                   block + word diff, for version stats
 *
 * The bundle keeps yjs external, so it shares this process's single Yjs
 * instance (two copies break Yjs' constructor checks).
 *
 * When the bundle is missing, `available()` is false and every conversion
 * throws: co-editing then refuses to open (503) rather than seeding a
 * document it cannot read back.
 */

'use strict';

const path = require('path');
const Y = require('yjs');

const FRAGMENT_NAME = 'content';
// Generated by `cd server && npm run build:editor-collab`; resolved at run
// time because the file may not exist on a checkout that has not built it.
const BUNDLE_PATH = path.join(__dirname, '..', 'markdown', 'editorCollab.cjs');

class CollabConvertError extends Error {
    /** @param {string} message @param {unknown} [cause] */
    constructor(message, cause) {
        super(message);
        this.name = 'CollabConvertError';
        this.code = 'COLLAB_CONVERT_FAILED';
        if (cause) this.cause = cause;
    }
}

/**
 * @typedef {{ type: string, attrs?: Record<string, any>, content?: AstNode[], marks?: any[], text?: string }} AstNode
 * @typedef {{
 *   markdownToAst: (md: string) => AstNode,
 *   htmlToAst: (html: string, domParser?: any) => AstNode,
 *   astToMarkdown: (ast: AstNode) => string,
 *   astToHtml: (ast: AstNode) => string,
 *   astToFragment: (ast: AstNode, fragment: any) => void,
 *   fragmentToAst: (fragment: any, cache?: any) => AstNode,
 *   syncDocToFragment: (fragment: any, doc: AstNode, mapping?: any) => void,
 *   diffDocs?: (a: AstNode, b: AstNode) => { stats?: { wordsAdded: number, wordsRemoved: number, blocksChanged: number } },
 * }} CollabBundle
 */

const REQUIRED = ['markdownToAst', 'htmlToAst', 'astToMarkdown', 'astToHtml', 'astToFragment', 'fragmentToAst', 'syncDocToFragment'];

/** @returns {CollabBundle|null} */
function loadBundle() {
    try {
        const b = require(BUNDLE_PATH);
        return REQUIRED.every((k) => typeof b[k] === 'function') ? b : null;
    } catch (_) {
        return null;
    }
}

let _DOMParser = null;
function domParser() {
    if (_DOMParser) return _DOMParser;
    const { JSDOM } = require('jsdom');
    _DOMParser = new JSDOM('').window.DOMParser;
    return _DOMParser;
}

const HTML_LIKE = /<\/?[a-z][\s\S]*>/i;
const BLOCKISH = /^(paragraph|heading|codeBlock|listItem|taskItem|tableCell|blockquote|horizontalRule|image|mermaid|mathBlock|chart)$/;

/**
 * Plain text of an AST, one line per block. Used for word counts and the
 * compliance scan, never stored in events.
 * @param {AstNode|null|undefined} node
 */
function astText(node) {
    const out = [];
    (function walk(n) {
        if (!n || typeof n !== 'object') return;
        if (n.type === 'text' && typeof n.text === 'string') { out.push(n.text); return; }
        if (n.type === 'hardBreak') { out.push('\n'); return; }
        if (Array.isArray(n.content)) for (const c of n.content) walk(c);
        if (BLOCKISH.test(n.type)) out.push('\n');
    })(node);
    return out.join('').replace(/\n{3,}/g, '\n\n').trim();
}

/** @param {string} text */
const countWords = (text) => (text.match(/\S+/g) || []).length;

const EMPTY_DOC = Object.freeze({ type: 'doc', content: [] });

/**
 * @param {{ bundle?: CollabBundle|null, domParser?: () => any }} [deps]
 */
function makeConverter(deps = {}) {
    /** @type {CollabBundle|null|undefined} */
    let bundle = deps.bundle;
    const parser = deps.domParser || domParser;

    function b() {
        if (bundle === undefined) bundle = loadBundle();
        if (!bundle) throw new CollabConvertError('The co-editing converter is not installed on this server');
        return bundle;
    }

    /** True when the editor bundle is present and complete. */
    function available() {
        try { b(); return true; } catch (_) { return false; }
    }

    /** @param {Y.Doc} ydoc */
    const fragmentOf = (ydoc) => ydoc.getXmlFragment(FRAGMENT_NAME);

    /**
     * An AST from what a caller or a legacy column holds.
     * @param {{ ast?: AstNode|null, html?: string|null, markdown?: string|null }} input
     * @returns {AstNode}
     */
    function toAst(input) {
        if (input.ast && typeof input.ast === 'object') return input.ast;
        try {
            if (typeof input.html === 'string' && input.html.trim()) return b().htmlToAst(input.html, parser());
            if (typeof input.markdown === 'string' && input.markdown.trim()) return b().markdownToAst(input.markdown);
        } catch (err) {
            if (err instanceof CollabConvertError) throw err;
            throw new CollabConvertError('The content could not be converted', err);
        }
        return { ...EMPTY_DOC, content: [] };
    }

    /**
     * The legacy content of a resource as an AST: HTML when the column holds
     * HTML (richer: tables, images), Markdown otherwise.
     * @param {{ html?: string|null, markdown?: string|null }} legacy
     */
    function legacyToAst({ html, markdown }) {
        if (typeof html === 'string' && html.trim()) {
            return HTML_LIKE.test(html) ? toAst({ html }) : toAst({ markdown: html });
        }
        return toAst({ markdown: markdown || '' });
    }

    /** @param {AstNode} ast */
    const isEmpty = (ast) => !ast || !Array.isArray(ast.content) || ast.content.length === 0;

    /**
     * Make the document equal to `ast`, as the smallest change: text typed by
     * someone else meanwhile survives wherever the new content keeps it.
     * @param {Y.Doc} ydoc @param {AstNode} ast @param {unknown} origin
     */
    function replaceWith(ydoc, ast, origin) {
        const bundle = b();
        const fragment = fragmentOf(ydoc);
        ydoc.transact(() => {
            if (fragment.length === 0) bundle.astToFragment(ast, fragment);
            else bundle.syncDocToFragment(fragment, ast);
        }, origin);
    }

    /**
     * Add `ast`'s blocks after the existing content.
     * @param {Y.Doc} ydoc @param {AstNode} ast @param {unknown} origin
     */
    function append(ydoc, ast, origin) {
        const current = readAst(ydoc);
        const next = { ...current, type: 'doc', content: [...(current.content || []), ...(ast.content || [])] };
        replaceWith(ydoc, next, origin);
    }

    /** @param {Y.Doc} ydoc @returns {AstNode} */
    function readAst(ydoc) {
        const fragment = fragmentOf(ydoc);
        if (fragment.length === 0) return { ...EMPTY_DOC, content: [] };
        return b().fragmentToAst(fragment);
    }

    /**
     * Everything a reader of the content needs, from the current state.
     * @param {Y.Doc} ydoc
     */
    function render(ydoc) {
        const bundle = b();
        const ast = readAst(ydoc);
        const text = astText(ast);
        return {
            ast,
            html: isEmpty(ast) ? '' : bundle.astToHtml(ast),
            markdown: isEmpty(ast) ? '' : bundle.astToMarkdown(ast),
            text,
            wordCount: countWords(text),
        };
    }

    /**
     * Bytes of the HTML the state renders to: what an owner that caps its
     * stored body (a page) counts. Only the HTML is rendered.
     * @param {Y.Doc} ydoc
     */
    function htmlBytes(ydoc) {
        const ast = readAst(ydoc);
        return isEmpty(ast) ? 0 : Buffer.byteLength(b().astToHtml(ast), 'utf8');
    }

    /**
     * Words added / removed and blocks changed between two ASTs, or null when
     * the diff is not available. Counts only: never text.
     * @param {AstNode|null} before @param {AstNode} after
     */
    function diffStats(before, after) {
        const bundle = b();
        if (typeof bundle.diffDocs !== 'function') return null;
        try {
            const r = bundle.diffDocs(before || { ...EMPTY_DOC, content: [] }, after);
            const s = r && r.stats;
            if (!s) return null;
            return {
                wordsAdded: Number(s.wordsAdded) || 0,
                wordsRemoved: Number(s.wordsRemoved) || 0,
                blocksChanged: Number(s.blocksChanged) || 0,
            };
        } catch (_) {
            return null;
        }
    }

    /**
     * A standalone document from a Yjs state (for stats against the state at
     * the last checkpoint).
     * @param {Uint8Array|null} state
     */
    function astOfState(state) {
        if (!state || state.length === 0) return { ...EMPTY_DOC, content: [] };
        const doc = new Y.Doc();
        try {
            Y.applyUpdate(doc, state);
            return readAst(doc);
        } finally {
            doc.destroy();
        }
    }

    return { available, toAst, legacyToAst, replaceWith, append, readAst, render, htmlBytes, diffStats, astOfState, isEmpty, fragmentOf };
}

const defaultConverter = makeConverter();

module.exports = {
    FRAGMENT_NAME,
    BUNDLE_PATH,
    CollabConvertError,
    astText,
    countWords,
    loadBundle,
    makeConverter,
    defaultConverter,
};
