/**
 * Golden binding corpus: what the legacy binding kinds resolve to, pinned.
 *
 * The cases were recorded from server/automation/bind.js BEFORE its code moved
 * into this directory (legacy.mjs, resolve.mjs), so they are today's runtime
 * behaviour, not a second, independently invented truth. They cover every
 * dialect a stored automation can hold: canonical paths, `[0]` and `.0`,
 * nested `[*]`, quoted and hyphenated keys, `trigger.x` without `.output`,
 * missing values, null rows, JSON templates, listAsMarkdown,
 * leaveUnresolved, the gallery templates (server/automation/templates.js) and
 * the paths the AI builder's normaliser writes.
 *
 * Some expectations are WRONG on purpose: `steps.s1.output.items.0.subject`
 * is undefined and `{{vars.objs}}` renders as JSON. That is what a stored
 * automation does today, and backward compatibility means it keeps doing so
 * until a milestone changes it deliberately and updates the case here.
 *
 * The same file runs under node --test (server), vitest (agent-hub, the
 * generated copy) and jest (mobile, the vendored copy), so the preview on the
 * web and on the phone equals the run. Add a case HERE, never in one runner.
 * Every case runs against a FRESH makeState(): interpolateTemplate pushes onto
 * `_templateWarnings`, and a shared object would leak between cases.
 *
 * The second half of the file (from "v2: pick and compose") is the v2
 * mapping: WALK_V2, PICKS, EACH, COMPOSE, DEEP_V2 and INPUTS_V2 against
 * makeMappingState(). Those cases are the specification, not a recording;
 * see the note there.
 */

export function makeState() {
    return {
        trigger: {
            output: {
                subject: 'Factuur 42',
                name: 'Jan',
                n: 3,
                zero: 0,
                no: false,
                empty: '',
                nil: null,
                'content-type': 'application/json',
                'Due date': '2026-10-01',
                "it's": 'apostrophe',
                'say "hi"': 'double',
                body: { content: 'hello', 'content-type': 'text/plain' },
                attachments: [
                    { filename: 'a.pdf', attachmentId: 'att1', data: 'QUJD' },
                    { filename: 'b.pdf', attachmentId: 'att2' },
                ],
                list: [{ a: 1 }, { a: 2 }, { b: 3 }],
                tags: ['x', 'y'],
                matrix: [[1, 2], [3]],
                json: '{"a":{"b":1}}',
                formTitle: 'Intake',
                submittedBy: 'Ada',
                submissionId: 'sub-1',
                summary: 'Kwartaaloverleg',
                startsAt: '2026-10-02T09:00:00Z',
                path: '/Shared/plan.docx',
                datetime: '2026-10-01 10:00',
                actor: 'piet',
                message: 'Klaar',
                title: 'Release',
                threadId: 't-9',
                messageId: 'msg-1',
                snippet: 'Hi there',
                transcript: 'A: hallo',
            },
            id: 'trg',
            kind: 'manual',
        },
        steps: {
            s1: {
                output: {
                    items: [
                        { subject: 'Hi', tags: ['a', 'b'], qty: 2 },
                        { subject: 'Yo', tags: ['c'], qty: null },
                        null,
                        { subject: 'Zo', tags: [] },
                    ],
                    total: 2,
                    count: 0,
                    results: [
                        { output: { a: 1, attachments: [{ name: 'x1' }, { name: 'x2' }] } },
                        { output: { a: 2, attachments: [] } },
                        { output: null },
                        { output: { attachments: { name: 'single' } } },
                    ],
                    nested: { deep: { deeper: { deepest: 'bottom' } } },
                    text: 'plain',
                    words: ['een', ' twee ', 3, true, null],
                },
                status: 'success',
            },
            fail: { output: null, status: 'handled_error', error: { message: 'boom', errorClass: 'transient', stepId: 'fail' } },
            $read: { output: { results: [{ content: 'r1' }, { content: 'r2' }], body: 'B' } },
            a_1a2b3c: { output: { messages: [{ id: 'm1' }], results: [] } },
            summarise: { output: 'A short summary' },
            fetch: { output: [1, 2, 3] },
            num: { output: 42 },
            nul: { output: null },
            deck: { output: { filename: 'deck.pptx', sourceHandle: 'h1' } },
            extract: { output: { factuurnummer: 'F-1', datum: '2026-09-30', excl_btw: 100, btw: 21, incl_btw: 121, status: 'open' } },
            judge: { output: { sensitivity: 'high', reason: 'public "share"' } },
            outline: { output: { text: 'Line 1\nLine 2' } },
            distill: { output: { title: 'T', article: 'Body' } },
        },
        loop: {
            e: { output: { btw: 21, datum: '2026-09-30' } },
            item: { path: '/a.txt' },
            row: { 'Due date': 'morgen', 'e-mail': 'a@b.nl', name: 'Row' },
            f: { path: '/f', fileId: 'F1', content: 'c' },
            _index: 2,
        },
        vars: {
            rate: 1.21,
            greeting: 'Hallo',
            list: ['a', 'b'],
            mixed: [1, 'two', true, null],
            objs: [{ a: 1 }],
            emptyList: [],
            ownProto: JSON.parse('{"__proto__":{"x":1},"constructor":"own"}'),
        },
        secrets: { apiKey: 'secret-value-1' },
    };
}

/** walkPath(path, makeState()) */
export const WALK = [
    { path: 'trigger', expected: { output: { subject: 'Factuur 42', name: 'Jan', n: 3, zero: 0, no: false, empty: '', nil: null, 'content-type': 'application/json', 'Due date': '2026-10-01', "it's": 'apostrophe', 'say "hi"': 'double', body: { content: 'hello', 'content-type': 'text/plain' }, attachments: [{ filename: 'a.pdf', attachmentId: 'att1', data: 'QUJD' }, { filename: 'b.pdf', attachmentId: 'att2' }], list: [{ a: 1 }, { a: 2 }, { b: 3 }], tags: ['x', 'y'], matrix: [[1, 2], [3]], json: '{"a":{"b":1}}', formTitle: 'Intake', submittedBy: 'Ada', submissionId: 'sub-1', summary: 'Kwartaaloverleg', startsAt: '2026-10-02T09:00:00Z', path: '/Shared/plan.docx', datetime: '2026-10-01 10:00', actor: 'piet', message: 'Klaar', title: 'Release', threadId: 't-9', messageId: 'msg-1', snippet: 'Hi there', transcript: 'A: hallo' }, id: 'trg', kind: 'manual' } },
    { path: 'trigger.output', expected: { subject: 'Factuur 42', name: 'Jan', n: 3, zero: 0, no: false, empty: '', nil: null, 'content-type': 'application/json', 'Due date': '2026-10-01', "it's": 'apostrophe', 'say "hi"': 'double', body: { content: 'hello', 'content-type': 'text/plain' }, attachments: [{ filename: 'a.pdf', attachmentId: 'att1', data: 'QUJD' }, { filename: 'b.pdf', attachmentId: 'att2' }], list: [{ a: 1 }, { a: 2 }, { b: 3 }], tags: ['x', 'y'], matrix: [[1, 2], [3]], json: '{"a":{"b":1}}', formTitle: 'Intake', submittedBy: 'Ada', submissionId: 'sub-1', summary: 'Kwartaaloverleg', startsAt: '2026-10-02T09:00:00Z', path: '/Shared/plan.docx', datetime: '2026-10-01 10:00', actor: 'piet', message: 'Klaar', title: 'Release', threadId: 't-9', messageId: 'msg-1', snippet: 'Hi there', transcript: 'A: hallo' } },
    { path: 'trigger.output.subject', expected: 'Factuur 42' },
    { path: 'trigger.output.n', expected: 3 },
    { path: 'trigger.output.zero', expected: 0 },
    { path: 'trigger.output.no', expected: false },
    { path: 'trigger.output.empty', expected: '' },
    { path: 'trigger.output.nil', expected: null },
    { path: 'trigger.output.body.content', expected: 'hello' },
    { path: 'trigger.id', expected: 'trg' },
    { path: 'trigger.subject', expected: undefined },
    { path: 'steps.s1.output.total', expected: 2 },
    { path: 'steps.s1.output.count', expected: 0 },
    { path: 'steps.s1.output.nested.deep.deeper.deepest', expected: 'bottom' },
    { path: 'steps.s1.status', expected: 'success' },
    { path: 'steps.fail.error.message', expected: 'boom' },
    { path: 'steps.fail.output', expected: null },
    { path: 'steps.summarise.output', expected: 'A short summary' },
    { path: 'steps.fetch.output', expected: [1, 2, 3] },
    { path: 'steps.num.output', expected: 42 },
    { path: 'steps.nul.output', expected: null },
    { path: 'steps.nul.output.x', expected: undefined },
    { path: 'steps.$read.output.body', expected: 'B' },
    { path: 'steps.$read.output.results', expected: [{ content: 'r1' }, { content: 'r2' }] },
    { path: 'steps.a_1a2b3c.output.messages', expected: [{ id: 'm1' }] },
    { path: 'steps.missing.output.x', expected: undefined },
    { path: 'vars.rate', expected: 1.21 },
    { path: 'vars.list', expected: ['a', 'b'] },
    { path: 'secrets.apiKey', expected: 'secret-value-1' },
    { path: 'loop.e.output.btw', expected: 21 },
    { path: 'loop.item.path', expected: '/a.txt' },
    { path: 'loop.f.fileId', expected: 'F1' },
    { path: 'loop._index', expected: 2 },
    { path: 'loop.r.output.content', expected: undefined },
    { path: 'steps.s1.output.items[0].subject', expected: 'Hi' },
    { path: 'steps.s1.output.items.0.subject', expected: undefined },
    { path: 'steps.s1.output.items[1].qty', expected: null },
    { path: 'steps.s1.output.items[2]', expected: null },
    { path: 'steps.s1.output.items[2].subject', expected: undefined },
    { path: 'steps.s1.output.items[9]', expected: undefined },
    { path: 'trigger.output.attachments[0].data', expected: 'QUJD' },
    { path: 'trigger.output.attachments.0.data', expected: undefined },
    { path: 'trigger.output.attachments.0.attachmentId', expected: undefined },
    { path: 'trigger.output.attachments.0.filename', expected: undefined },
    { path: 'trigger.output.matrix[0][1]', expected: 2 },
    { path: 'trigger.output.matrix[1][0]', expected: 3 },
    { path: 'steps.fetch.output[2]', expected: 3 },
    { path: 'trigger.output.tags[1]', expected: 'y' },
    { path: 'trigger.output.subject[0]', expected: 'F' },
    { path: 'steps.s1.output.items[01].subject', expected: 'Yo' },
    { path: 'steps.s1.output.items[-1]', expected: undefined },
    { path: 'trigger.output.list[*].a', expected: [1, 2] },
    { path: 'trigger.output.list[*]', expected: [{ a: 1 }, { a: 2 }, { b: 3 }] },
    { path: 'trigger.output.attachments[*].filename', expected: ['a.pdf', 'b.pdf'] },
    { path: 'steps.s1.output.items[*].subject', expected: ['Hi', 'Yo', 'Zo'] },
    { path: 'steps.s1.output.items[*].qty', expected: [2, null] },
    { path: 'steps.s1.output.items[*].tags', expected: ['a', 'b', 'c'] },
    { path: 'steps.s1.output.items[*].tags[*]', expected: ['a', 'b', 'c'] },
    { path: 'steps.s1.output.items[*].tags[0]', expected: ['a', 'c'] },
    { path: 'steps.s1.output.results[*].output.a', expected: [1, 2] },
    { path: 'steps.s1.output.results[*].output.attachments', expected: [{ name: 'x1' }, { name: 'x2' }, { name: 'single' }] },
    { path: 'steps.s1.output.results[*].output.attachments[*].name', expected: ['x1', 'x2'] },
    { path: 'steps.s1.output.results[*].output', expected: [{ a: 1, attachments: [{ name: 'x1' }, { name: 'x2' }] }, { a: 2, attachments: [] }, null, { attachments: { name: 'single' } }] },
    { path: 'trigger.output.matrix[*]', expected: [1, 2, 3] },
    { path: 'trigger.output.matrix[*][0]', expected: [1, 3] },
    { path: 'trigger.output.subject[*]', expected: undefined },
    { path: 'steps.s1.output.total[*]', expected: undefined },
    { path: 'steps.$read.output.results[*].content', expected: ['r1', 'r2'] },
    { path: 'vars.emptyList[*].x', expected: [] },
    { path: 'trigger.output["content-type"]', expected: 'application/json' },
    { path: "trigger.output['content-type']", expected: 'application/json' },
    { path: 'trigger.output.content-type', expected: undefined },
    { path: 'trigger.output.body.content-type', expected: undefined },
    { path: 'trigger.output.body["content-type"]', expected: 'text/plain' },
    { path: 'trigger.output["Due date"]', expected: '2026-10-01' },
    { path: "trigger.output[\"it's\"]", expected: 'apostrophe' },
    { path: "trigger.output['say \"hi\"']", expected: 'double' },
    { path: 'trigger.output["subject"]', expected: 'Factuur 42' },
    { path: 'trigger["output"].n', expected: 3 },
    { path: 'loop.row["Due date"]', expected: 'morgen' },
    { path: 'loop.row.Due', expected: undefined },
    { path: 'loop.row["e-mail"]', expected: 'a@b.nl' },
    { path: 'loop.row.e', expected: undefined },
    { path: 'trigger.output[""]', expected: undefined },
    { path: 'constructor', expected: undefined },
    { path: '__proto__', expected: undefined },
    { path: 'steps.s1.output.total.constructor', expected: undefined },
    { path: 'trigger.output.subject.length', expected: 10 },
    { path: 'trigger.output.tags.length', expected: 2 },
    { path: 'trigger.output.subject.toUpperCase', expected: undefined },
    { path: 'trigger.output.constructor.name', expected: undefined },
    { path: 'trigger.output["constructor"]', expected: undefined },
    { path: 'trigger.output.__proto__', expected: undefined },
    { path: 'vars.ownProto.constructor', expected: 'own' },
    { path: 'vars.ownProto.__proto__', expected: { x: 1 } },
    { path: 'vars.ownProto.__proto__.x', expected: 1 },
    { path: 'trigger.output.json.a', expected: undefined },
    { path: 'trigger.output.json', expected: '{"a":{"b":1}}' },
    { path: '', expected: undefined },
    { path: ' ', expected: undefined },
    { path: 'steps..s1', expected: undefined },
    { path: 'steps.s1.output.results.', expected: undefined },
    { path: '.steps.s1.output.total', expected: undefined },
    { path: '$steps.s1.output.total', expected: undefined },
    { path: 'steps[s1].output.total', expected: undefined },
    { path: 'steps.s1.output.items[', expected: undefined },
    { path: 'steps.s1.output.items[0', expected: undefined },
    { path: 'steps.s1.output.items]0[', expected: undefined },
    { path: 'steps . s1 . output', expected: undefined },
    { path: ' steps.s1.output.total', expected: undefined },
    { path: 'steps.s1.output.total ', expected: undefined },
    { path: '[0]', expected: undefined },
    { path: '0', expected: undefined },
    { path: '1abc', expected: undefined },
    { path: 'steps.s1.output.items.*.subject', expected: undefined },
    { path: 'steps.s1.output.items[ 0 ].subject', expected: undefined },
    { path: 'steps.s1.output.items[*]x', expected: undefined },
    { path: 'x + 1', expected: undefined },
    { path: 'steps.s1.output.total > 1', expected: undefined },
    { path: 'nope', expected: undefined },
    { path: 'nope.x', expected: undefined },
];

/** walkPath(path, root): odd roots and non-string paths. */
export const WALK_ROOTS = [
    { path: 'a', root: null, expected: undefined },
    { path: 'a', root: undefined, expected: undefined },
    { path: 'a', root: 'str', expected: undefined },
    { path: 'length', root: 'str', expected: 3 },
    { path: 'length', root: [1, 2], expected: 2 },
    { path: 'a.b', root: { a: { b: 0 } }, expected: 0 },
    { path: null, root: { a: 1 }, expected: undefined },
    { path: undefined, root: { a: 1 }, expected: undefined },
    { path: 42, root: { '42': 'x' }, expected: undefined },
    { path: ['a'], root: { a: 1 }, expected: undefined },
    { path: { toString: null }, root: {}, expected: undefined },
];

/** walkRelativePath(path, value) */
export const RELATIVE = [
    { path: '', value: { a: 1 }, expected: { a: 1 } },
    { path: '$', value: [1, 2], expected: [1, 2] },
    { path: null, value: 'x', expected: 'x' },
    { path: undefined, value: 5, expected: 5 },
    { path: 'a', value: { a: { b: 1 }, 'a-b': 2 }, expected: { b: 1 } },
    { path: 'a.b', value: { a: { b: 1 } }, expected: 1 },
    { path: '[0]', value: [{ x: 1 }], expected: { x: 1 } },
    { path: '[0].x', value: [{ x: 1 }], expected: 1 },
    { path: '[*].sku', value: [{ sku: 's1' }, { sku: 's2' }, {}], expected: ['s1', 's2'] },
    { path: '0', value: [7], expected: undefined },
    { path: 'a-b', value: { 'a-b': 2 }, expected: undefined },
    { path: '["a-b"]', value: { 'a-b': 2 }, expected: 2 },
    { path: 'a["b"]', value: { a: { b: 3 } }, expected: 3 },
    { path: "a['b']", value: { a: { b: 4 } }, expected: 4 },
    { path: 'a[*].b', value: { a: [{ b: 1 }, { b: [2, 3] }] }, expected: [1, 2, 3] },
    { path: 'a.', value: { a: 1 }, expected: undefined },
    { path: 'constructor', value: {}, expected: undefined },
    { path: 'length', value: 'text', expected: 4 },
    { path: '[0]', value: 'text', expected: 't' },
    { path: 'x', value: null, expected: undefined },
    { path: '[*]', value: [[1, 2], [3]], expected: [1, 2, 3] },
    { path: '$.a', value: { a: 1 }, expected: undefined },
    { path: 0, value: [9], expected: undefined },
    { path: '.a', value: { a: 1 }, expected: undefined },
];

/**
 * interpolateTemplate(template, state, opts), where state = makeState() plus
 * `_templateWarnings: []`; `warnings` is what the call pushed there.
 */
export const TEMPLATE = [
    { template: 'Hallo {{trigger.output.name}}', expected: 'Hallo Jan', warnings: [] },
    { template: '{{ trigger.output.name }}!', expected: 'Jan!', warnings: [] },
    { template: '{{trigger.output.name}}{{trigger.output.n}}', expected: 'Jan3', warnings: [] },
    { template: 'no tokens', expected: 'no tokens', warnings: [] },
    { template: '', expected: '', warnings: [] },
    { template: '{{trigger.output.zero}}|{{trigger.output.no}}|{{trigger.output.empty}}|{{trigger.output.nil}}', expected: '0|false||', warnings: [] },
    { template: '{{steps.s1.output.nested}}', expected: '{"deep":{"deeper":{"deepest":"bottom"}}}', warnings: [] },
    { template: '{{trigger.output.tags}}', expected: '["x","y"]', warnings: [] },
    { template: '{{steps.fetch.output}}', expected: '[1,2,3]', warnings: [] },
    { template: '{{steps.num.output}}', expected: '42', warnings: [] },
    { template: '{{steps.s1.output.items[*].subject}}', expected: '["Hi","Yo","Zo"]', warnings: [] },
    { template: '{{steps.s1.output.items}}', expected: '[{"subject":"Hi","tags":["a","b"],"qty":2},{"subject":"Yo","tags":["c"],"qty":null},null,{"subject":"Zo","tags":[]}]', warnings: [] },
    { template: '{{steps.s1.output.items[0].subject}}', expected: 'Hi', warnings: [] },
    { template: '{{steps.s1.output.items.0.subject}}', expected: '', warnings: ['steps.s1.output.items.0.subject'] },
    { template: '{{trigger.output["content-type"]}}', expected: 'application/json', warnings: [] },
    { template: '{{trigger.output.body.content-type}}', expected: '', warnings: ['trigger.output.body.content-type'] },
    { template: '{{trigger.output.json}}', expected: '{"a":{"b":1}}', warnings: [] },
    { template: '{{trigger.output.missing}} and {{trigger.output.name}}', expected: ' and Jan', warnings: ['trigger.output.missing'] },
    { template: '{{x + 1}}', expected: '', warnings: ['x + 1'] },
    { template: '{{ }}', expected: '', warnings: [''] },
    { template: '{{}}', expected: '{{}}', warnings: [] },
    { template: '{{{trigger.output.name}}}', expected: '}', warnings: ['{trigger.output.name'] },
    { template: '{{trigger.output.name}', expected: '{{trigger.output.name}', warnings: [] },
    { template: '{trigger.output.name}}', expected: '{trigger.output.name}}', warnings: [] },
    { template: '{{trigger.output.name}} {{ trigger.output.name }}', expected: 'Jan Jan', warnings: [] },
    { template: '{{secrets.apiKey}}', expected: 'secret-value-1', warnings: [] },
    { template: '{{steps.s1.output.words}}', expected: '["een"," twee ",3,true,null]', warnings: [] },
    { template: '{{vars.mixed}}', expected: '[1,"two",true,null]', warnings: [] },
    { template: '{{vars.objs}}', expected: '[{"a":1}]', warnings: [] },
    { template: '{{vars.emptyList}}', expected: '[]', warnings: [] },
    { template: '{{steps.outline.output.text}}', expected: "Line 1\nLine 2", warnings: [] },
    { template: '{{steps.judge.output.reason}}', expected: 'public "share"', warnings: [] },
    { template: '{{constructor}}', expected: '', warnings: ['constructor'] },
    { template: '{{trigger.output.subject.length}}', expected: '10', warnings: [] },
    { template: "multi\nline {{trigger.output.name}}\n", expected: "multi\nline Jan\n", warnings: [] },
    { template: 42, expected: '42', warnings: [] },
    { template: null, expected: 'null', warnings: [] },
    { template: undefined, expected: 'undefined', warnings: [] },
    { template: 'Bevindingen: {{vars.list}}', opts: { listAsMarkdown: true }, expected: "Bevindingen: \n\n- a\n- b\n", warnings: [] },
    { template: '{{vars.mixed}}', opts: { listAsMarkdown: true }, expected: "\n\n- 1\n- two\n- true\n- \n", warnings: [] },
    { template: '{{vars.objs}}', opts: { listAsMarkdown: true }, expected: '[{"a":1}]', warnings: [] },
    { template: '{{vars.emptyList}}', opts: { listAsMarkdown: true }, expected: '', warnings: [] },
    { template: '{{steps.s1.output.words}}', opts: { listAsMarkdown: true }, expected: "\n\n- een\n- twee\n- 3\n- true\n- \n", warnings: [] },
    { template: '{{trigger.output.name}}', opts: { listAsMarkdown: true }, expected: 'Jan', warnings: [] },
    { template: '{{steps.s1.output.items[*].tags}}', opts: { listAsMarkdown: true }, expected: "\n\n- a\n- b\n- c\n", warnings: [] },
    { template: '{{trigger.output.matrix}}', opts: { listAsMarkdown: true }, expected: '[[1,2],[3]]', warnings: [] },
    { template: '{{trigger.output.missing}}', opts: { listAsMarkdown: true }, expected: '', warnings: ['trigger.output.missing'] },
    { template: 'Use {{trigger.output.missing}} here', opts: { leaveUnresolved: true }, expected: 'Use {{trigger.output.missing}} here', warnings: ['trigger.output.missing'] },
    { template: '{{ x + 1 }}', opts: { leaveUnresolved: true }, expected: '{{ x + 1 }}', warnings: ['x + 1'] },
    { template: '{{trigger.output.nil}}', opts: { leaveUnresolved: true }, expected: '', warnings: [] },
    { template: '{{trigger.output.name}} {{nope}}', opts: { leaveUnresolved: true }, expected: 'Jan {{nope}}', warnings: ['nope'] },
    { template: '{{steps.s1.output.items.0.subject}}', opts: { leaveUnresolved: true }, expected: '{{steps.s1.output.items.0.subject}}', warnings: ['steps.s1.output.items.0.subject'] },
    { template: '{{vars.list}} {{nope}}', opts: { leaveUnresolved: true, listAsMarkdown: true }, expected: "\n\n- a\n- b\n {{nope}}", warnings: ['nope'] },
    { template: '/Invoices/{{trigger.output.subject}}.pdf', expected: '/Invoices/Factuur 42.pdf', warnings: [] },
    { template: '{{steps.outline.output.text}}', expected: "Line 1\nLine 2", warnings: [] },
    { template: '{{trigger.output.name}}', expected: 'Jan', warnings: [] },
    { template: '/Briefings/{{steps.deck.output.filename}}', expected: '/Briefings/deck.pptx', warnings: [] },
    { template: '{"Submitted by": "{{trigger.output.submittedBy}}", "Form": "{{trigger.output.formTitle}}", "Summary": "{{steps.summarise.output}}"}', expected: '{"Submitted by": "Ada", "Form": "Intake", "Summary": "A short summary"}', warnings: [] },
    { template: '/Form intake/{{trigger.output.formTitle}} - {{trigger.output.submissionId}}.docx', expected: '/Form intake/Intake - sub-1.docx', warnings: [] },
    { template: '{{trigger.output.formTitle}}', expected: 'Intake', warnings: [] },
    { template: 'Follow up: {{trigger.output.formTitle}} ({{trigger.output.submittedBy}})', expected: 'Follow up: Intake (Ada)', warnings: [] },
    { template: 'Write a 5-line meeting briefing for "{{trigger.output.summary}}" at {{trigger.output.startsAt}}. Skip pleasantries.', expected: 'Write a 5-line meeting briefing for "Kwartaaloverleg" at 2026-10-02T09:00:00Z. Skip pleasantries.', warnings: [] },
    { template: '{{steps.brief.output}}', expected: '', warnings: ['steps.brief.output'] },
    { template: 'Given a file path, classify sensitivity as low/medium/high. Path: {{trigger.output.path}}. Return JSON {sensitivity, reason}.', expected: 'Given a file path, classify sensitivity as low/medium/high. Path: /Shared/plan.docx. Return JSON {sensitivity, reason}.', warnings: [] },
    { template: 'A new public share was created for "{{trigger.output.path}}". AI judged it: {{steps.judge.output.sensitivity}} ({{steps.judge.output.reason}}). Approve to REVOKE this share; reject to leave it active.', expected: 'A new public share was created for "/Shared/plan.docx". AI judged it: high (public "share"). Approve to REVOKE this share; reject to leave it active.', warnings: [] },
    { template: '{{trigger.output.datetime}} — {{trigger.output.actor}}: {{trigger.output.message}}', expected: '2026-10-01 10:00 — piet: Klaar', warnings: [] },
    { template: '🎉 "{{trigger.output.title}}" is done!', expected: '🎉 "Release" is done!', warnings: [] },
    { template: '/Welcome/{{trigger.output.actor}}', expected: '/Welcome/piet', warnings: [] },
    { template: 'Welcome to the team @{{trigger.output.actor}}!', expected: 'Welcome to the team @piet!', warnings: [] },
    { template: '{{steps.distill.output.title}}', expected: 'T', warnings: [] },
    { template: '{{steps.distill.output.article}}', expected: 'Body', warnings: [] },
    { template: 'support://ticket/{{trigger.output.threadId}}', expected: 'support://ticket/t-9', warnings: [] },
    { template: '{"items": {{steps.s1.output.items[*].subject}}, "n": {{trigger.output.n}}, "nested": {{steps.s1.output.nested}}}', expected: '{"items": ["Hi","Yo","Zo"], "n": 3, "nested": {"deep":{"deeper":{"deepest":"bottom"}}}}', warnings: [] },
    { template: '{"text": "{{steps.outline.output.text}}"}', expected: "{\"text\": \"Line 1\nLine 2\"}", warnings: [] },
];

/** resolveValue(binding, makeState(), opts) */
export const RESOLVE = [
    { binding: { kind: 'literal', value: 'x' }, expected: 'x' },
    { binding: { kind: 'literal', value: null }, expected: null },
    { binding: { kind: 'literal', value: 0 }, expected: 0 },
    { binding: { kind: 'literal', value: false }, expected: false },
    { binding: { kind: 'literal', value: { a: [1, { b: 2 }] } }, expected: { a: [1, { b: 2 }] } },
    { binding: { kind: 'literal' }, expected: undefined },
    { binding: { kind: 'literal', value: '{{trigger.output.name}}' }, expected: '{{trigger.output.name}}' },
    { binding: { kind: 'literal', value: { kind: 'ref', path: 'trigger.output.name' } }, expected: { kind: 'ref', path: 'trigger.output.name' } },
    { binding: null, expected: null },
    { binding: undefined, expected: undefined },
    { binding: 'bare', expected: 'bare' },
    { binding: 42, expected: 42 },
    { binding: true, expected: true },
    { binding: ['a', { kind: 'ref', path: 'trigger.output.name' }], expected: ['a', 'Jan'] },
    { binding: { to: 'a@b.nl', body: { kind: 'ref', path: 'trigger.output.name' } }, expected: { to: 'a@b.nl', body: 'Jan' } },
    { binding: { path: 'trigger.output.name' }, expected: { path: 'trigger.output.name' } },
    { binding: { value: '{{trigger.output.name}}' }, expected: { value: '{{trigger.output.name}}' } },
    { binding: { kind: '', value: 1 }, expected: { kind: '', value: 1 } },
    { binding: { kind: 0, value: 1 }, expected: { kind: 0, value: 1 } },
    { binding: { kind: 'ref', path: 'trigger.output.name' }, expected: 'Jan' },
    { binding: { kind: 'ref', path: 'trigger.output.nil' }, expected: null },
    { binding: { kind: 'ref', path: 'trigger.output.missing' }, expected: undefined },
    { binding: { kind: 'ref', path: 'trigger.name' }, expected: undefined },
    { binding: { kind: 'ref', path: 'steps.s1.output.items[0].subject' }, expected: 'Hi' },
    { binding: { kind: 'ref', path: 'steps.s1.output.items.0.subject' }, expected: undefined },
    { binding: { kind: 'ref', path: 'steps.s1.output.results[*].output.a' }, expected: [1, 2] },
    { binding: { kind: 'ref', path: 'steps.s1.output.results.' }, expected: undefined },
    { binding: { kind: 'ref', path: 'steps.s1.output.results[*].output.attachments' }, expected: [{ name: 'x1' }, { name: 'x2' }, { name: 'single' }] },
    { binding: { kind: 'ref', path: 'loop.row["Due date"]' }, expected: 'morgen' },
    { binding: { kind: 'ref', path: 'loop.row.Due' }, expected: undefined },
    { binding: { kind: 'ref', path: 'loop.row["e-mail"]' }, expected: 'a@b.nl' },
    { binding: { kind: 'ref', path: 'loop.row.e' }, expected: undefined },
    { binding: { kind: 'ref', path: 'trigger.output.body.content-type' }, expected: undefined },
    { binding: { kind: 'ref', path: 'steps.$read.output.results' }, expected: [{ content: 'r1' }, { content: 'r2' }] },
    { binding: { kind: 'ref', path: 'loop.e.output.btw' }, expected: 21 },
    { binding: { kind: 'ref', path: 'loop._index' }, expected: 2 },
    { binding: { kind: 'ref', path: 'secrets.apiKey' }, expected: undefined },
    { binding: { kind: 'ref', path: 'steps.s1.output.nested' }, expected: { deep: { deeper: { deepest: 'bottom' } } } },
    { binding: { kind: 'ref', path: 'steps.fetch.output' }, expected: [1, 2, 3] },
    { binding: { kind: 'ref', path: 'vars.list' }, expected: ['a', 'b'] },
    { binding: { kind: 'ref', path: 'trigger.output.json' }, expected: '{"a":{"b":1}}' },
    { binding: { kind: 'ref', path: '' }, expected: undefined },
    { binding: { kind: 'ref', path: 'steps..s1' }, expected: undefined },
    { binding: { kind: 'ref' }, expected: undefined },
    { binding: { kind: 'ref', path: 5 }, expected: undefined },
    { binding: { kind: 'ref', path: 'secrets.apiKey' }, opts: { allowSecrets: true }, expected: 'secret-value-1' },
    { binding: { kind: 'ref', path: 'trigger.output.name' }, opts: { allowSecrets: true }, expected: 'Jan' },
    { binding: { kind: 'template', value: 'Hi {{trigger.output.name}}' }, expected: 'Hi Jan' },
    { binding: { kind: 'template' }, expected: '' },
    { binding: { kind: 'template', value: '' }, expected: '' },
    { binding: { kind: 'template', value: '{{secrets.apiKey}}' }, expected: '' },
    { binding: { kind: 'template', value: '{{secrets.apiKey}}' }, opts: { allowSecrets: true }, expected: 'secret-value-1' },
    { binding: { kind: 'template', value: '{{steps.s1.output.items}}' }, expected: '[{"subject":"Hi","tags":["a","b"],"qty":2},{"subject":"Yo","tags":["c"],"qty":null},null,{"subject":"Zo","tags":[]}]' },
    { binding: { kind: 'template', value: 'no tokens' }, expected: 'no tokens' },
    { binding: { kind: 'template', value: 42 }, expected: '42' },
    { binding: { kind: 'template', value: '{{vars.list}}' }, expected: '["a","b"]' },
    { binding: { kind: 'expr', value: 'steps.s1.output.total > 1 ? "high" : "low"' }, expected: 'high' },
    { binding: { kind: 'expr', value: 'trigger.output.n * 2' }, expected: 6 },
    { binding: { kind: 'expr', value: 'lower(trigger.output.name)' }, expected: 'jan' },
    { binding: { kind: 'expr', value: 'count(steps.s1.output.items)' }, expected: 4 },
    { binding: { kind: 'expr', value: 'steps.s1.output.items[0].subject' }, expected: 'Hi' },
    { binding: { kind: 'expr', value: '1 +' }, expected: undefined },
    { binding: { kind: 'expr' }, expected: undefined },
    { binding: { kind: 'expr', value: 'nope.x' }, expected: undefined },
    { binding: { kind: 'expr', value: 'secrets.apiKey' }, expected: undefined },
    { binding: { kind: 'expr', value: 'secrets.apiKey' }, opts: { allowSecrets: true }, expected: 'secret-value-1' },
    { binding: { kind: 'expr', value: 'unknownFn(1)' }, expected: undefined },
    { binding: { kind: 'expr', value: 'concat(trigger.output.name, "!")' }, expected: 'Jan!' },
    { binding: { kind: 'mystery', value: 1 }, expected: undefined },
    { binding: { kind: 'pick', from: { root: 'trigger', path: ['name'] }, take: 'one', as: 'native' }, expected: undefined },
    { binding: { kind: 'compose', parts: ['x'] }, expected: undefined },
];

/** resolveDeep(structure, makeState(), opts) */
export const DEEP = [
    { structure: { a: { kind: 'ref', path: 'trigger.output.name' }, b: [{ kind: 'template', value: '{{trigger.output.n}}' }, 3], c: { d: { kind: 'literal', value: [1] } } }, expected: { a: 'Jan', b: ['3', 3], c: { d: [1] } } },
    { structure: [{ kind: 'ref', path: 'vars.rate' }, 'x', null, undefined], expected: [1.21, 'x', null, undefined] },
    { structure: null, expected: null },
    { structure: undefined, expected: undefined },
    { structure: 's', expected: 's' },
    { structure: 7, expected: 7 },
    { structure: { kind: 'mystery', value: { kind: 'ref', path: 'trigger.output.name' } }, expected: { kind: 'mystery', value: 'Jan' } },
    { structure: { kind: 'pick', from: { root: 'trigger', path: ['name'] } }, expected: { kind: 'pick', from: { root: 'trigger', path: ['name'] } } },
    { structure: { nested: { kind: 'pick', from: { root: 'trigger', path: ['name'] }, take: 'one', as: 'native' } }, expected: { nested: { kind: 'pick', from: { root: 'trigger', path: ['name'] }, take: 'one', as: 'native' } } },
    { structure: { kind: 'ref', path: 'secrets.apiKey' }, expected: undefined },
    { structure: { s: { kind: 'ref', path: 'secrets.apiKey' } }, opts: { allowSecrets: true }, expected: { s: 'secret-value-1' } },
    { structure: { kind: 'expr', value: 'trigger.output.n + 1' }, expected: 4 },
    { structure: { path: 'trigger.output.name' }, expected: { path: 'trigger.output.name' } },
];

/** resolveInputs(inputs, makeState(), opts) */
export const INPUTS = [
    { inputs: { to: { kind: 'ref', path: 'trigger.output.name' }, n: { kind: 'expr', value: 'trigger.output.n + 1' }, miss: { kind: 'ref', path: 'trigger.output.missing' }, bare: 'x', t: { kind: 'template', value: '{{vars.greeting}} {{trigger.output.name}}' } }, expected: { to: 'Jan', n: 4, miss: undefined, bare: 'x', t: 'Hallo Jan' } },
    { inputs: null, expected: {} },
    { inputs: undefined, expected: {} },
    { inputs: 'str', expected: {} },
    { inputs: {}, expected: {} },
    { inputs: [{ kind: 'ref', path: 'vars.rate' }], expected: { '0': 1.21 } },
    { inputs: { k: { kind: 'ref', path: 'secrets.apiKey' } }, opts: { allowSecrets: true }, expected: { k: 'secret-value-1' } },
];

// ── v2: pick and compose ──────────────────────────────────────────────────
//
// Unlike everything above, these cases were not recorded from an older
// runtime: they ARE the specification of the v2 mapping (design §3), written
// out case by case. They run against makeMappingState(), never against
// makeState(), so the legacy cases above stay exactly as they were recorded.
// `warnings` lists the codes onWarning reports, in order (none when absent).

const S = (id, ...path) => ({ root: 'steps', id, path });
const T = (...path) => ({ root: 'trigger', path });
const pick = (from, take = 'one', as = 'native', extra = {}) => ({ kind: 'pick', v: 1, from, take, as, ...extra });
const part = (from, take = 'one', as = 'text', extra = {}) => ({ from, take, as, ...extra });
const ORDERS = S('orders', 'orders');

/** The run state the v2 cases read: depth, lists, tables, holes, JSON text, Dutch numbers. */
export function makeMappingState() {
    return {
        trigger: {
            output: {
                Klant: { Naam: 'Jan Jansen', 'E-mail adres': 'jan@voorbeeld.nl', Adres: { Straat: 'Dorpsstraat 1', Postcode: '1234 AB' } },
                bedrag: '€ 1.554,25',
                aantal: '12,5',
                plain: '1.234',
                datum: '2026-10-01',
                moment: '2026-10-01T10:00:00+02:00',
                gmail: 'Tue, 01 Sep 2026 10:00:00 +0200',
                epoch: 1756720800,
                ja: 'ja',
                nee: 'Nee',
                yes: true,
                flag: 'misschien',
                leeg: '',
                niets: null,
                nul: 0,
                tags: ['spoed', 'klant'],
                json: '{"order":{"lines":[{"sku":"A1","qty":2},{"sku":"B2","qty":1}]}}',
                badJson: '{"order":',
                tekst: 'gewoon tekst',
            },
            headers: { 'x-trace': 'h1' },
            id: 'trg-1',
            kind: 'webhook',
            firedAt: '2026-10-01T08:00:00Z',
        },
        steps: {
            orders: {
                output: {
                    orders: [
                        { id: 'o1', klant: { naam: 'Ada', email: 'ada@example.org' }, lines: [{ product: 'Stoel', qty: 2, prijs: '€40' }, { product: 'Tafel', qty: 1, prijs: '€150' }], tags: ['a', 'b'] },
                        { id: 'o2', klant: { naam: 'Bob' }, lines: [{ product: 'Lamp', qty: 3, prijs: '€25' }], tags: [] },
                        null,
                        { id: 'o4', lines: [], tags: ['c'] },
                    ],
                    total: 3,
                    empty: [],
                    matrix: [[1, 2], [3]],
                    deep: { a: { b: { c: { d: { e: { f: 'zes' } } } } } },
                    deepList: { a: [{ b: { c: [{ d: { e: 'x1' } }, { d: { e: 'x2' } }] } }, { b: { c: [] } }, { b: { c: [{ d: { e: 'x3' } }] } }] },
                    mixed: [1, 'twee', true, null, { k: 'v' }],
                },
            },
            text: { output: 'Gewone tekst' },
            num: { output: 42 },
            list: { output: ['x', 'y', 'z'] },
            nul: { output: null },
            jsonOut: { output: '[{"a":1},{"a":2}]' },
        },
        vars: { rate: '21', greeting: 'Hallo', own: JSON.parse('{"__proto__":{"x":1},"constructor":"own","length":3,"ok":"ja"}') },
        loop: { row: { email: 'row@example.org', n: 2 }, _index: 1 },
        item: { amount: '1.250,50', name: 'Rij' },
        secrets: { apiKey: 'secret-value-1' },
    };
}

/** walk(sourceBase(source), source.path), as plain data: nesting and holes kept. */
export const WALK_V2 = [
    { source: S('orders', 'orders', 'id'), expected: ['o1', 'o2', undefined, 'o4'] },
    { source: S('orders', 'orders', 'klant', 'naam'), expected: ['Ada', 'Bob', undefined, undefined] },
    { source: S('orders', 'orders', 'lines', 'product'), expected: [['Stoel', 'Tafel'], ['Lamp'], undefined, []] },
    { source: S('orders', 'orders', 0, 'lines', 1, 'product'), expected: 'Tafel' },
    { source: S('orders', 'orders', 2), expected: null },
    { source: S('orders', 'orders', 9), expected: undefined },
    { source: S('orders', 'orders', 2, 'id'), expected: undefined },
    { source: S('orders', 'deep', 'a', 'b', 'c', 'd', 'e', 'f'), expected: 'zes' },
    { source: S('orders', 'deepList', 'a', 'b', 'c', 'd', 'e'), expected: [['x1', 'x2'], [], ['x3']] },
    { source: S('orders', 'matrix'), expected: [[1, 2], [3]] },
    { source: S('orders', 'matrix', 0, 1), expected: 2 },
    { source: S('orders', 'empty', 'x'), expected: [] },
    { source: S('orders', 'mixed', 'k'), expected: [undefined, undefined, undefined, undefined, 'v'] },
    { source: T('json', 'order', 'lines', 'sku'), expected: ['A1', 'B2'] },
    { source: T('json'), expected: '{"order":{"lines":[{"sku":"A1","qty":2},{"sku":"B2","qty":1}]}}' },
    { source: T('badJson', 'order'), expected: undefined },
    { source: T('tekst', 'x'), expected: undefined },
    { source: S('jsonOut', 'a'), expected: [1, 2] },
    { source: T('Klant', 'Adres', 'Postcode'), expected: '1234 AB' },
    { source: T('Klant', 'E-mail adres'), expected: 'jan@voorbeeld.nl' },
    { source: T('Klant', 0), expected: undefined },
    { source: S('list', 1), expected: 'y' },
    { source: S('list', 'length'), expected: [undefined, undefined, undefined] },
    { source: { root: 'vars', path: ['own', 'ok'] }, expected: 'ja' },
    { source: { root: 'vars', path: ['own', 'constructor'] }, expected: undefined },
    { source: { root: 'vars', path: ['own', 'length'] }, expected: undefined },
    { source: { root: 'vars', path: ['own', '__proto__'] }, expected: undefined },
    { source: { root: 'vars', path: ['own', 'x'] }, expected: undefined },
    { source: { root: 'vars', path: ['greeting', 'toString'] }, expected: undefined },
    { source: { root: 'run', path: ['id'] }, expected: 'trg-1' },
    { source: { root: 'run', path: ['firedAt'] }, expected: '2026-10-01T08:00:00Z' },
    { source: { root: 'run', path: ['output', 'tekst'] }, expected: undefined },
    { source: { root: 'run', path: ['headers'] }, expected: undefined },
    { source: { root: 'item', path: ['amount'] }, expected: '1.250,50' },
    { source: { root: 'loop', id: 'row', path: ['email'] }, expected: 'row@example.org' },
    { source: { root: 'secrets', path: ['apiKey'] }, expected: undefined },
    { source: S('missing', 'x'), expected: undefined },
    { source: S('nul', 'x'), expected: undefined },
    { source: S('text'), expected: 'Gewone tekst' },
    { source: S('orders', 'orders', -1), expected: undefined },
    { source: S('orders', 'orders', 1.5), expected: undefined },
    { source: S('orders', 'orders', { wild: true }, 'id'), expected: undefined },
];

/** resolveValue(binding, makeMappingState()) for a pick: every take, as and join on every shape. */
export const PICKS = [
    // one
    { binding: pick(T('Klant', 'E-mail adres')), expected: 'jan@voorbeeld.nl' },
    { binding: pick(T('Klant', 'Adres')), expected: { Straat: 'Dorpsstraat 1', Postcode: '1234 AB' } },
    { binding: pick(T('tags')), expected: ['spoed', 'klant'] },
    { binding: pick(T('niets')), expected: null },
    { binding: pick(T('missing')), expected: undefined, warnings: ['missing'] },
    { binding: pick(S('orders', 'orders', 'klant', 'naam')), expected: 'Ada', warnings: ['many_for_one'] },
    { binding: pick(S('orders', 'orders', 'klant', 'naam'), 'one', 'text'), expected: 'Ada', warnings: ['many_for_one'] },
    { binding: pick(T('tags'), 'one', 'text'), expected: 'spoed\nklant' },
    { binding: pick(T('tags'), 'one', 'number'), expected: undefined, warnings: ['many_for_one', 'parse_failed'] },
    { binding: pick(T('Klant'), 'one', 'text'), expected: 'Naam: Jan Jansen\nE-mail adres: jan@voorbeeld.nl\nAdres: Dorpsstraat 1 · 1234 AB' },
    { binding: pick(T('Klant'), 'one', 'text', { join: 'comma' }), expected: 'Naam: Jan Jansen, E-mail adres: jan@voorbeeld.nl, Adres: Dorpsstraat 1 · 1234 AB' },
    { binding: pick(T('Klant'), 'one', 'json'), expected: { Naam: 'Jan Jansen', 'E-mail adres': 'jan@voorbeeld.nl', Adres: { Straat: 'Dorpsstraat 1', Postcode: '1234 AB' } } },
    { binding: pick(T('leeg'), 'one', 'text'), expected: '' },
    { binding: pick(T('missing'), 'one', 'text'), expected: '', warnings: ['missing'] },
    { binding: pick(T('missing'), 'one', 'list'), expected: [], warnings: ['missing'] },
    { binding: pick(T('Klant', 'E-mail adres'), 'one', 'list'), expected: ['jan@voorbeeld.nl'] },
    // all
    { binding: pick(S('orders', 'orders', 'lines', 'product'), 'all', 'list'), expected: ['Stoel', 'Tafel', 'Lamp'], warnings: ['holes_dropped'] },
    { binding: pick(S('orders', 'orders', 'lines', 'product'), 'all', 'text'), expected: 'Stoel\nTafel\nLamp', warnings: ['holes_dropped'] },
    { binding: pick(S('orders', 'orders', 'lines', 'product'), 'all', 'text', { join: 'comma' }), expected: 'Stoel, Tafel, Lamp', warnings: ['holes_dropped'] },
    { binding: pick(S('orders', 'orders', 'lines', 'product'), 'all', 'text', { join: 'bullets' }), expected: '- Stoel\n- Tafel\n- Lamp', warnings: ['holes_dropped'] },
    { binding: pick(S('orders', 'orders', 'lines', 'product'), 'all', 'native'), expected: ['Stoel', 'Tafel', 'Lamp'], warnings: ['holes_dropped'] },
    { binding: pick(S('orders', 'orders', 'lines', 'product'), 'all', 'json'), expected: ['Stoel', 'Tafel', 'Lamp'], warnings: ['holes_dropped'] },
    { binding: pick(S('orders', 'orders', 'lines'), 'all', 'text'), expected: 'Stoel · 2 · €40\nTafel · 1 · €150\nLamp · 3 · €25', warnings: ['holes_dropped'] },
    { binding: pick(S('orders', 'orders', 'lines'), 'all', 'list'), expected: [{ product: 'Stoel', qty: 2, prijs: '€40' }, { product: 'Tafel', qty: 1, prijs: '€150' }, { product: 'Lamp', qty: 3, prijs: '€25' }], warnings: ['holes_dropped'] },
    { binding: pick(S('orders', 'orders', 'klant'), 'all', 'text'), expected: 'Ada · ada@example.org\nBob', warnings: ['holes_dropped'] },
    { binding: pick(S('orders', 'orders', 'id'), 'all', 'list'), expected: ['o1', 'o2', 'o4'], warnings: ['holes_dropped'] },
    { binding: pick(S('orders', 'orders', 'tags'), 'all', 'list'), expected: ['a', 'b', 'c'], warnings: ['holes_dropped'] },
    { binding: pick(ORDERS, 'all', 'list'), expected: [{ id: 'o1', klant: { naam: 'Ada', email: 'ada@example.org' }, lines: [{ product: 'Stoel', qty: 2, prijs: '€40' }, { product: 'Tafel', qty: 1, prijs: '€150' }], tags: ['a', 'b'] }, { id: 'o2', klant: { naam: 'Bob' }, lines: [{ product: 'Lamp', qty: 3, prijs: '€25' }], tags: [] }, null, { id: 'o4', lines: [], tags: ['c'] }] },
    { binding: pick(ORDERS, 'all', 'native'), expected: [{ id: 'o1', klant: { naam: 'Ada', email: 'ada@example.org' }, lines: [{ product: 'Stoel', qty: 2, prijs: '€40' }, { product: 'Tafel', qty: 1, prijs: '€150' }], tags: ['a', 'b'] }, { id: 'o2', klant: { naam: 'Bob' }, lines: [{ product: 'Lamp', qty: 3, prijs: '€25' }], tags: [] }, null, { id: 'o4', lines: [], tags: ['c'] }] },
    { binding: pick(S('orders', 'matrix'), 'all', 'text'), expected: '1, 2\n3' },
    { binding: pick(S('orders', 'matrix'), 'all', 'list'), expected: [[1, 2], [3]] },
    { binding: pick(S('orders', 'mixed'), 'all', 'text'), expected: '1\ntwee\ntrue\nv' },
    { binding: pick(S('orders', 'mixed'), 'all', 'text', { join: 'comma' }), expected: '1, twee, true, v' },
    { binding: pick(S('orders', 'deepList', 'a', 'b', 'c', 'd', 'e'), 'all', 'list'), expected: ['x1', 'x2', 'x3'] },
    { binding: pick(S('orders', 'empty'), 'all', 'list'), expected: [] },
    { binding: pick(S('orders', 'empty'), 'all', 'text'), expected: '' },
    { binding: pick(T('tags'), 'all', 'native'), expected: ['spoed', 'klant'] },
    { binding: pick(S('text'), 'all', 'list'), expected: ['Gewone tekst'] },
    { binding: pick(S('num'), 'all', 'text'), expected: '42' },
    { binding: pick(S('nul'), 'all', 'list'), expected: [] },
    { binding: pick(S('nul'), 'all', 'text'), expected: '' },
    { binding: pick(T('missing'), 'all', 'list'), expected: [], warnings: ['missing'] },
    { binding: pick(T('json', 'order', 'lines', 'sku'), 'all', 'list'), expected: ['A1', 'B2'] },
    { binding: pick(S('jsonOut', 'a'), 'all', 'text', { join: 'comma' }), expected: '1, 2' },
    // first, last
    { binding: pick(S('orders', 'orders', 'lines', 'product'), 'first'), expected: 'Stoel' },
    { binding: pick(S('orders', 'orders', 'lines', 'product'), 'last'), expected: 'Lamp' },
    { binding: pick(S('list'), 'first', 'text'), expected: 'x' },
    { binding: pick(S('list'), 'last', 'text'), expected: 'z' },
    { binding: pick(S('text'), 'first'), expected: 'Gewone tekst' },
    { binding: pick(S('text'), 'last'), expected: 'Gewone tekst' },
    { binding: pick(S('orders', 'empty'), 'first'), expected: undefined, warnings: ['missing'] },
    { binding: pick(T('json', 'order', 'lines', 'qty'), 'first', 'number'), expected: 2 },
    // count: the same items `all` sends
    { binding: pick(S('orders', 'orders', 'lines', 'product'), 'count'), expected: 3 },
    { binding: pick(S('orders', 'orders', 'id'), 'count'), expected: 3 },
    { binding: pick(ORDERS, 'count'), expected: 4 },
    { binding: pick(ORDERS, 'count', 'text'), expected: '4' },
    { binding: pick(S('text'), 'count'), expected: 1 },
    { binding: pick(S('num'), 'count'), expected: 1 },
    { binding: pick(S('nul'), 'count'), expected: 0 },
    { binding: pick(T('missing'), 'count'), expected: 0 },
    { binding: pick(S('orders', 'empty'), 'count'), expected: 0 },
    // number: what Number() reads first, then the Dutch and euro forms
    { binding: pick(T('bedrag'), 'one', 'number'), expected: 1554.25 },
    { binding: pick(T('aantal'), 'one', 'number'), expected: 12.5 },
    { binding: pick(T('plain'), 'one', 'number'), expected: 1.234 },
    { binding: pick(T('nul'), 'one', 'number'), expected: 0 },
    { binding: pick(T('epoch'), 'one', 'number'), expected: 1756720800 },
    { binding: pick({ root: 'vars', path: ['rate'] }, 'one', 'number'), expected: 21 },
    { binding: pick({ root: 'item', path: ['amount'] }, 'one', 'number'), expected: 1250.5 },
    { binding: pick(T('tekst'), 'one', 'number'), expected: undefined, warnings: ['parse_failed'] },
    { binding: pick(T('leeg'), 'one', 'number'), expected: undefined, warnings: ['missing'] },
    { binding: pick(T('yes'), 'one', 'number'), expected: undefined, warnings: ['parse_failed'] },
    { binding: pick(S('orders', 'orders', 'lines', 'qty'), 'one', 'number'), expected: 2, warnings: ['many_for_one'] },
    // date
    { binding: pick(T('datum'), 'one', 'date'), expected: '2026-10-01' },
    { binding: pick(T('moment'), 'one', 'date'), expected: '2026-10-01T10:00:00+02:00' },
    { binding: pick(T('gmail'), 'one', 'date'), expected: '2026-09-01T08:00:00.000Z' },
    { binding: pick(T('epoch'), 'one', 'date'), expected: '2025-09-01T10:00:00.000Z' },
    { binding: pick(T('tekst'), 'one', 'date'), expected: undefined, warnings: ['parse_failed'] },
    // yes/no
    { binding: pick(T('ja'), 'one', 'yesno'), expected: true },
    { binding: pick(T('nee'), 'one', 'yesno'), expected: false },
    { binding: pick(T('yes'), 'one', 'yesno'), expected: true },
    { binding: pick(T('nul'), 'one', 'yesno'), expected: false },
    { binding: pick(S('num'), 'one', 'yesno'), expected: true },
    { binding: pick(T('flag'), 'one', 'yesno'), expected: undefined, warnings: ['parse_failed'] },
    // the other roots
    { binding: pick({ root: 'run', path: ['id'] }), expected: 'trg-1' },
    { binding: pick({ root: 'loop', id: 'row', path: ['email'] }), expected: 'row@example.org' },
    { binding: pick({ root: 'vars', path: ['own', 'constructor'] }), expected: undefined, warnings: ['missing'] },
    // required, and what is not a valid pick
    { binding: pick(T('missing'), 'one', 'native', { required: true }), expected: undefined, warnings: ['missing_required'] },
    { binding: pick(T('Klant', 'Naam'), 'one', 'native', { label: 'Naam van klant' }), expected: 'Jan Jansen' },
    { binding: pick(T('Klant', 'Naam'), 'twice'), expected: undefined, warnings: ['mapping_invalid'] },
    { binding: pick(S('orders', 'orders', { wild: true }, 'id'), 'all', 'list'), expected: undefined, warnings: ['mapping_invalid'] },
    { binding: pick({ root: 'secrets', path: ['apiKey'] }), expected: undefined, warnings: ['mapping_invalid'] },
    { binding: { kind: 'pick', from: T('Klant', 'Naam'), take: 'one', as: 'native' }, expected: undefined },
    { binding: { kind: 'pick', v: 2, from: T('Klant', 'Naam'), take: 'one', as: 'native' }, expected: undefined },
    { binding: pick(T('Klant', 'Naam'), 'each'), expected: undefined, warnings: ['each_outside_repeat'] },
    { binding: pick(T('Klant', 'Naam'), 'each', 'list'), expected: [], warnings: ['each_outside_repeat'] },
];

/**
 * resolveValue(binding, state) for a pick that takes `each`: `state` is
 * makeMappingState() with `_mappingScope = { over, item, index: 0 }`, the item
 * a repeated step runs for.
 */
export const EACH = [
    { over: ORDERS, item: 0, binding: pick(S('orders', 'orders', 'id'), 'each'), expected: 'o1' },
    { over: ORDERS, item: 0, binding: pick(S('orders', 'orders', 'klant', 'email'), 'each'), expected: 'ada@example.org' },
    { over: ORDERS, item: 0, binding: pick(S('orders', 'orders', 'lines', 'product'), 'each', 'text'), expected: 'Stoel\nTafel' },
    { over: ORDERS, item: 0, binding: pick(S('orders', 'orders', 'lines', 'product'), 'each', 'list'), expected: ['Stoel', 'Tafel'] },
    { over: ORDERS, item: 0, binding: pick(S('orders', 'orders', 'lines', 'product'), 'each'), expected: 'Stoel', warnings: ['many_for_one'] },
    { over: ORDERS, item: 0, binding: pick(ORDERS, 'each'), expected: { id: 'o1', klant: { naam: 'Ada', email: 'ada@example.org' }, lines: [{ product: 'Stoel', qty: 2, prijs: '€40' }, { product: 'Tafel', qty: 1, prijs: '€150' }], tags: ['a', 'b'] } },
    { over: ORDERS, item: 1, binding: pick(S('orders', 'orders', 'klant', 'email'), 'each'), expected: undefined, warnings: ['missing'] },
    { over: ORDERS, item: 2, binding: pick(S('orders', 'orders', 'id'), 'each', 'text'), expected: '', warnings: ['missing'] },
    { over: S('orders', 'orders', 'lines'), item: 2, binding: pick(S('orders', 'orders', 'lines', 'prijs'), 'each'), expected: '€25' },
    { over: ORDERS, item: 0, binding: pick(S('orders', 'orders', 'lines', 'product'), 'all', 'list'), expected: ['Stoel', 'Tafel', 'Lamp'], warnings: ['holes_dropped'] },
    { over: ORDERS, item: 0, binding: pick(S('text'), 'each'), expected: undefined, warnings: ['each_outside_repeat'] },
    { over: ORDERS, item: 0, binding: pick(S('orders', 'orders'), 'each', 'number'), expected: undefined, warnings: ['parse_failed'] },
];

/** interpolateTemplate(template, makeMappingState()), and resolveValue gives the same. */
export const COMPOSE = [
    {
        template: { kind: 'compose', v: 1, parts: ['Beste ', part(T('Klant', 'Naam')), ',\nUw orders:\n', part(S('orders', 'orders', 'lines', 'product'), 'all', 'text', { join: 'bullets' })] },
        expected: 'Beste Jan Jansen,\nUw orders:\n- Stoel\n- Tafel\n- Lamp', warnings: ['holes_dropped'],
    },
    { template: { kind: 'compose', v: 1, parts: ['Aantal: ', part(S('orders', 'orders', 'id'), 'count')] }, expected: 'Aantal: 3' },
    { template: { kind: 'compose', v: 1, parts: ['Klant: ', part(T('Klant'), 'one', 'json')] }, expected: 'Klant: {"Naam":"Jan Jansen","E-mail adres":"jan@voorbeeld.nl","Adres":{"Straat":"Dorpsstraat 1","Postcode":"1234 AB"}}' },
    { template: { kind: 'compose', v: 1, parts: ['Klant: ', part(T('Klant'))] }, expected: 'Klant: Naam: Jan Jansen\nE-mail adres: jan@voorbeeld.nl\nAdres: Dorpsstraat 1 · 1234 AB' },
    { template: { kind: 'compose', v: 1, parts: ['Hallo ', part(T('missing')), '!'] }, expected: 'Hallo !', warnings: ['missing'] },
    { template: { kind: 'compose', v: 1, parts: ['Tabel:\n', part(S('orders', 'orders', 'lines'), 'all')] }, expected: 'Tabel:\nStoel · 2 · €40\nTafel · 1 · €150\nLamp · 3 · €25', warnings: ['holes_dropped'] },
    { template: { kind: 'compose', v: 1, parts: ['Bedrag ', part(T('bedrag'), 'one', 'number')] }, expected: 'Bedrag 1554.25' },
    { template: { kind: 'compose', v: 1, parts: ['Tags: ', part(T('tags'), 'all', 'text', { join: 'comma' })] }, expected: 'Tags: spoed, klant' },
    { template: { kind: 'compose', v: 1, parts: ['vast'] }, expected: 'vast' },
    { template: { kind: 'compose', v: 1, parts: [] }, expected: '' },
    { template: { kind: 'compose', v: 1, parts: ['x', { from: T('tags'), take: 'all', as: 'sideways' }] }, expected: '', warnings: ['mapping_invalid'] },
    { template: { kind: 'compose', parts: ['geen versie'] }, expected: '' },
];

/** resolveDeep(structure, makeMappingState()): v2 kinds inside plain data, and what stays data. */
export const DEEP_V2 = [
    { structure: { to: pick(T('Klant', 'E-mail adres')), note: 'x' }, expected: { to: 'jan@voorbeeld.nl', note: 'x' } },
    { structure: [pick(S('list'), 'last'), { kind: 'compose', v: 1, parts: ['n=', part(S('num'))] }], expected: ['z', 'n=42'] },
    { structure: { nested: { kind: 'pick', from: T('Klant', 'Naam'), take: 'one', as: 'native' } }, expected: { nested: { kind: 'pick', from: { root: 'trigger', path: ['Klant', 'Naam'] }, take: 'one', as: 'native' } } },
    { structure: { nested: { kind: 'pick', v: 1, from: T('Klant', 'Naam'), take: 'sideways', as: 'native' } }, expected: { nested: { kind: 'pick', v: 1, from: { root: 'trigger', path: ['Klant', 'Naam'] }, take: 'sideways', as: 'native' } } },
    { structure: { kind: 'literal', value: pick(T('Klant', 'Naam')) }, expected: { kind: 'pick', v: 1, from: { root: 'trigger', path: ['Klant', 'Naam'] }, take: 'one', as: 'native' } },
    { structure: { data: { ...pick(T('Klant', 'Naam')), label: 'Naam', extra: 1 } }, expected: { data: 'Jan Jansen' } },
    { structure: { mixed: [{ kind: 'ref', path: 'trigger.output.tekst' }, pick(T('tekst'), 'one', 'text')] }, expected: { mixed: ['gewoon tekst', 'gewoon tekst'] } },
];

/** resolveInputs(inputs, makeMappingState(), opts): a pick that gives nothing leaves its input out. */
export const INPUTS_V2 = [
    { inputs: { to: pick(T('Klant', 'E-mail adres')), cc: pick(T('missing')), legacy: { kind: 'ref', path: 'trigger.output.missing' } }, expected: { to: 'jan@voorbeeld.nl', legacy: undefined }, warnings: ['missing', 'missing'] },
    { inputs: { cc: pick(T('missing')) }, opts: { required: ['cc'] }, expected: {}, warnings: ['missing_required'] },
    { inputs: { body: { kind: 'compose', v: 1, parts: ['Hoi ', part(T('Klant', 'Naam'))] }, n: pick(T('aantal'), 'one', 'number') }, expected: { body: 'Hoi Jan Jansen', n: 12.5 } },
    { inputs: { list: pick(T('missing'), 'all', 'list'), text: pick(T('missing'), 'one', 'text') }, expected: { list: [], text: '' }, warnings: ['missing', 'missing'] },
];
