/**
 * GENERATED by scripts/sync-web-icons.mjs — do not edit. Run
 * `node scripts/sync-web-icons.mjs` after changing its MOBILE_ICONS or when
 * the web's iconRegistry.js changes (registry.generated.test.ts fails then).
 *
 * One import per icon file: the package barrel would bundle all of Lucide.
 */
/* eslint-disable import/order, max-lines -- generated: one import per icon, sorted by name */
import type { LucideIcon } from 'lucide-react-native';

import Activity from 'lucide-react-native/dist/esm/icons/activity.js';
import AlarmClock from 'lucide-react-native/dist/esm/icons/alarm-clock.js';
import AppWindow from 'lucide-react-native/dist/esm/icons/app-window.js';
import Archive from 'lucide-react-native/dist/esm/icons/archive.js';
import ArrowDown from 'lucide-react-native/dist/esm/icons/arrow-down.js';
import ArrowLeft from 'lucide-react-native/dist/esm/icons/arrow-left.js';
import ArrowRight from 'lucide-react-native/dist/esm/icons/arrow-right.js';
import ArrowRightLeft from 'lucide-react-native/dist/esm/icons/arrow-right-left.js';
import ArrowUp from 'lucide-react-native/dist/esm/icons/arrow-up.js';
import AtSign from 'lucide-react-native/dist/esm/icons/at-sign.js';
import AudioLines from 'lucide-react-native/dist/esm/icons/audio-lines.js';
import Award from 'lucide-react-native/dist/esm/icons/award.js';
import BadgeCheck from 'lucide-react-native/dist/esm/icons/badge-check.js';
import Ban from 'lucide-react-native/dist/esm/icons/ban.js';
import Bell from 'lucide-react-native/dist/esm/icons/bell.js';
import BellRing from 'lucide-react-native/dist/esm/icons/bell-ring.js';
import Blocks from 'lucide-react-native/dist/esm/icons/blocks.js';
import Book from 'lucide-react-native/dist/esm/icons/book.js';
import BookOpen from 'lucide-react-native/dist/esm/icons/book-open.js';
import Bookmark from 'lucide-react-native/dist/esm/icons/bookmark.js';
import Bot from 'lucide-react-native/dist/esm/icons/bot.js';
import Box from 'lucide-react-native/dist/esm/icons/box.js';
import Boxes from 'lucide-react-native/dist/esm/icons/boxes.js';
import Braces from 'lucide-react-native/dist/esm/icons/braces.js';
import Brain from 'lucide-react-native/dist/esm/icons/brain.js';
import Briefcase from 'lucide-react-native/dist/esm/icons/briefcase.js';
import Bug from 'lucide-react-native/dist/esm/icons/bug.js';
import Building2 from 'lucide-react-native/dist/esm/icons/building-2.js';
import Calculator from 'lucide-react-native/dist/esm/icons/calculator.js';
import Calendar from 'lucide-react-native/dist/esm/icons/calendar.js';
import CalendarClock from 'lucide-react-native/dist/esm/icons/calendar-clock.js';
import Camera from 'lucide-react-native/dist/esm/icons/camera.js';
import CameraOff from 'lucide-react-native/dist/esm/icons/camera-off.js';
import ChartColumn from 'lucide-react-native/dist/esm/icons/chart-column.js';
import ChartLine from 'lucide-react-native/dist/esm/icons/chart-line.js';
import ChartNoAxesColumn from 'lucide-react-native/dist/esm/icons/chart-no-axes-column.js';
import ChartPie from 'lucide-react-native/dist/esm/icons/chart-pie.js';
import Check from 'lucide-react-native/dist/esm/icons/check.js';
import ChevronDown from 'lucide-react-native/dist/esm/icons/chevron-down.js';
import ChevronRight from 'lucide-react-native/dist/esm/icons/chevron-right.js';
import ChevronUp from 'lucide-react-native/dist/esm/icons/chevron-up.js';
import ChevronsDown from 'lucide-react-native/dist/esm/icons/chevrons-down.js';
import Circle from 'lucide-react-native/dist/esm/icons/circle.js';
import CircleAlert from 'lucide-react-native/dist/esm/icons/circle-alert.js';
import CircleCheck from 'lucide-react-native/dist/esm/icons/circle-check.js';
import CircleCheckBig from 'lucide-react-native/dist/esm/icons/circle-check-big.js';
import CircleDollarSign from 'lucide-react-native/dist/esm/icons/circle-dollar-sign.js';
import CircleMinus from 'lucide-react-native/dist/esm/icons/circle-minus.js';
import CircleQuestionMark from 'lucide-react-native/dist/esm/icons/circle-question-mark.js';
import CircleX from 'lucide-react-native/dist/esm/icons/circle-x.js';
import Clapperboard from 'lucide-react-native/dist/esm/icons/clapperboard.js';
import Clipboard from 'lucide-react-native/dist/esm/icons/clipboard.js';
import ClipboardCheck from 'lucide-react-native/dist/esm/icons/clipboard-check.js';
import ClipboardList from 'lucide-react-native/dist/esm/icons/clipboard-list.js';
import Clock from 'lucide-react-native/dist/esm/icons/clock.js';
import Cloud from 'lucide-react-native/dist/esm/icons/cloud.js';
import CloudCog from 'lucide-react-native/dist/esm/icons/cloud-cog.js';
import CloudUpload from 'lucide-react-native/dist/esm/icons/cloud-upload.js';
import Code from 'lucide-react-native/dist/esm/icons/code.js';
import CodeXml from 'lucide-react-native/dist/esm/icons/code-xml.js';
import Coffee from 'lucide-react-native/dist/esm/icons/coffee.js';
import Coins from 'lucide-react-native/dist/esm/icons/coins.js';
import Compass from 'lucide-react-native/dist/esm/icons/compass.js';
import Contact from 'lucide-react-native/dist/esm/icons/contact.js';
import Cookie from 'lucide-react-native/dist/esm/icons/cookie.js';
import Copy from 'lucide-react-native/dist/esm/icons/copy.js';
import CornerDownRight from 'lucide-react-native/dist/esm/icons/corner-down-right.js';
import CornerUpLeft from 'lucide-react-native/dist/esm/icons/corner-up-left.js';
import Cpu from 'lucide-react-native/dist/esm/icons/cpu.js';
import CreditCard from 'lucide-react-native/dist/esm/icons/credit-card.js';
import Crosshair from 'lucide-react-native/dist/esm/icons/crosshair.js';
import Crown from 'lucide-react-native/dist/esm/icons/crown.js';
import Database from 'lucide-react-native/dist/esm/icons/database.js';
import DatabaseZap from 'lucide-react-native/dist/esm/icons/database-zap.js';
import Dna from 'lucide-react-native/dist/esm/icons/dna.js';
import DollarSign from 'lucide-react-native/dist/esm/icons/dollar-sign.js';
import Download from 'lucide-react-native/dist/esm/icons/download.js';
import Droplet from 'lucide-react-native/dist/esm/icons/droplet.js';
import Earth from 'lucide-react-native/dist/esm/icons/earth.js';
import Ellipsis from 'lucide-react-native/dist/esm/icons/ellipsis.js';
import EllipsisVertical from 'lucide-react-native/dist/esm/icons/ellipsis-vertical.js';
import Eraser from 'lucide-react-native/dist/esm/icons/eraser.js';
import ExternalLink from 'lucide-react-native/dist/esm/icons/external-link.js';
import Eye from 'lucide-react-native/dist/esm/icons/eye.js';
import EyeOff from 'lucide-react-native/dist/esm/icons/eye-off.js';
import FastForward from 'lucide-react-native/dist/esm/icons/fast-forward.js';
import File from 'lucide-react-native/dist/esm/icons/file.js';
import FileBraces from 'lucide-react-native/dist/esm/icons/file-braces.js';
import FileCheck from 'lucide-react-native/dist/esm/icons/file-check.js';
import FileDown from 'lucide-react-native/dist/esm/icons/file-down.js';
import FileExclamationPoint from 'lucide-react-native/dist/esm/icons/file-exclamation-point.js';
import FileHeadphone from 'lucide-react-native/dist/esm/icons/file-headphone.js';
import FilePen from 'lucide-react-native/dist/esm/icons/file-pen.js';
import FilePenLine from 'lucide-react-native/dist/esm/icons/file-pen-line.js';
import FilePlus from 'lucide-react-native/dist/esm/icons/file-plus.js';
import FileSearch from 'lucide-react-native/dist/esm/icons/file-search.js';
import FileText from 'lucide-react-native/dist/esm/icons/file-text.js';
import FileUp from 'lucide-react-native/dist/esm/icons/file-up.js';
import Files from 'lucide-react-native/dist/esm/icons/files.js';
import FingerprintPattern from 'lucide-react-native/dist/esm/icons/fingerprint-pattern.js';
import Flag from 'lucide-react-native/dist/esm/icons/flag.js';
import FlaskConical from 'lucide-react-native/dist/esm/icons/flask-conical.js';
import Folder from 'lucide-react-native/dist/esm/icons/folder.js';
import FolderGit2 from 'lucide-react-native/dist/esm/icons/folder-git-2.js';
import FolderOpen from 'lucide-react-native/dist/esm/icons/folder-open.js';
import FolderSync from 'lucide-react-native/dist/esm/icons/folder-sync.js';
import Funnel from 'lucide-react-native/dist/esm/icons/funnel.js';
import Gauge from 'lucide-react-native/dist/esm/icons/gauge.js';
import Gavel from 'lucide-react-native/dist/esm/icons/gavel.js';
import Gift from 'lucide-react-native/dist/esm/icons/gift.js';
import GitBranch from 'lucide-react-native/dist/esm/icons/git-branch.js';
import GitCommitHorizontal from 'lucide-react-native/dist/esm/icons/git-commit-horizontal.js';
import GitCompare from 'lucide-react-native/dist/esm/icons/git-compare.js';
import GitFork from 'lucide-react-native/dist/esm/icons/git-fork.js';
import Github from 'lucide-react-native/dist/esm/icons/github.js';
import Globe from 'lucide-react-native/dist/esm/icons/globe.js';
import GraduationCap from 'lucide-react-native/dist/esm/icons/graduation-cap.js';
import GripVertical from 'lucide-react-native/dist/esm/icons/grip-vertical.js';
import Handshake from 'lucide-react-native/dist/esm/icons/handshake.js';
import HardDrive from 'lucide-react-native/dist/esm/icons/hard-drive.js';
import Hash from 'lucide-react-native/dist/esm/icons/hash.js';
import Heart from 'lucide-react-native/dist/esm/icons/heart.js';
import Hexagon from 'lucide-react-native/dist/esm/icons/hexagon.js';
import History from 'lucide-react-native/dist/esm/icons/history.js';
import Hourglass from 'lucide-react-native/dist/esm/icons/hourglass.js';
import House from 'lucide-react-native/dist/esm/icons/house.js';
import Image from 'lucide-react-native/dist/esm/icons/image.js';
import ImagePlus from 'lucide-react-native/dist/esm/icons/image-plus.js';
import Import from 'lucide-react-native/dist/esm/icons/import.js';
import Inbox from 'lucide-react-native/dist/esm/icons/inbox.js';
import Info from 'lucide-react-native/dist/esm/icons/info.js';
import Kanban from 'lucide-react-native/dist/esm/icons/kanban.js';
import Key from 'lucide-react-native/dist/esm/icons/key.js';
import KeyRound from 'lucide-react-native/dist/esm/icons/key-round.js';
import KeySquare from 'lucide-react-native/dist/esm/icons/key-square.js';
import Landmark from 'lucide-react-native/dist/esm/icons/landmark.js';
import Languages from 'lucide-react-native/dist/esm/icons/languages.js';
import Layers from 'lucide-react-native/dist/esm/icons/layers.js';
import LayoutGrid from 'lucide-react-native/dist/esm/icons/layout-grid.js';
import LayoutPanelLeft from 'lucide-react-native/dist/esm/icons/layout-panel-left.js';
import LayoutTemplate from 'lucide-react-native/dist/esm/icons/layout-template.js';
import Library from 'lucide-react-native/dist/esm/icons/library.js';
import LifeBuoy from 'lucide-react-native/dist/esm/icons/life-buoy.js';
import Lightbulb from 'lucide-react-native/dist/esm/icons/lightbulb.js';
import Link from 'lucide-react-native/dist/esm/icons/link.js';
import Link2 from 'lucide-react-native/dist/esm/icons/link-2.js';
import Linkedin from 'lucide-react-native/dist/esm/icons/linkedin.js';
import List from 'lucide-react-native/dist/esm/icons/list.js';
import ListChecks from 'lucide-react-native/dist/esm/icons/list-checks.js';
import ListFilter from 'lucide-react-native/dist/esm/icons/list-filter.js';
import ListOrdered from 'lucide-react-native/dist/esm/icons/list-ordered.js';
import Loader from 'lucide-react-native/dist/esm/icons/loader.js';
import LoaderCircle from 'lucide-react-native/dist/esm/icons/loader-circle.js';
import Lock from 'lucide-react-native/dist/esm/icons/lock.js';
import LockOpen from 'lucide-react-native/dist/esm/icons/lock-open.js';
import LogIn from 'lucide-react-native/dist/esm/icons/log-in.js';
import LogOut from 'lucide-react-native/dist/esm/icons/log-out.js';
import Mail from 'lucide-react-native/dist/esm/icons/mail.js';
import Map from 'lucide-react-native/dist/esm/icons/map.js';
import MapPin from 'lucide-react-native/dist/esm/icons/map-pin.js';
import Maximize2 from 'lucide-react-native/dist/esm/icons/maximize-2.js';
import Megaphone from 'lucide-react-native/dist/esm/icons/megaphone.js';
import Menu from 'lucide-react-native/dist/esm/icons/menu.js';
import MessageCircle from 'lucide-react-native/dist/esm/icons/message-circle.js';
import MessageCircleQuestionMark from 'lucide-react-native/dist/esm/icons/message-circle-question-mark.js';
import MessageSquare from 'lucide-react-native/dist/esm/icons/message-square.js';
import MessageSquareQuote from 'lucide-react-native/dist/esm/icons/message-square-quote.js';
import MessagesSquare from 'lucide-react-native/dist/esm/icons/messages-square.js';
import Mic from 'lucide-react-native/dist/esm/icons/mic.js';
import MicOff from 'lucide-react-native/dist/esm/icons/mic-off.js';
import Milestone from 'lucide-react-native/dist/esm/icons/milestone.js';
import Minus from 'lucide-react-native/dist/esm/icons/minus.js';
import Monitor from 'lucide-react-native/dist/esm/icons/monitor.js';
import MonitorPlay from 'lucide-react-native/dist/esm/icons/monitor-play.js';
import MousePointer2 from 'lucide-react-native/dist/esm/icons/mouse-pointer-2.js';
import MousePointerClick from 'lucide-react-native/dist/esm/icons/mouse-pointer-click.js';
import Network from 'lucide-react-native/dist/esm/icons/network.js';
import Newspaper from 'lucide-react-native/dist/esm/icons/newspaper.js';
import NotebookPen from 'lucide-react-native/dist/esm/icons/notebook-pen.js';
import OctagonAlert from 'lucide-react-native/dist/esm/icons/octagon-alert.js';
import OctagonX from 'lucide-react-native/dist/esm/icons/octagon-x.js';
import Package from 'lucide-react-native/dist/esm/icons/package.js';
import Palette from 'lucide-react-native/dist/esm/icons/palette.js';
import PanelsTopLeft from 'lucide-react-native/dist/esm/icons/panels-top-left.js';
import Paperclip from 'lucide-react-native/dist/esm/icons/paperclip.js';
import Pause from 'lucide-react-native/dist/esm/icons/pause.js';
import Pen from 'lucide-react-native/dist/esm/icons/pen.js';
import PenLine from 'lucide-react-native/dist/esm/icons/pen-line.js';
import PenTool from 'lucide-react-native/dist/esm/icons/pen-tool.js';
import Pencil from 'lucide-react-native/dist/esm/icons/pencil.js';
import Phone from 'lucide-react-native/dist/esm/icons/phone.js';
import PhoneCall from 'lucide-react-native/dist/esm/icons/phone-call.js';
import PhoneOff from 'lucide-react-native/dist/esm/icons/phone-off.js';
import Pin from 'lucide-react-native/dist/esm/icons/pin.js';
import PinOff from 'lucide-react-native/dist/esm/icons/pin-off.js';
import Play from 'lucide-react-native/dist/esm/icons/play.js';
import Plug from 'lucide-react-native/dist/esm/icons/plug.js';
import Plus from 'lucide-react-native/dist/esm/icons/plus.js';
import Power from 'lucide-react-native/dist/esm/icons/power.js';
import Presentation from 'lucide-react-native/dist/esm/icons/presentation.js';
import Printer from 'lucide-react-native/dist/esm/icons/printer.js';
import Puzzle from 'lucide-react-native/dist/esm/icons/puzzle.js';
import QrCode from 'lucide-react-native/dist/esm/icons/qr-code.js';
import Quote from 'lucide-react-native/dist/esm/icons/quote.js';
import Receipt from 'lucide-react-native/dist/esm/icons/receipt.js';
import RectangleHorizontal from 'lucide-react-native/dist/esm/icons/rectangle-horizontal.js';
import Redo2 from 'lucide-react-native/dist/esm/icons/redo-2.js';
import RefreshCw from 'lucide-react-native/dist/esm/icons/refresh-cw.js';
import Repeat from 'lucide-react-native/dist/esm/icons/repeat.js';
import Rocket from 'lucide-react-native/dist/esm/icons/rocket.js';
import RotateCcw from 'lucide-react-native/dist/esm/icons/rotate-ccw.js';
import RotateCw from 'lucide-react-native/dist/esm/icons/rotate-cw.js';
import Rows3 from 'lucide-react-native/dist/esm/icons/rows-3.js';
import Rss from 'lucide-react-native/dist/esm/icons/rss.js';
import Save from 'lucide-react-native/dist/esm/icons/save.js';
import Scale from 'lucide-react-native/dist/esm/icons/scale.js';
import ScanText from 'lucide-react-native/dist/esm/icons/scan-text.js';
import ScrollText from 'lucide-react-native/dist/esm/icons/scroll-text.js';
import Search from 'lucide-react-native/dist/esm/icons/search.js';
import Send from 'lucide-react-native/dist/esm/icons/send.js';
import Server from 'lucide-react-native/dist/esm/icons/server.js';
import ServerCog from 'lucide-react-native/dist/esm/icons/server-cog.js';
import Settings from 'lucide-react-native/dist/esm/icons/settings.js';
import Settings2 from 'lucide-react-native/dist/esm/icons/settings-2.js';
import Share2 from 'lucide-react-native/dist/esm/icons/share-2.js';
import Shield from 'lucide-react-native/dist/esm/icons/shield.js';
import ShieldAlert from 'lucide-react-native/dist/esm/icons/shield-alert.js';
import ShieldCheck from 'lucide-react-native/dist/esm/icons/shield-check.js';
import ShieldOff from 'lucide-react-native/dist/esm/icons/shield-off.js';
import ShieldQuestionMark from 'lucide-react-native/dist/esm/icons/shield-question-mark.js';
import ShoppingCart from 'lucide-react-native/dist/esm/icons/shopping-cart.js';
import Shuffle from 'lucide-react-native/dist/esm/icons/shuffle.js';
import Sigma from 'lucide-react-native/dist/esm/icons/sigma.js';
import Siren from 'lucide-react-native/dist/esm/icons/siren.js';
import SlidersVertical from 'lucide-react-native/dist/esm/icons/sliders-vertical.js';
import Smartphone from 'lucide-react-native/dist/esm/icons/smartphone.js';
import Sparkles from 'lucide-react-native/dist/esm/icons/sparkles.js';
import Split from 'lucide-react-native/dist/esm/icons/split.js';
import Square from 'lucide-react-native/dist/esm/icons/square.js';
import SquareCheckBig from 'lucide-react-native/dist/esm/icons/square-check-big.js';
import SquarePen from 'lucide-react-native/dist/esm/icons/square-pen.js';
import SquareStack from 'lucide-react-native/dist/esm/icons/square-stack.js';
import SquareTerminal from 'lucide-react-native/dist/esm/icons/square-terminal.js';
import Star from 'lucide-react-native/dist/esm/icons/star.js';
import Stethoscope from 'lucide-react-native/dist/esm/icons/stethoscope.js';
import StickyNote from 'lucide-react-native/dist/esm/icons/sticky-note.js';
import Store from 'lucide-react-native/dist/esm/icons/store.js';
import SwatchBook from 'lucide-react-native/dist/esm/icons/swatch-book.js';
import Table from 'lucide-react-native/dist/esm/icons/table.js';
import Table2 from 'lucide-react-native/dist/esm/icons/table-2.js';
import Tag from 'lucide-react-native/dist/esm/icons/tag.js';
import Tags from 'lucide-react-native/dist/esm/icons/tags.js';
import Target from 'lucide-react-native/dist/esm/icons/target.js';
import Terminal from 'lucide-react-native/dist/esm/icons/terminal.js';
import TestTube from 'lucide-react-native/dist/esm/icons/test-tube.js';
import TextAlignStart from 'lucide-react-native/dist/esm/icons/text-align-start.js';
import ThumbsDown from 'lucide-react-native/dist/esm/icons/thumbs-down.js';
import ThumbsUp from 'lucide-react-native/dist/esm/icons/thumbs-up.js';
import Ticket from 'lucide-react-native/dist/esm/icons/ticket.js';
import Timer from 'lucide-react-native/dist/esm/icons/timer.js';
import Trash2 from 'lucide-react-native/dist/esm/icons/trash-2.js';
import TrendingUp from 'lucide-react-native/dist/esm/icons/trending-up.js';
import TriangleAlert from 'lucide-react-native/dist/esm/icons/triangle-alert.js';
import Truck from 'lucide-react-native/dist/esm/icons/truck.js';
import Type from 'lucide-react-native/dist/esm/icons/type.js';
import Undo2 from 'lucide-react-native/dist/esm/icons/undo-2.js';
import Unlink from 'lucide-react-native/dist/esm/icons/unlink.js';
import Unplug from 'lucide-react-native/dist/esm/icons/unplug.js';
import Upload from 'lucide-react-native/dist/esm/icons/upload.js';
import User from 'lucide-react-native/dist/esm/icons/user.js';
import UserCheck from 'lucide-react-native/dist/esm/icons/user-check.js';
import UserMinus from 'lucide-react-native/dist/esm/icons/user-minus.js';
import UserPlus from 'lucide-react-native/dist/esm/icons/user-plus.js';
import UserX from 'lucide-react-native/dist/esm/icons/user-x.js';
import Users from 'lucide-react-native/dist/esm/icons/users.js';
import VenetianMask from 'lucide-react-native/dist/esm/icons/venetian-mask.js';
import Video from 'lucide-react-native/dist/esm/icons/video.js';
import Volume2 from 'lucide-react-native/dist/esm/icons/volume-2.js';
import Wallet from 'lucide-react-native/dist/esm/icons/wallet.js';
import WandSparkles from 'lucide-react-native/dist/esm/icons/wand-sparkles.js';
import Webhook from 'lucide-react-native/dist/esm/icons/webhook.js';
import Wifi from 'lucide-react-native/dist/esm/icons/wifi.js';
import WifiOff from 'lucide-react-native/dist/esm/icons/wifi-off.js';
import Workflow from 'lucide-react-native/dist/esm/icons/workflow.js';
import Wrench from 'lucide-react-native/dist/esm/icons/wrench.js';
import X from 'lucide-react-native/dist/esm/icons/x.js';
import Zap from 'lucide-react-native/dist/esm/icons/zap.js';

export const ICON_REGISTRY = {
    Activity,
    AlarmClock,
    AlertTriangle: TriangleAlert,
    AppWindow,
    Archive,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowRightLeft,
    ArrowUp,
    AtSign,
    AudioLines,
    Award,
    BadgeCheck,
    Ban,
    BarChart3: ChartColumn,
    Bell,
    BellRing,
    Blocks,
    Book,
    BookOpen,
    Bookmark,
    Bot,
    Box,
    Boxes,
    Braces,
    Brain,
    Briefcase,
    Bug,
    Building2,
    Calculator,
    Calendar,
    CalendarClock,
    Camera,
    CameraOff,
    ChartLine,
    ChartNoAxesColumn,
    ChartPie,
    Check,
    CheckCircle: CircleCheckBig,
    CheckCircle2: CircleCheck,
    CheckSquare: SquareCheckBig,
    ChevronDown,
    ChevronRight,
    ChevronUp,
    ChevronsDown,
    Circle,
    CircleAlert,
    CircleCheck,
    CircleCheckBig,
    CircleDollarSign,
    CircleMinus,
    CircleQuestionMark,
    CircleX,
    Clapperboard,
    Clipboard,
    ClipboardCheck,
    ClipboardList,
    Clock,
    Cloud,
    CloudCog,
    CloudUpload,
    Code,
    Code2: CodeXml,
    Coffee,
    Coins,
    Compass,
    Contact,
    Cookie,
    Copy,
    CornerDownRight,
    CornerUpLeft,
    Cpu,
    CreditCard,
    Crosshair,
    Crown,
    Database,
    DatabaseZap,
    Dna,
    DollarSign,
    Download,
    Droplet,
    Ellipsis,
    EllipsisVertical,
    Eraser,
    ExternalLink,
    Eye,
    EyeOff,
    FastForward,
    File,
    FileAudio: FileHeadphone,
    FileCheck,
    FileDown,
    FileJson: FileBraces,
    FilePen,
    FilePenLine,
    FilePlus,
    FileSearch,
    FileSignature: FilePenLine,
    FileText,
    FileUp,
    FileWarning: FileExclamationPoint,
    Files,
    Filter: Funnel,
    FingerprintPattern,
    Flag,
    FlaskConical,
    Folder,
    FolderGit2,
    FolderOpen,
    FolderSync,
    Funnel,
    Gauge,
    Gavel,
    Gift,
    GitBranch,
    GitCommitHorizontal,
    GitCompare,
    GitFork,
    Github,
    Globe,
    Globe2: Earth,
    GraduationCap,
    GripVertical,
    Handshake,
    HardDrive,
    Hash,
    Heart,
    HelpCircle: CircleQuestionMark,
    Hexagon,
    History,
    Home: House,
    Hourglass,
    House,
    Image,
    ImagePlus,
    Import,
    Inbox,
    Info,
    Kanban,
    Key,
    KeyRound,
    KeySquare,
    Landmark,
    Languages,
    Layers,
    LayoutGrid,
    LayoutPanelLeft,
    LayoutTemplate,
    Library,
    LifeBuoy,
    Lightbulb,
    Link,
    Link2,
    Linkedin,
    List,
    ListChecks,
    ListFilter,
    ListOrdered,
    Loader,
    LoaderCircle,
    Lock,
    LockOpen,
    LogIn,
    LogOut,
    Mail,
    Map,
    MapPin,
    Maximize2,
    Megaphone,
    Menu,
    MessageCircle,
    MessageCircleQuestion: MessageCircleQuestionMark,
    MessageSquare,
    MessageSquareQuote,
    MessagesSquare,
    Mic,
    MicOff,
    Milestone,
    Minus,
    Monitor,
    MonitorPlay,
    MoreHorizontal: Ellipsis,
    MoreVertical: EllipsisVertical,
    MousePointer2,
    MousePointerClick,
    Network,
    Newspaper,
    NotebookPen,
    OctagonAlert,
    OctagonX,
    Package,
    Palette,
    PanelsTopLeft,
    Paperclip,
    Pause,
    Pen,
    PenLine,
    PenTool,
    Pencil,
    Phone,
    PhoneCall,
    PhoneOff,
    PieChart: ChartPie,
    Pin,
    PinOff,
    Play,
    Plug,
    Plus,
    Power,
    Presentation,
    Printer,
    Puzzle,
    QrCode,
    Quote,
    Receipt,
    RectangleHorizontal,
    Redo2,
    RefreshCw,
    Repeat,
    Rocket,
    RotateCcw,
    RotateCw,
    Rows3,
    Rss,
    Save,
    Scale,
    ScanText,
    ScrollText,
    Search,
    Send,
    Server,
    ServerCog,
    Settings,
    Settings2,
    Share2,
    Shield,
    ShieldAlert,
    ShieldCheck,
    ShieldOff,
    ShieldQuestionMark,
    ShoppingCart,
    Shuffle,
    Sigma,
    Siren,
    SlidersVertical,
    Smartphone,
    Sparkles,
    Split,
    Square,
    SquareCheckBig,
    SquarePen,
    SquareStack,
    Star,
    Stethoscope,
    StickyNote,
    Store,
    SwatchBook,
    Table,
    Table2,
    Tag,
    Tags,
    Target,
    Terminal,
    TerminalSquare: SquareTerminal,
    TestTube,
    TextAlignStart,
    ThumbsDown,
    ThumbsUp,
    Ticket,
    Timer,
    Trash2,
    TrendingUp,
    TriangleAlert,
    Truck,
    Type,
    Undo2,
    Unlink,
    Unplug,
    Upload,
    User,
    UserCheck,
    UserMinus,
    UserPlus,
    UserX,
    Users,
    VenetianMask,
    Video,
    Volume2,
    Wallet,
    Wand2: WandSparkles,
    Webhook,
    Wifi,
    WifiOff,
    Workflow,
    Wrench,
    X,
    Zap,
} satisfies Record<string, LucideIcon>;

/** A name <Icon> and <AppIcon> can draw. */
export type IconName = keyof typeof ICON_REGISTRY;

/** The web's ICON_REGISTRY names (agent-hub/src/components/icons/iconRegistry.js). */
export const WEB_ICON_NAMES = [
    'AppWindow',
    'ArrowRight',
    'AudioLines',
    'Ban',
    'BarChart3',
    'Bell',
    'Blocks',
    'BookOpen',
    'Bot',
    'Boxes',
    'Brain',
    'Bug',
    'Building2',
    'Calendar',
    'CalendarClock',
    'Check',
    'CheckSquare',
    'ChevronDown',
    'ChevronRight',
    'ClipboardCheck',
    'Clock',
    'Cloud',
    'Code',
    'Coins',
    'Cookie',
    'Copy',
    'Cpu',
    'CreditCard',
    'Crosshair',
    'Database',
    'Download',
    'ExternalLink',
    'EyeOff',
    'FileAudio',
    'FileCheck',
    'FileDown',
    'FileJson',
    'FileSearch',
    'FileText',
    'FileWarning',
    'Flag',
    'FlaskConical',
    'Folder',
    'FolderOpen',
    'FolderSync',
    'Gauge',
    'Gavel',
    'Gift',
    'GitBranch',
    'GitCompare',
    'Github',
    'Globe',
    'Globe2',
    'GripVertical',
    'HardDrive',
    'HelpCircle',
    'Home',
    'Image',
    'Import',
    'Kanban',
    'KeyRound',
    'Landmark',
    'Languages',
    'Layers',
    'LayoutGrid',
    'LayoutPanelLeft',
    'LayoutTemplate',
    'Library',
    'LifeBuoy',
    'Linkedin',
    'ListChecks',
    'ListOrdered',
    'Lock',
    'Mail',
    'Map',
    'MapPin',
    'Megaphone',
    'MessageCircleQuestion',
    'MessageSquare',
    'MessageSquareQuote',
    'MessagesSquare',
    'Mic',
    'Milestone',
    'Monitor',
    'MonitorPlay',
    'MoreHorizontal',
    'MoreVertical',
    'MousePointerClick',
    'Newspaper',
    'NotebookPen',
    'Palette',
    'PenLine',
    'PenTool',
    'Plug',
    'Plus',
    'Presentation',
    'Puzzle',
    'Quote',
    'RefreshCw',
    'Repeat',
    'Rocket',
    'RotateCcw',
    'RotateCw',
    'Scale',
    'ScrollText',
    'Search',
    'Send',
    'Server',
    'ServerCog',
    'Settings',
    'Settings2',
    'Share2',
    'Shield',
    'ShieldAlert',
    'ShieldCheck',
    'Sparkles',
    'Square',
    'Star',
    'Stethoscope',
    'Store',
    'Table',
    'Target',
    'TerminalSquare',
    'TestTube',
    'Ticket',
    'Trash2',
    'Type',
    'Upload',
    'UserCheck',
    'Users',
    'Video',
    'Wand2',
    'WifiOff',
    'Workflow',
    'Wrench',
    'X',
    'Zap',
] as const satisfies readonly IconName[];

/** The web's FALLBACK_ICON: what an unknown name draws. */
export const WEB_FALLBACK_ICON: IconName = 'HelpCircle';
