/**
 * Envelope encryption — a byte-for-byte port of agent-hub/src/lib/opaque.js's
 * key handling.
 *
 * The shape of Bee Flow's zero-knowledge story:
 *
 *   password --OPAQUE--> exportKey --HKDF--> KEK --AES-GCM--> unwraps DEK
 *
 * The server stores only the WRAPPED DEK (`wrappedDEK`, returned by
 * /auth/opaque/login/start) and never sees the KEK. A second client — this app
 * — can therefore decrypt the same vault with nothing but the user's password,
 * which is the entire reason a native mobile client is possible at all.
 *
 * Every parameter below is load-bearing for interop with the web app: the HKDF
 * salt and info strings, SHA-256 (not 512 — the OPAQUE half uses 512, this
 * half does not), the 12-byte IV, the 16-byte tag, the hex encoding of the
 * three envelope fields, and the AAD context strings including the username.
 * Change any of them and the phone silently fails to open a vault the browser
 * opens fine. keys.test.ts pins them against fixtures generated by the web
 * implementation.
 *
 * WebCrypto does not exist on Hermes, so the primitives come from @noble:
 * audited, pure JS, no native module and no WASM.
 */

import { gcm } from '@noble/ciphers/aes.js';
import { hkdf } from '@noble/hashes/hkdf.js';
import { sha256 } from '@noble/hashes/sha2.js';

import { randomBytes } from './random';

/** The three-field envelope the server persists. All values are lowercase hex. */
export interface WrappedKey {
    iv: string;
    authTag: string;
    data: string;
}

const KEK_SALT = 'beeflow:opaque:kek:v1';
const KEK_INFO = 'beeflow:opaque:kek-derive';
const IV_BYTES = 12;
const TAG_BYTES = 16;
const KEY_BYTES = 32;

const encoder = new TextEncoder();

export function toHex(bytes: Uint8Array): string {
    let out = '';
    for (const b of bytes) out += b.toString(16).padStart(2, '0');
    return out;
}

export function fromHex(hex: string): Uint8Array {
    if (hex.length % 2 !== 0) throw new Error('Malformed hex: odd length');
    const out = new Uint8Array(hex.length / 2);
    for (let i = 0; i < out.length; i++) {
        const byte = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
        if (Number.isNaN(byte)) throw new Error('Malformed hex: non-hex character');
        out[i] = byte;
    }
    return out;
}

/** Base64 without relying on atob/btoa, which Hermes does not provide. */
export function toBase64(bytes: Uint8Array): string {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    let out = '';
    for (let i = 0; i < bytes.length; i += 3) {
        const a = bytes[i] as number;
        const b = i + 1 < bytes.length ? (bytes[i + 1] as number) : undefined;
        const c = i + 2 < bytes.length ? (bytes[i + 2] as number) : undefined;
        out += alphabet[a >> 2];
        out += alphabet[((a & 3) << 4) | ((b ?? 0) >> 4)];
        out += b === undefined ? '=' : alphabet[((b & 15) << 2) | ((c ?? 0) >> 6)];
        out += c === undefined ? '=' : alphabet[c & 63];
    }
    return out;
}

/**
 * Decode base64, accepting BOTH alphabets.
 *
 * This is load-bearing, not politeness. The two producers whose output lands
 * here disagree: the server's `wrappedDEK` and the web app's values are
 * standard base64 (the browser's `btoa`), while src/crypto/opaque emits
 * base64url without padding because that is the only dialect opaque-ke
 * accepts. `deriveKEK(exportKey)` and `encryptDEKForServer(dek, sessionKey)`
 * are both handed OPAQUE output, so a standard-only decoder here rejects a `-`
 * or `_` — which, for 64 random bytes, is very nearly every sign-in.
 *
 * `toBase64` deliberately stays standard-only: its output goes to the server,
 * which decodes what the browser produced.
 */
export function fromBase64(value: string): Uint8Array {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    const clean = value.replace(/=+$/, '').replace(/-/g, '+').replace(/_/g, '/');
    const out = new Uint8Array(Math.floor((clean.length * 3) / 4));
    let bits = 0;
    let acc = 0;
    let o = 0;
    for (const ch of clean) {
        const v = alphabet.indexOf(ch);
        if (v === -1) throw new Error('Malformed base64');
        acc = (acc << 6) | v;
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            out[o++] = (acc >> bits) & 0xff;
        }
    }
    return out.subarray(0, o);
}

/**
 * Derive the key-encryption key from the OPAQUE exportKey.
 *
 * The web implementation imports the exportKey as HKDF material and derives an
 * AES-256-GCM key with a FIXED salt and info. Fixed, not random: both sides
 * must arrive at the same KEK from the exportKey alone, so there is nowhere to
 * put a random salt.
 *
 * @param exportKeyB64 base64 exportKey from OPAQUE finishLogin/finishRegistration
 */
export function deriveKEK(exportKeyB64: string): Uint8Array {
    const material = fromBase64(exportKeyB64);
    return hkdf(sha256, material, encoder.encode(KEK_SALT), encoder.encode(KEK_INFO), KEY_BYTES);
}

/** A fresh 32-byte data encryption key. */
export function generateDEK(): Uint8Array {
    return randomBytes(KEY_BYTES);
}

/**
 * A recovery key: 32 random bytes, shown to the user as uppercase hex in
 * eight-character groups (`A1B2C3D4-...`). The formatting is cosmetic but must
 * match the web app exactly — a user reads it off one screen and types it into
 * the other.
 */
export function generateRecoveryKey(): { raw: Uint8Array; formatted: string } {
    const raw = randomBytes(KEY_BYTES);
    const hex = toHex(raw);
    const groups = hex.match(/.{8}/g);
    if (!groups) throw new Error('Recovery key generation produced an unexpected length');
    return { raw, formatted: groups.join('-').toUpperCase() };
}

/** Parse a recovery key the user typed, tolerating case, spaces and dashes. */
export function parseRecoveryKey(input: string): Uint8Array {
    const hex = input.trim().toLowerCase().replace(/[\s-]/g, '');
    if (!/^[0-9a-f]{64}$/.test(hex)) {
        throw new Error('That does not look like a recovery key.');
    }
    return fromHex(hex);
}

/**
 * Wrap a DEK under a 32-byte key.
 *
 * WebCrypto appends the 16-byte GCM tag to the ciphertext and the web code
 * splits it back out to fill `authTag`; @noble/ciphers does the same, so the
 * split is identical here. The `context` string is the AAD and is part of the
 * contract — `dek-wrap:<username>` for the password envelope,
 * `recovery-wrap:<username>` for the recovery one, `dek-wrap:sso-pin` for the
 * SSO PIN. Get it wrong and decryption fails with no useful error.
 */
export function wrapDEK(dek: Uint8Array, key: Uint8Array, context: string): WrappedKey {
    const iv = randomBytes(IV_BYTES);
    const aad = encoder.encode(context);
    const sealed = gcm(key, iv, aad).encrypt(dek);
    const split = sealed.length - TAG_BYTES;
    return {
        iv: toHex(iv),
        authTag: toHex(sealed.subarray(split)),
        data: toHex(sealed.subarray(0, split)),
    };
}

/**
 * Unwrap a DEK. Throws when the tag does not verify — which is the correct and
 * only signal for "wrong password", and must never be caught and turned into a
 * partial result.
 */
export function unwrapDEK(wrapped: WrappedKey, key: Uint8Array, context: string): Uint8Array {
    const iv = fromHex(wrapped.iv);
    const data = fromHex(wrapped.data);
    const tag = fromHex(wrapped.authTag);
    if (iv.length !== IV_BYTES) throw new Error('Malformed envelope: bad IV length');
    if (tag.length !== TAG_BYTES) throw new Error('Malformed envelope: bad tag length');

    const combined = new Uint8Array(data.length + tag.length);
    combined.set(data);
    combined.set(tag, data.length);
    return gcm(key, iv, encoder.encode(context)).decrypt(combined);
}

/**
 * Encrypt the DEK for the server under the OPAQUE session key ("Option B" in
 * the web implementation's comments — the server needs the DEK in memory to
 * run AI over the user's data for the life of the session).
 *
 * Two details are easy to get wrong and both are load-bearing:
 *   - the session key is truncated to its first 32 bytes (it is 64);
 *   - the plaintext is the DEK **base64-encoded, then UTF-8 bytes** — not the
 *     raw DEK. The web code does `btoa(String.fromCharCode(...dek))` before
 *     encrypting, and the server decodes accordingly.
 * There is no AAD on this one.
 */
export function encryptDEKForServer(dek: Uint8Array, sessionKeyB64: string): WrappedKey {
    const sessionKey = fromBase64(sessionKeyB64).subarray(0, KEY_BYTES);
    const iv = randomBytes(IV_BYTES);
    const plaintext = encoder.encode(toBase64(dek));
    const sealed = gcm(sessionKey, iv).encrypt(plaintext);
    const split = sealed.length - TAG_BYTES;
    return {
        iv: toHex(iv),
        authTag: toHex(sealed.subarray(split)),
        data: toHex(sealed.subarray(0, split)),
    };
}

/**
 * Best-effort scrub of key material.
 *
 * JavaScript gives no guarantee here — the engine may have copied the bytes
 * during a GC compaction, and a `string` (which is where base64 key material
 * inevitably ends up) cannot be overwritten at all. This zeroes what CAN be
 * zeroed, which is the long-lived Uint8Array buffers, and is not a claim that
 * the key is gone from RAM.
 */
export function scrub(...buffers: (Uint8Array | null | undefined)[]): void {
    for (const buf of buffers) buf?.fill(0);
}
