/**
 * SBOM locator — candidate order, format detection and the never-throw
 * contract, against fixtures in a temp dir.
 *
 * Run: cd server && node --test --test-force-exit compliance/lib/sbomLocator.test.js
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');

const locator = require('./sbomLocator');

let dir;
test.before(() => { dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sbom-locator-')); });
test.after(() => { fs.rmSync(dir, { recursive: true, force: true }); });

function write(name, content) {
    const p = path.join(dir, name);
    fs.writeFileSync(p, typeof content === 'string' ? content : JSON.stringify(content));
    return p;
}

const CDX = (extra = {}) => ({
    bomFormat: 'CycloneDX',
    specVersion: '1.5',
    metadata: {
        timestamp: '2026-09-14T10:00:00.000Z',
        tools: [{ vendor: 'npm', name: 'cli', version: '10.9.8' }],
        component: { name: 'server', version: '1.0.0', properties: [{ name: 'cdx:npm:package:path', value: '' }] },
        ...extra,
    },
    components: [{ name: 'express', version: '5.1.0' }, { name: 'pg', version: '8.16.0' }],
});

test('candidates(): SBOM_PATH first, then image path, repo sbom/, licences file — deduplicated', () => {
    const list = locator.candidates({ SBOM_PATH: '/srv/custom/bom.json' });
    assert.equal(list[0], path.resolve('/srv/custom/bom.json'));
    assert.equal(list[1], locator.DEFAULT_IMAGE_PATH);
    assert.equal(list[2], path.join(locator.REPO_ROOT, 'sbom', 'cyclonedx.json'));
    assert.equal(list[3], path.join(locator.REPO_ROOT, 'THIRD-PARTY-LICENSES.md'));
    assert.equal(list.length, 4);

    const noEnv = locator.candidates({});
    assert.equal(noEnv[0], locator.DEFAULT_IMAGE_PATH);
    assert.equal(noEnv.length, 3);
    // Blank SBOM_PATH is ignored, not resolved to the cwd.
    assert.deepEqual(locator.candidates({ SBOM_PATH: '   ' }), noEnv);
});

test('CycloneDX: component count, timestamp, version and the beeflow:build_sha property', async () => {
    const p = write('cdx.json', CDX({ properties: [{ name: 'beeflow:build_sha', value: 'abc123' }] }));
    const r = await locator.locate({ candidates: [p], hash: true });
    assert.equal(r.format, 'cyclonedx');
    assert.equal(r.path, p);
    assert.equal(r.parsed.component_count, 2);
    assert.equal(r.parsed.generated_at, '2026-09-14T10:00:00.000Z');
    assert.equal(r.parsed.version, '1.0.0');
    assert.equal(r.parsed.name, 'server');
    assert.equal(r.parsed.build_sha, 'abc123');
    assert.equal(r.parsed.spec_version, '1.5');
    assert.equal(r.parsed.tool, 'npm cli 10.9.8');
    assert.match(r.sha256, /^[0-9a-f]{64}$/);
    assert.deepEqual(r.tried, []);
});

test('CycloneDX: build sha is also accepted on metadata.component.properties; absent → null', async () => {
    const onComponent = CDX();
    onComponent.metadata.component.properties.push({ name: 'beeflow:build_sha', value: 'def456' });
    let r = await locator.locate({ candidates: [write('cdx-comp.json', onComponent)] });
    assert.equal(r.parsed.build_sha, 'def456');

    r = await locator.locate({ candidates: [write('cdx-nosha.json', CDX())] });
    assert.equal(r.parsed.build_sha, null);
    assert.equal(r.sha256, undefined, 'hash only computed on request');
});

test('SPDX documents are recognised as machine-readable too', async () => {
    const p = write('spdx.json', {
        spdxVersion: 'SPDX-2.3', name: 'server',
        creationInfo: { created: '2026-09-01T00:00:00Z', creators: ['Tool: npm-10.9.8'] },
        packages: [{ name: 'a' }, { name: 'b' }, { name: 'c' }],
    });
    const r = await locator.locate({ candidates: [p] });
    assert.equal(r.format, 'spdx');
    assert.equal(r.parsed.component_count, 3);
    assert.equal(r.parsed.generated_at, '2026-09-01T00:00:00.000Z');
    assert.equal(r.parsed.tool, 'npm-10.9.8');
});

test('THIRD-PARTY-LICENSES.md: generated date from the header, rows counted', async () => {
    const md = [
        '# Third-Party Licenses', '',
        'Generated by [scripts/generate-sbom.sh](scripts/generate-sbom.sh) on 2026-05-10.', '',
        '## Workspaces', '', '### server', '',
        '| Package | License | Source |', '|---|---|---|',
        '| `express@5.1.0` | MIT | https://github.com/expressjs/express |',
        '| `pg@8.16.0` | MIT | https://github.com/brianc/node-postgres |',
        '| `@anthropic-ai/sdk@0.78.0` | MIT | https://github.com/anthropics/anthropic-sdk-typescript |',
    ].join('\n');
    const r = await locator.locate({ candidates: [write('THIRD-PARTY-LICENSES.md', md)] });
    assert.equal(r.format, 'licenses-md');
    assert.equal(r.parsed.component_count, 3);
    assert.equal(r.parsed.generated_at, '2026-05-10T00:00:00.000Z');
    assert.equal(r.parsed.build_sha, null);
});

test('order matters: a missing or malformed earlier candidate is skipped and recorded, the next one wins', async () => {
    const missing = path.join(dir, 'does-not-exist.json');
    const broken = write('broken.json', '{ not json');
    const wrongJson = write('other.json', { hello: 'world' });
    const good = write('good.json', CDX());
    const r = await locator.locate({ candidates: [missing, broken, wrongJson, dir, good] });
    assert.equal(r.path, good);
    assert.deepEqual(r.tried.map(t => t.reason), [
        'not found', 'invalid json', 'json is not a CycloneDX or SPDX document', 'not a file',
    ]);
});

test('nothing found → format null, never a throw', async () => {
    const r = await locator.locate({ candidates: [path.join(dir, 'nope.json'), write('junk.txt', 'hello')] });
    assert.equal(r.format, null);
    assert.equal(r.path, null);
    assert.equal(r.parsed, null);
    assert.equal(r.tried.length, 2);
    assert.match(r.tried[1].reason, /unrecognised format/);
});

test('parseArtefact is pure and tolerant of empty input', () => {
    assert.equal(locator.parseArtefact('').format, null);
    assert.equal(locator.parseArtefact(null).format, null);
    assert.equal(locator.parseArtefact('  \n{"bomFormat":"CycloneDX","components":[]}').format, 'cyclonedx');
    assert.equal(locator.parseArtefact('  \n{"bomFormat":"CycloneDX","components":[]}').parsed.component_count, 0);
});
