/**
 * SBOM locator — finds the software bill of materials that describes the
 * RUNNING build (CRA Annex I Part II(1); PLD Art. 9 evidence).
 *
 * Search order (the first artefact that exists AND parses wins):
 *   1. process.env.SBOM_PATH              — explicit operator override
 *   2. /app/sbom/cyclonedx.json           — where the Dockerfile lands CI's artefact
 *                                           (build-push-ghcr.yml → server/sbom/ → `COPY sbom*`)
 *   3. <repoRoot>/sbom/cyclonedx.json     — local `scripts/generate-sbom.sh` output
 *   4. <repoRoot>/THIRD-PARTY-LICENSES.md — committed, human-readable fallback
 *
 * The result never throws: an unreadable or malformed candidate is recorded
 * under `tried` and the search moves on. Nothing found → `{ format: null }`.
 *
 *   locate({ candidates?, hash? }) →
 *     { path, format: 'cyclonedx'|'spdx'|'licenses-md'|null,
 *       parsed: { component_count, generated_at, version, name, build_sha, spec_version, tool } | null,
 *       size, mtime, sha256 (only with hash: true), tried: [{ path, reason }] }
 *
 * `build_sha` is read from the CycloneDX property `beeflow:build_sha` (set by
 * the CI step on `metadata.properties`; `metadata.component.properties` is
 * accepted too), so the check can prove the SBOM belongs to THIS build.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const BUILD_SHA_PROPERTY = 'beeflow:build_sha';
const DEFAULT_IMAGE_PATH = '/app/sbom/cyclonedx.json';
// server/compliance/lib → repo root is four levels up.
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
// Anything larger is not an SBOM we want to hold in memory on every sweep.
const MAX_BYTES = 64 * 1024 * 1024;

function candidates(env = process.env) {
    const list = [];
    const explicit = typeof env.SBOM_PATH === 'string' ? env.SBOM_PATH.trim() : '';
    if (explicit) list.push(path.resolve(explicit));
    list.push(DEFAULT_IMAGE_PATH);
    list.push(path.join(REPO_ROOT, 'sbom', 'cyclonedx.json'));
    list.push(path.join(REPO_ROOT, 'THIRD-PARTY-LICENSES.md'));
    return Array.from(new Set(list));
}

function _propertyValue(list, name) {
    if (!Array.isArray(list)) return null;
    const hit = list.find(p => p && p.name === name && typeof p.value === 'string' && p.value.trim());
    return hit ? hit.value.trim() : null;
}

function _isoOrNull(value) {
    if (typeof value !== 'string' || !value.trim()) return null;
    const t = Date.parse(value);
    return Number.isFinite(t) ? new Date(t).toISOString() : null;
}

function parseCycloneDx(bom) {
    if (!bom || typeof bom !== 'object' || bom.bomFormat !== 'CycloneDX') return null;
    const meta = bom.metadata && typeof bom.metadata === 'object' ? bom.metadata : {};
    const component = meta.component && typeof meta.component === 'object' ? meta.component : {};
    const tool = Array.isArray(meta.tools) ? meta.tools[0]
        : (meta.tools && Array.isArray(meta.tools.components) ? meta.tools.components[0] : null);
    return {
        component_count: Array.isArray(bom.components) ? bom.components.length : 0,
        generated_at: _isoOrNull(meta.timestamp),
        version: typeof component.version === 'string' ? component.version : null,
        name: typeof component.name === 'string' ? component.name : null,
        build_sha: _propertyValue(meta.properties, BUILD_SHA_PROPERTY)
            || _propertyValue(component.properties, BUILD_SHA_PROPERTY),
        spec_version: typeof bom.specVersion === 'string' ? bom.specVersion : null,
        tool: tool ? [tool.vendor, tool.name, tool.version].filter(Boolean).join(' ') || null : null,
    };
}

function parseSpdx(doc) {
    if (!doc || typeof doc !== 'object' || typeof doc.spdxVersion !== 'string') return null;
    const info = doc.creationInfo && typeof doc.creationInfo === 'object' ? doc.creationInfo : {};
    const creators = Array.isArray(info.creators) ? info.creators : [];
    const tool = creators.find(c => typeof c === 'string' && /^Tool:/i.test(c));
    return {
        component_count: Array.isArray(doc.packages) ? doc.packages.length : 0,
        generated_at: _isoOrNull(info.created),
        version: null,
        name: typeof doc.name === 'string' ? doc.name : null,
        build_sha: null,
        spec_version: doc.spdxVersion,
        tool: tool ? tool.replace(/^Tool:\s*/i, '') : null,
    };
}

const LICENSES_MD_TITLE = /^#\s*Third-Party Licenses/im;
const LICENSES_MD_DATE = /Generated by .*? on (\d{4}-\d{2}-\d{2})/i;
// One table row per dependency: | `name@version` | LICENSE | source |
const LICENSES_MD_ROW = /^\|\s*`[^`\n]+@[^`\n]+`\s*\|/gm;

function parseLicensesMd(text) {
    if (typeof text !== 'string' || !LICENSES_MD_TITLE.test(text)) return null;
    const date = text.match(LICENSES_MD_DATE);
    const rows = text.match(LICENSES_MD_ROW);
    return {
        component_count: rows ? rows.length : 0,
        generated_at: date ? `${date[1]}T00:00:00.000Z` : null,
        version: null,
        name: null,
        build_sha: null,
        spec_version: null,
        tool: 'scripts/generate-sbom.sh',
    };
}

/**
 * Classify + parse one artefact's text. Pure; returns
 * `{ format, parsed }` or `{ format: null, parsed: null, reason }`.
 */
function parseArtefact(text, filePath = '') {
    if (typeof text !== 'string' || !text.trim()) return { format: null, parsed: null, reason: 'empty' };
    const trimmed = text.trimStart();
    if (trimmed.startsWith('{')) {
        let json;
        try { json = JSON.parse(trimmed); } catch { return { format: null, parsed: null, reason: 'invalid json' }; }
        const cdx = parseCycloneDx(json);
        if (cdx) return { format: 'cyclonedx', parsed: cdx };
        const spdx = parseSpdx(json);
        if (spdx) return { format: 'spdx', parsed: spdx };
        return { format: null, parsed: null, reason: 'json is not a CycloneDX or SPDX document' };
    }
    const md = parseLicensesMd(text);
    if (md) return { format: 'licenses-md', parsed: md };
    return { format: null, parsed: null, reason: `unrecognised format${filePath ? ` (${path.extname(filePath) || 'no extension'})` : ''}` };
}

/**
 * Walk the candidates and return the first artefact that parses.
 * @param {{ candidates?: string[], hash?: boolean }} [opts]
 */
async function locate(opts = {}) {
    const list = Array.isArray(opts.candidates) ? opts.candidates : candidates();
    const tried = [];
    for (const p of list) {
        let stat;
        try {
            stat = await fs.promises.stat(p);
        } catch {
            tried.push({ path: p, reason: 'not found' });
            continue;
        }
        if (!stat.isFile()) { tried.push({ path: p, reason: 'not a file' }); continue; }
        if (stat.size > MAX_BYTES) { tried.push({ path: p, reason: 'too large' }); continue; }
        let text;
        try {
            text = await fs.promises.readFile(p, 'utf8');
        } catch (e) {
            tried.push({ path: p, reason: `unreadable: ${e.code || e.message}` });
            continue;
        }
        const { format, parsed, reason } = parseArtefact(text, p);
        if (!format) { tried.push({ path: p, reason }); continue; }
        const out = {
            path: p,
            format,
            parsed,
            size: stat.size,
            mtime: stat.mtime.toISOString(),
            tried,
        };
        if (opts.hash) out.sha256 = crypto.createHash('sha256').update(text).digest('hex');
        return out;
    }
    return { path: null, format: null, parsed: null, size: 0, mtime: null, tried };
}

module.exports = {
    locate,
    candidates,
    parseArtefact,
    parseCycloneDx,
    parseSpdx,
    parseLicensesMd,
    BUILD_SHA_PROPERTY,
    DEFAULT_IMAGE_PATH,
    REPO_ROOT,
};
