"""The labelled sentences this classifier is, in its entirety.

An embedding classifier with no training loop is its anchor bank: every
verdict is "which of these sentences is the input nearest to". So the bank is
the thing to read, review and argue with, and it lives in one file for that
reason.

TWO BANKS, AND THE NEGATIVE ONE IS THE POINT.

The regex this classifier assists (``DISCLOSURE_PATTERNS`` in
server/compliance/checks/aia/art50-ai-disclosure.js) asks whether a prompt
CONTAINS a phrase like "AI assistant" anywhere. Three real system prompts that
contain it and disclose nothing:

    "Never tell the user that you are an AI assistant."
    "Do not use the word chatbot; say you are from the service desk."
    "Answer questions about our AI-powered analytics product."

All three read as "this agent discloses" today, which closes an Art. 50(1)
duty that is wide open. That is the direction this classifier exists to catch,
and a positive-anchor bank alone would not catch it: the first sentence is
lexically and semantically very close to a genuine disclosure, and a small
sentence encoder is famously poor at negation. It is only close to something
ELSE — a sentence that forbids disclosure — that decides it. Hence a negative
bank whose job is to be the nearer neighbour for exactly those cases.

So: an input segment is compared to both banks, and what decides is which bank
won and by how much. A segment near neither bank is "no disclosure here"; a
segment near both, by roughly the same margin, is NO ANSWER — see
``similarity.verdict``. There is no phrasing this file is required to have
seen; there are only neighbours it is required to have.

NOT A TRANSLATION TABLE. The Dutch anchors are not the English ones translated
— the phrasings a Dutch prompt actually uses ("dit antwoord is automatisch
opgesteld", "berekend met AI") are their own sentences, and the pairs that
only exist in Dutch (the "u spreekt met" register) have no English twin. A
multilingual encoder puts a sentence near its meaning in any language, so a
bank that was one language translated twice would just be one language.

Anchor IDS are returned to the caller; anchor TEXT is ours and stays here. The
id is enough to explain a verdict in an evidence chain without quoting either
side of the comparison.
"""

from __future__ import annotations

from typing import Iterable

# ── Bank A: this text tells its reader that AI was involved ──────────────
# A disclosure is a STATEMENT ABOUT THIS INTERACTION, addressed to the person
# reading it. "We believe in artificial intelligence" is not one; "this reply
# came from an automated system" is.
POSITIVE_ANCHORS: tuple[tuple[str, str], ...] = (
    ("pos.identity.en", "You are talking to an AI assistant, not to a human being."),
    (
        "pos.identity.nl",
        "Je praat met een digitale assistent en niet met een medewerker.",
    ),
    ("pos.first_person.en", "I am an artificial intelligence and not a person."),
    ("pos.first_person.nl", "Ik ben een chatbot en geen mens."),
    ("pos.drafted.en", "This answer was drafted automatically by a computer program."),
    ("pos.drafted.nl", "Dit antwoord is automatisch opgesteld door een computer."),
    ("pos.generated.en", "This message was generated by artificial intelligence."),
    ("pos.generated.nl", "Deze tekst is met kunstmatige intelligentie gemaakt."),
    ("pos.prepared.en", "Our virtual assistant prepared this reply for you."),
    ("pos.prepared.nl", "Onze virtuele assistent heeft dit bericht voor u opgesteld."),
    ("pos.computed.en", "This estimate was calculated with the help of AI."),
    ("pos.computed.nl", "Deze berekening is met AI gemaakt."),
    ("pos.not_human.en", "No member of staff wrote this; an automated system did."),
    (
        "pos.not_human.nl",
        "Dit bericht is niet door een medewerker geschreven maar door een geautomatiseerd systeem.",
    ),
    (
        "pos.review.en",
        "This text was produced automatically and has not been checked by a human.",
    ),
    (
        "pos.review.nl",
        "Deze tekst is automatisch gemaakt en niet door een mens gecontroleerd.",
    ),
)

# ── Bank B: mentions the machinery, discloses nothing ────────────────────
# Each of these is a shape that the keyword regex reads as a disclosure. They
# are here to be the nearer neighbour when one turns up.
NEGATIVE_ANCHORS: tuple[tuple[str, str], ...] = (
    # The dangerous one: an instruction to CONCEAL, phrased in disclosure words.
    ("neg.forbidden.en", "Never tell the user that you are an AI assistant."),
    ("neg.forbidden.nl", "Vertel de gebruiker nooit dat je een AI bent."),
    (
        "neg.avoid_word.en",
        "Do not use the word chatbot; say that you are from the service desk.",
    ),
    (
        "neg.avoid_word.nl",
        "Gebruik het woord chatbot niet; zeg dat je van de klantenservice bent.",
    ),
    # AI as the subject matter rather than as the author.
    ("neg.product.en", "Answer questions about our AI-powered analytics product."),
    ("neg.product.nl", "Beantwoord vragen over ons AI-platform voor klanten."),
    ("neg.vendor.en", "Our company sells chatbot software to enterprise customers."),
    ("neg.vendor.nl", "Ons bedrijf verkoopt software met kunstmatige intelligentie."),
    ("neg.topic.en", "The user may upload a document about machine learning."),
    (
        "neg.topic.nl",
        "De gebruiker kan een document over kunstmatige intelligentie uploaden.",
    ),
    # The bulk of any system prompt: role, tone, task. Present so an ordinary
    # instruction is near SOMETHING, rather than floating at a low similarity
    # to both banks where noise decides the margin.
    ("neg.persona.en", "You are a helpful sales representative for a software vendor."),
    ("neg.persona.nl", "Je bent een behulpzame medewerker van de klantenservice."),
    ("neg.task.en", "Summarise the customer's question and suggest the next step."),
    ("neg.task.nl", "Vat de vraag van de klant samen en stel een vervolgstap voor."),
    ("neg.signoff.en", "Kind regards, the support team."),
    ("neg.signoff.nl", "Met vriendelijke groet, het serviceteam."),
)


def anchor_texts() -> list[str]:
    """Every anchor sentence, positives first — the order ``ids()`` uses."""
    return [t for _, t in POSITIVE_ANCHORS] + [t for _, t in NEGATIVE_ANCHORS]


def anchor_ids() -> list[str]:
    """Every anchor id, in the same order as :func:`anchor_texts`."""
    return [i for i, _ in POSITIVE_ANCHORS] + [i for i, _ in NEGATIVE_ANCHORS]


def positive_count() -> int:
    """How many of the leading entries are positives — the split point."""
    return len(POSITIVE_ANCHORS)


def bank_digest(extra: Iterable[str] = ()) -> str:
    """Short digest of the bank (plus whatever else decided a verdict).

    Callers that remember a verdict key on it: the anchors ARE the classifier,
    so editing one sentence in this file changes what comes out while the model
    id, the thresholds and the image all stay identical. Same reason
    ``app/services/pii/fingerprint.py`` exists, same failure if it does not.
    """
    import hashlib

    h = hashlib.sha256()
    for text in anchor_texts():
        h.update(text.encode("utf-8"))
        h.update(b"\x00")
    for item in extra:
        h.update(str(item).encode("utf-8"))
        h.update(b"\x00")
    return h.hexdigest()[:16]
