/**
 * The generator's output is imported by the browser bundle and, natively, by
 * vitest — so what has to hold is that it round-trips (every value survives
 * JSON quoting, including quotes, backslashes and newlines), keeps the source's
 * key order, and stays in the one shape enDefaultsExternal.test.js allows.
 * And --check is a gate: it must REFUSE a hand edit and a stale copy, and say
 * what to run.
 *
 * Sandbox style: scripts/count-ratchet.test.mjs — a throwaway tree under
 * os.tmpdir() with the real script copied in and a tiny fixture dictionary.
 */

import test from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SCRIPT = path.join(HERE, 'gen-i18n-defaults.mjs');

const DICT = {
    'b.first': 'Comes first in the source',
    'a.quotes': 'He said "hi" and it\'s fine',
    'a.slash': 'C:\\path\\to',
    'a.newline': 'line one\nline two',
    greet: 'Hi {name} — “curly” …',
};

function sandbox(dict = DICT) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gen-i18n-defaults-'));
    fs.mkdirSync(path.join(dir, 'scripts'));
    fs.copyFileSync(SCRIPT, path.join(dir, 'scripts', 'gen-i18n-defaults.mjs'));
    fs.copyFileSync(path.join(HERE, 'entry-point.mjs'), path.join(dir, 'scripts', 'entry-point.mjs'));
    fs.mkdirSync(path.join(dir, 'agent-hub', 'src', 'i18n'), { recursive: true });
    writeDict(dir, dict);
    return dir;
}

function writeDict(dir, dict) {
    const en = path.join(dir, 'server', 'i18n', 'defaults', 'en');
    fs.mkdirSync(en, { recursive: true });
    fs.writeFileSync(path.join(en, 'index.js'), `module.exports = { GUI_DEFAULTS: ${JSON.stringify(dict)} };\n`);
}

function run(dir, extra = []) {
    try {
        const stdout = execFileSync(process.execPath, [path.join(dir, 'scripts', 'gen-i18n-defaults.mjs'), ...extra], { cwd: dir, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
        return { code: 0, stdout, stderr: '' };
    } catch (e) {
        return { code: e.status, stdout: e.stdout || '', stderr: e.stderr || '' };
    }
}

const target = (dir) => path.join(dir, 'agent-hub', 'src', 'i18n', 'en-defaults.js');

test('the generated file round-trips every value, in source order', async () => {
    const dir = sandbox();
    const r = run(dir);
    assert.strictEqual(r.code, 0, r.stderr);
    assert.match(r.stdout, /wrote agent-hub\/src\/i18n\/en-defaults\.js \(5 keys\)/);
    const mod = await import(pathToFileURL(target(dir)).href);
    assert.deepStrictEqual(mod.default, DICT);
    assert.deepStrictEqual(Object.keys(mod.default), Object.keys(DICT));
});

test('the file has exactly the transform-free shape: header, literal, export', () => {
    const dir = sandbox();
    run(dir);
    const src = fs.readFileSync(target(dir), 'utf8');
    assert.match(src, /^\/\*\*\n \* English GUI defaults — GENERATED by scripts\/gen-i18n-defaults\.mjs/);
    assert.match(src, /DO NOT EDIT BY HAND/);
    assert.match(src, /Loaded NATIVELY in tests/);
    assert.match(src, / \*\/\n\nconst EN_DEFAULTS = \{\n {4}"b\.first": "Comes first in the source",\n/);
    assert.match(src, /\n {4}"a\.newline": "line one\\nline two",\n/);
    assert.match(src, /\n\};\n\nexport default EN_DEFAULTS;\n$/);
    assert.doesNotMatch(src, /^import /m);
});

test('--check passes on a fresh file and refuses a hand edit', () => {
    const dir = sandbox();
    run(dir);
    const ok = run(dir, ['--check']);
    assert.strictEqual(ok.code, 0, ok.stderr);
    assert.match(ok.stdout, /up to date \(5 keys\)/);

    fs.writeFileSync(target(dir), fs.readFileSync(target(dir), 'utf8').replace('Comes first', 'Edited by hand'));
    const bad = run(dir, ['--check']);
    assert.strictEqual(bad.code, 1);
    assert.match(bad.stderr, /out of date/);
    assert.match(bad.stderr, /committed: {5}"b\.first": "Edited by hand in the source",/);
    assert.match(bad.stderr, /node scripts\/gen-i18n-defaults\.mjs/);
});

test('--check refuses a copy the server dictionary has moved on from, and a missing file', () => {
    const dir = sandbox();
    run(dir);
    writeDict(dir, { ...DICT, 'c.added': 'New' });
    assert.strictEqual(run(dir, ['--check']).code, 1);
    assert.strictEqual(run(dir).code, 0);
    assert.strictEqual(run(dir, ['--check']).code, 0);

    fs.rmSync(target(dir));
    assert.strictEqual(run(dir, ['--check']).code, 1);
    assert.ok(!fs.existsSync(target(dir)), '--check never writes');
});
