#!/usr/bin/env bash
#
# generate-sbom.sh — Software Bill of Materials generator for Bee Flow.
#
# Walks every npm workspace, runs license-checker, and produces:
#   - sbom/<workspace>.json     (machine-readable, gitignored)
#   - sbom/cyclonedx.json       (root CycloneDX, gitignored)
#   - THIRD-PARTY-LICENSES.md   (human-readable, committed)
#
# Usage:   bash scripts/generate-sbom.sh
# Requires: node, npx (license-checker fetched on demand), jq.
#
# Idempotent. Run before each release or after dependency changes.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SBOM_DIR="${REPO_ROOT}/sbom"
OUT_MD="${REPO_ROOT}/THIRD-PARTY-LICENSES.md"

mkdir -p "${SBOM_DIR}"

# Workspaces with package.json + node_modules to scan.
WORKSPACES=(
    "server"
    "agent-hub"
    "install-wizard"
    "nextcloud-connector"
)

# Components are smaller npm packages; collect them dynamically.
mapfile -t COMPONENTS < <(find "${REPO_ROOT}/components" -maxdepth 2 -name package.json -not -path "*/node_modules/*" 2>/dev/null | xargs -I{} dirname {} | sed "s|^${REPO_ROOT}/||" | sort)
WORKSPACES+=("${COMPONENTS[@]}")

# ─── Header ────────────────────────────────────────────────────────────
{
    echo "# Third-Party Licenses"
    echo
    echo "Generated by [scripts/generate-sbom.sh](scripts/generate-sbom.sh) on $(date -u +"%Y-%m-%d")."
    echo
    echo "This file lists every direct and transitive runtime dependency in each Bee Flow npm workspace, plus the self-hosted ML models and proprietary SDKs the application can load. Each entry shows the license identifier and the publishing source."
    echo
    echo "For the legal scope of these notices, see [NOTICE.md](NOTICE.md)."
    echo
    echo "## Workspaces"
    echo
} > "${OUT_MD}"

# ─── Per-workspace license-checker ─────────────────────────────────────
for ws in "${WORKSPACES[@]}"; do
    ws_path="${REPO_ROOT}/${ws}"
    [[ -f "${ws_path}/package.json" ]] || continue

    safe_name="${ws//\//_}"
    json_out="${SBOM_DIR}/${safe_name}.json"

    echo "[sbom] Scanning ${ws} ..."

    if [[ ! -d "${ws_path}/node_modules" ]]; then
        echo "  (skipping — node_modules not installed; run 'npm install' in ${ws} first)"
        {
            echo "### ${ws}"
            echo
            echo "_Not scanned: \`node_modules\` missing. Run \`npm install\` in [\`${ws}\`](${ws}) and re-run this script._"
            echo
        } >> "${OUT_MD}"
        continue
    fi

    (
        cd "${ws_path}"
        npx --yes license-checker@^25 \
            --json \
            --production \
            --excludePrivatePackages \
            --customPath /dev/null > "${json_out}" 2>/dev/null \
        || echo "{}" > "${json_out}"
    )

    {
        echo "### ${ws}"
        echo
        echo "| Package | License | Source |"
        echo "|---|---|---|"
        jq -r 'to_entries[] | "| `\(.key)` | \(.value.licenses // "UNKNOWN") | \(.value.repository // .value.url // "—") |"' "${json_out}" | sort
        echo
    } >> "${OUT_MD}"
done

# ─── Self-hosted ML models ─────────────────────────────────────────────
{
    echo "## Self-hosted ML models"
    echo
    echo "These models are downloaded from Hugging Face the first time the corresponding feature is enabled. Each carries its own license."
    echo
    echo "| Model | Used by | License | Source |"
    echo "|---|---|---|---|"
    echo "| \`urchade/gliner_multi_pii-v1\` | [guard-service/](guard-service/) | Apache 2.0 | https://huggingface.co/urchade/gliner_multi_pii-v1 |"
    echo "| \`openai/privacy-filter\` | [server/core/localPiiDetection.js](server/core/localPiiDetection.js) | Apache 2.0 | https://huggingface.co/openai |"
    echo "| \`Xenova/whisper-base\` | [server/core/voice/localWhisper.js](server/core/voice/localWhisper.js) | MIT (OpenAI Whisper) | https://huggingface.co/Xenova/whisper-base |"
    echo "| \`Qwen/Qwen3-Embedding-4B\` | [search-service/app/config.py](search-service/app/config.py) | Apache 2.0 / Tongyi Qianwen | https://huggingface.co/Qwen/Qwen3-Embedding-4B |"
    echo "| \`BAAI/bge-reranker-v2-m3\` | [search-service/app/config.py](search-service/app/config.py) | Apache 2.0 / MIT | https://huggingface.co/BAAI/bge-reranker-v2-m3 |"
    echo "| \`cross-encoder/mmarco-mMiniLMv2-L12-H384-v1\` | [reranker/reranker.py](reranker/reranker.py) (fallback) | Apache 2.0 | https://huggingface.co/cross-encoder/mmarco-mMiniLMv2-L12-H384-v1 |"
    echo
    echo "## Proprietary SDKs"
    echo
    echo "These dependencies are open-source npm packages but require a commercial subscription to the upstream service when their feature is enabled. Operators are responsible for compliance with the supplier's terms."
    echo
    echo "| Package | Feature | Subscription required |"
    echo "|---|---|---|"
    echo "| \`microsoft-cognitiveservices-speech-sdk\` | Azure Speech transcription / TTS in [server/integrations/transcriptionTools.js](server/integrations/transcriptionTools.js) | Microsoft Azure Cognitive Services. Use is governed by the Microsoft Online Services Terms (OST) and the SDK's bundled Microsoft Software License Terms. |"
    echo
    echo "Other cloud AI providers (Anthropic, OpenAI, Google AI, Mistral, Azure OpenAI, Google Vertex AI, ElevenLabs, Stripe) are reached over their public REST APIs via small open-source SDKs. Their terms of service apply when an API key is configured."
    echo
} >> "${OUT_MD}"

# ─── CycloneDX root SBOM (best-effort) ─────────────────────────────────
echo "[sbom] Generating CycloneDX root SBOM ..."
(
    cd "${REPO_ROOT}"
    npm sbom --sbom-format=cyclonedx > "${SBOM_DIR}/cyclonedx.json" 2>/dev/null \
        || echo "  (npm sbom not available on this Node version; skipping CycloneDX output)"
)

echo "[sbom] Done."
echo "  Machine-readable: ${SBOM_DIR}/"
echo "  Human-readable:   ${OUT_MD}"
