// @typecheck
/**
 * Conversation title encryption.
 *
 * Titles look like metadata and are not. They are generated by asking the model
 * to summarise the first user message, so "Q3 layoff list for Van Dijk" is a
 * précis of exactly the content the other surfaces are busy encrypting. Leaving
 * them readable hands an attacker a searchable index of every conversation.
 *
 * ── Which key ───────────────────────────────────────────────────────────────
 *
 * `ctx.backgroundKey` (the org escrow), never the session DEK. Titles are read
 * by the conversation LIST endpoints, which return dozens of rows across
 * conversations, and written by the auto-title pass that runs after a turn
 * completes. Binding them to a session key would make every list a partial
 * failure the moment one row was written under a different session.
 *
 * ── The cost, stated plainly ────────────────────────────────────────────────
 *
 * `WHERE c.title ILIKE $1` cannot match ciphertext. Search therefore falls back
 * to decrypting a bounded candidate set in the app — the same approach
 * Strategy A2 already uses for message bodies. Search stays correct and gets
 * slower; it does not silently return fewer results, which is the failure mode
 * that matters.
 */

const { conversationKey } = require('./messageCrypto');
const { encryptField, decryptField, isEnvelope } = require('../lib/fieldEnvelope');
const log = require('../../telemetry/log');

/** Bound to the conversation AND its table, so a title cannot be replayed across either. */
function titleAad(type, conversationId) {
    return `bftitle:v1:${type || 'agent'}:${conversationId}`;
}

function _key(ctx, conversationId) {
    const root = (ctx && (ctx.backgroundKey || ctx.key)) || null;
    return root ? conversationKey(root, conversationId) : null;
}

/**
 * Storable form of a title. Passes plaintext straight through when the policy
 * is off or no key resolved.
 */
function sealTitle(title, conversationId, type, ctx) {
    if (title === null || title === undefined) return title;
    return encryptField(String(title), {
        key: _key(ctx, conversationId),
        aad: titleAad(type, conversationId),
        encrypt: !!(ctx && ctx.encryptTitle),
    });
}

/**
 * Readable form of a stored title.
 *
 * Unlike message content, a title that will not open resolves to null rather
 * than throwing. A conversation list is an aggregate: one unreadable row must
 * not take down the other forty, and the caller substitutes a placeholder. The
 * loud-failure rule exists to stop a silent empty read from being written BACK
 * over good data — and nothing writes a title as a side effect of listing it.
 */
function openTitle(stored, conversationId, type, ctx) {
    if (!isEnvelope(stored)) return stored;
    try {
        return decryptField(stored, {
            key: _key(ctx, conversationId),
            aad: titleAad(type, conversationId),
        });
    } catch (err) {
        log.warn(`[ConversationTitle] could not open title for ${conversationId}: ${err.message}`);
        return null;
    }
}

/**
 * Decrypt the `title` on a set of rows in place-ish (returns new objects).
 * `id` is taken from each row, so this works for both conversation tables.
 */
function openTitles(rows, type, ctx) {
    if (!Array.isArray(rows) || !rows.length) return rows;
    return rows.map(r => (
        r && isEnvelope(r.title) ? { ...r, title: openTitle(r.title, r.id, type, ctx) } : r
    ));
}

module.exports = { titleAad, sealTitle, openTitle, openTitles };
