#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════
# e2e/ci/write-env.sh — generate a throwaway .env for the smoke stack
# ══════════════════════════════════════════════════════════════════
#
# Writes the .env that docker-compose.from-registry.yml (+ the CI override
# e2e/ci/docker-compose.ci.yml) reads at the REPO ROOT, with fresh random
# secrets. Intended for ephemeral CI runners — a guard refuses to clobber
# an existing .env outside CI (a developer's local stack config).
#
# Inputs (env):
#   E2E_ANTHROPIC_API_KEY  API key for the smoke LLM tiers (NEVER logged)
#   CI                     must be "true" to overwrite an existing .env
#   GITHUB_ENV             when set, ADMIN_PASSWORD is masked + exported
#                          for later workflow steps
# ══════════════════════════════════════════════════════════════════
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

# ── Safety guard: never clobber a developer's local stack config ──
if [[ -f "$ENV_FILE" && "${CI:-}" != "true" ]]; then
  echo "::error::$ENV_FILE already exists and CI != true — refusing to overwrite a local stack config." >&2
  exit 1
fi

# docker/init-db.sh is bind-mounted by the base compose file. It is checked
# into the repo (selfhost.sh only materialises it for no-clone installs), so
# a plain checkout suffices — just assert it is there.
if [[ ! -f "$REPO_ROOT/docker/init-db.sh" ]]; then
  echo "::error::$REPO_ROOT/docker/init-db.sh is missing — postgres cannot create the beeflow databases." >&2
  exit 1
fi

ADMIN_PASSWORD="Sm0ke$(openssl rand -hex 10)"

# Mask the password in workflow logs and hand it to later steps (the strict
# gate + the Playwright suite) via GITHUB_ENV. Guard: only inside a workflow.
if [[ -n "${GITHUB_ENV:-}" ]]; then
  echo "::add-mask::$ADMIN_PASSWORD"
  echo "ADMIN_PASSWORD=$ADMIN_PASSWORD" >> "$GITHUB_ENV"
fi

# NOTE: E2E_ANTHROPIC_API_KEY is written into the (throwaway, gitignored)
# .env only — never echoed, never logged.
cat > "$ENV_FILE" <<EOF
# Throwaway smoke-stack config generated by e2e/ci/write-env.sh — do not reuse.
TAG=smoke
DEPLOYMENT_MODE=self-hosted
ALLOW_SIGNUPS=false
ALLOW_PASSWORD_LOGIN=true
DEMO_MODE_ENABLED=false
SERVER_PORT=3001
CLIENT_PORT=5176
SESSION_SECRET=$(openssl rand -hex 32)
MASTER_ENCRYPTION_KEY=$(openssl rand -hex 32)
DB_PASSWORD=$(openssl rand -hex 24)
RUSTFS_SECRET_KEY=$(openssl rand -hex 24)
SERVICES_API_KEY=$(openssl rand -hex 24)
INIT_ADMIN_PASSWORD=$ADMIN_PASSWORD
INIT_AI_PROVIDER=claude
INIT_GENERIC_API_KEY=${E2E_ANTHROPIC_API_KEY:-}
INIT_CHAT_MODEL_TIERS={"fast":{"modelId":"claude-haiku-4-5-20251001"},"standard":{"modelId":"claude-haiku-4-5-20251001"}}
# Not required by the core profile — set empty to silence docker
# compose "variable is not set" interpolation warnings.
OPAQUE_SERVER_SETUP=
HF_TOKEN=
EOF
chmod 600 "$ENV_FILE"

echo "[write-env] wrote $ENV_FILE (secret values not shown)"
