/**
 * The Content group: what you and your agents read, write and run. Order here
 * is the order the map lists them in.
 */

import type { Destination } from '../types';

export const CONTENT: Destination[] = [
    {
        id: 'notebooks',
        i18nKey: 'sidebar.notebooks',
        label: 'Notebooks',
        hint: 'Long-form notes your agents can read',
        icon: 'FileText',
        href: '/notebooks',
        group: 'Content',
        keywords: ['notes', 'writing'],
    },
    {
        id: 'knowledge',
        label: 'Knowledge bases',
        hintKey: 'studio.tab.knowledge_desc',
        hint: 'Knowledge bases your AI can search',
        icon: 'BookOpen',
        href: '/knowledge',
        group: 'Content',
        keywords: ['kb', 'rag', 'sources', 'retrieval'],
    },
    {
        id: 'documents',
        label: 'Knowledge documents',
        hint: 'Files you have uploaded to your knowledge bases',
        icon: 'FileText',
        // /documents is Studio Documents (the web's Studio section); the
        // knowledge-base file list moved under /knowledge.
        href: '/knowledge/documents',
        group: 'Content',
        keywords: ['files', 'uploads', 'pdf'],
    },
    {
        id: 'skills',
        label: 'Skills',
        hintKey: 'studio.tab.skills_desc',
        hint: 'Reusable abilities for your agents',
        icon: 'Sparkles',
        href: '/skills',
        group: 'Content',
        keywords: ['instructions', 'prompt pack', 'playbook'],
    },
    {
        id: 'memory',
        i18nKey: 'settings.memory',
        label: 'Memory',
        hintKey: 'settings.memory_desc',
        hint: 'Persisted facts about you, your projects, and preferences',
        icon: 'Bookmark',
        href: '/memory',
        group: 'Content',
        keywords: ['remember', 'forget', 'recall', 'personalisation'],
    },
    {
        id: 'templates',
        i18nKey: 'sidebar.templates',
        label: 'Templates',
        hint: 'Reusable prompts and starting points',
        icon: 'Copy',
        href: '/templates',
        group: 'Content',
        keywords: ['prompt', 'starter'],
    },
    {
        id: 'projects',
        i18nKey: 'sidebar.projects',
        label: 'Projects',
        hint: 'Group chats, files and automations by the work they belong to',
        icon: 'Folder',
        href: '/projects',
        group: 'Content',
        keywords: ['workspace', 'folder'],
    },
    {
        id: 'apps',
        label: 'Apps',
        hint: 'Small tools built in App Studio',
        icon: 'AppWindow',
        href: '/apps',
        group: 'Content',
        keywords: ['studio', 'tools'],
    },
    {
        id: 'approvals',
        label: 'Approvals',
        hintKey: 'studio.tab.approvals_desc',
        hint: 'Requests waiting on a person, and every past decision',
        icon: 'ShieldCheck',
        href: '/approvals',
        group: 'Content',
        // Had no row at all until its list screen existed: the only entrance
        // was an unread notification, so a decided approval was unreachable.
        keywords: ['approve', 'reject', 'waiting', 'decision', 'goedkeuren', 'wacht', 'besluit'],
    },
    {
        id: 'automations',
        label: 'Automations',
        hintKey: 'studio.tab.automations_desc',
        hint: 'Multi-step routines that run for you',
        icon: 'ListChecks',
        href: '/automations',
        group: 'Content',
        keywords: ['schedule', 'trigger', 'runs', 'workflow'],
    },
    {
        id: 'tasks',
        i18nKey: 'sidebar.tasks',
        label: 'Tasks and reminders',
        hint: 'What you asked Bee Flow to come back to you about',
        icon: 'SquareCheckBig',
        href: '/tasks',
        group: 'Content',
        keywords: ['todo', 'reminder', 'agenda'],
    },
    {
        id: 'datatables',
        label: 'Datatables',
        hintKey: 'studio.tab.datatables_desc',
        hint: 'Rows your routines keep between runs',
        icon: 'Table2',
        href: '/datatables',
        group: 'Content',
        // Studio's gate: the automations entitlement and `use_datatables`.
        gate: { license: 'automations', canUse: 'automations', perms: ['use_datatables'] },
        keywords: ['table', 'rows', 'spreadsheet', 'csv', 'data', 'tabel'],
    },
    {
        id: 'studio-documents',
        label: 'Studio documents',
        hintKey: 'studio.tab.documents_desc',
        hint: 'Invoices, quotes and letters — editable by hand, downloadable as PDF',
        icon: 'FileText',
        href: '/documents',
        group: 'Content',
        keywords: ['invoice', 'quote', 'letter', 'presentation', 'deck', 'pdf', 'factuur', 'offerte', 'brief'],
    },
    {
        id: 'runs',
        label: 'Runs & log',
        hintKey: 'runs.tab_desc',
        hint: 'Every time a routine fired, and what happened',
        icon: 'History',
        href: '/runs',
        group: 'Content',
        keywords: ['executions', 'log', 'history', 'failed', 'uitvoeringen', 'logboek'],
        gate: { license: 'automations', canUse: 'automations' },
    },
    {
        id: 'playbooks',
        label: 'Playbooks',
        hintKey: 'studio.tab.playbooks_desc',
        hint: 'Watch the AI build a table, an automation and an app — one phase at a time',
        icon: 'Clapperboard',
        href: '/playbooks',
        group: 'Content',
        keywords: ['build', 'phases', 'recipe', 'bouwen'],
        gate: { can: 'app_studio', canUse: 'automations' },
    },
];
