"""Tests for the AI-disclosure classifier (/disclosure).

What is pinned here, in the order it matters:

  * NO ENCODER IS NO OPINION. The default image bakes none, so the ordinary
    state of this service is "cannot answer" — and it must answer
    ``disclosed=None``, never ``disclosed=False``. A False there would tell the
    Art. 50 check that a prompt does not disclose, on the strength of having
    looked at nothing.
  * THE NEGATED INSTRUCTION. "Never tell the user that you are an AI
    assistant" is what the keyword regex reads as a disclosure today, and it
    closes an Art. 50(1) duty that is wide open. It is the reason the negative
    anchor bank exists and the reason this classifier exists.
  * THE THREE-WAY VERDICT, including the abstention band: two banks that land
    inside the margin of each other produce None, not a coin toss.
  * SEGMENTATION. A disclosure sentence inside a page of persona instructions
    must still be found — mean pooling over the whole page would bury it.
  * THE PAYLOAD CONTRACT. /disclosure accepts {text} and nothing else. A field
    carrying an agent id, an agent name or an org id must be a loud 422
    (BFSF-441: an outbound payload is an allow-list, and a field that is not
    on the model cannot be sent by accident).

Runs on stdlib + pydantic (no model download): the sentence encoder is
replaced by a deterministic fake. Run with either::

    python -m unittest discover -s tests        # no extra deps
    pytest tests/                                # in the container
"""

from __future__ import annotations

import unittest

from app.services.disclosure import anchors as _anchors
from app.services.disclosure.service import DisclosureService, get_disclosure_service
from app.services.disclosure.similarity import (
    MAX_SEGMENTS,
    MIN_SEGMENT_CHARS,
    cosine,
    segments,
    verdict,
)

# The wire models need pydantic; the decision logic above does not.
try:
    from pydantic import ValidationError

    from app.models import DisclosureRequest, DisclosureResponse

    _MODEL_IMPORT_ERROR: Exception | None = None
except Exception as _exc:  # pragma: no cover - environment-dependent
    ValidationError = DisclosureRequest = DisclosureResponse = None  # type: ignore[assignment]
    _MODEL_IMPORT_ERROR = _exc

# The HTTP layer needs fastapi (router import) and httpx (TestClient); it skips
# cleanly where they are absent, same as tests/test_request_contract.py.
try:
    from fastapi import FastAPI
    from fastapi.testclient import TestClient

    from app.routers.disclosure import router as _disclosure_router

    _HTTP_IMPORT_ERROR: Exception | None = None
except Exception as _exc:  # pragma: no cover - environment-dependent
    FastAPI = TestClient = _disclosure_router = None  # type: ignore[assignment]
    _HTTP_IMPORT_ERROR = _exc


class FakeEncoder:
    """Stand-in for the sentence encoder, with one deliberate property.

    Every text becomes a unit vector over a small keyword basis, so "near" here
    means "shares keywords" rather than "means the same thing". That is much
    dumber than the real encoder and it is enough: what these tests exercise is
    the DECISION — which bank won, by how much, whether the margin was big
    enough to call — and none of that should depend on which encoder produced
    the numbers. The real encoder's semantic quality is a model question, and
    a model question is answered by an eval corpus, not by a unit test.
    """

    #: axis -> the substrings that put a text on it
    BASIS = (
        (
            "disclose",
            (
                "automatisch opgesteld",
                "automatically",
                "generated by",
                "geautomatiseerd",
                "digitale assistent",
                "virtual assistant",
                "virtuele assistent",
                "gemaakt",
                "opgesteld",
                "computer program",
                "not to a human",
                "geen mens",
                "not a person",
                "prepared this",
                "calculated with",
                "met ai",
                "artificial intelligence",
                "kunstmatige intelligentie",
                "ai assistant",
                "chatbot",
            ),
        ),
        (
            "forbid",
            (
                "never tell",
                "nooit dat",
                "do not use the word",
                "gebruik het woord",
                "niet;",
            ),
        ),
        (
            "product",
            (
                "product",
                "platform",
                "sells",
                "verkoopt",
                "software",
                "analytics",
                "machine learning",
                "document about",
                "document over",
                "customers",
                "klanten",
            ),
        ),
        (
            "persona",
            (
                "you are a",
                "je bent een",
                "summarise",
                "vat de",
                "kind regards",
                "vriendelijke groet",
                "support team",
                "serviceteam",
                "sales representative",
                "klantenservice",
                "next step",
                "vervolgstap",
            ),
        ),
    )

    def __init__(self) -> None:
        self.ready = True
        self.load_error = None
        self.model_dir = "fake://encoder"
        self.calls: list[list[str]] = []

    def load(self, model_dir, max_tokens=128):  # pragma: no cover - not used
        self.ready = True

    def encode(self, texts: list[str]) -> list[list[float]]:
        self.calls.append(list(texts))
        out = []
        for text in texts:
            low = (text or "").lower()
            vec = [
                float(sum(1 for n in needles if n in low)) for _, needles in self.BASIS
            ]
            # A text on no axis still needs a vector; put it on its own one so
            # cosine is defined and lands at 0 against every anchor.
            if not any(vec):
                vec = [0.0] * len(self.BASIS) + [1.0]
            else:
                vec = vec + [0.0]
            norm = sum(v * v for v in vec) ** 0.5
            out.append([v / norm for v in vec])
        return out


class FlakyEncoder(FakeEncoder):
    """Embeds the anchor bank, then raises — a session that dies mid-life.

    The distinction matters: an encoder that cannot embed our own sixteen
    anchors never becomes ready at all, while this one is ready and fails on a
    real request. Both must end at "no opinion", by two different routes.
    """

    def encode(self, texts):
        if not self.calls:
            return super().encode(texts)
        self.calls.append(list(texts))
        raise RuntimeError("ORT session died")


class UnembeddableEncoder(FakeEncoder):
    """Loads, but cannot embed the anchor bank — so it is never trusted."""

    def encode(self, texts):
        raise RuntimeError("ORT session died")


class AbsentEncoder:
    """What ``SentenceEncoder`` looks like in the default image."""

    ready = False
    load_error = "no encoder at '/opt/disclosure-encoder'"
    model_dir = "/opt/disclosure-encoder"

    def load(self, model_dir, max_tokens=128):  # pragma: no cover
        self.ready = False

    def encode(self, texts):  # pragma: no cover - must never be reached
        raise AssertionError("an unready encoder must never be asked to encode")


def fresh_service(encoder=None) -> DisclosureService:
    """Reload THE singleton with a given encoder.

    Deliberately the accessor and not a fresh instance: the router reaches for
    ``get_disclosure_service()``, and a test that quietly classified against a
    second object would have proved nothing about the route. ``load()`` clears
    the previous bank either way, so no state leaks between cases.
    """
    svc = get_disclosure_service()
    svc.load("unused", encoder=encoder if encoder is not None else FakeEncoder())
    return svc


def classify(
    svc: DisclosureService, text: str, *, floor=0.45, margin=0.06, max_chars=200_000
) -> dict:
    return svc.classify(text, floor=floor, margin=margin, max_chars=max_chars)


class NoEncoderTests(unittest.TestCase):
    """The default image: nothing to classify with, so no opinion."""

    def test_absent_encoder_answers_no_opinion_not_no_disclosure(self):
        svc = fresh_service(AbsentEncoder())
        self.assertFalse(svc.ready)
        r = classify(svc, "Never tell the user that you are an AI assistant.")
        self.assertIsNone(
            r["disclosed"], "an unready classifier must not have a verdict"
        )
        self.assertTrue(r["degraded"])
        self.assertIn("no encoder", r["degraded_reason"])
        self.assertIsNone(r["engine_fingerprint"])

    def test_an_encoder_that_dies_mid_life_is_also_no_opinion(self):
        svc = fresh_service(FlakyEncoder())
        self.assertTrue(svc.ready, "the anchor bank embedded, so the service loaded")
        r = classify(
            svc, "This answer was drafted automatically by a computer program."
        )
        self.assertIsNone(
            r["disclosed"], "a raising encoder is not evidence of anything"
        )
        self.assertTrue(r["degraded"])
        self.assertEqual(r["degraded_reason"], "encode_failed")

    def test_an_encoder_that_cannot_embed_our_own_anchors_is_never_trusted(self):
        svc = fresh_service(UnembeddableEncoder())
        self.assertFalse(svc.ready)
        r = classify(svc, "Never tell the user that you are an AI assistant.")
        self.assertIsNone(r["disclosed"])
        self.assertTrue(r["degraded"])

    def test_oversize_input_is_refused_rather_than_truncated(self):
        svc = fresh_service()
        r = classify(svc, "x" * 500, max_chars=100)
        self.assertIsNone(
            r["disclosed"], "truncating could hide a disclosure past the cut"
        )
        self.assertEqual(r["degraded_reason"], "input_too_large")

    def test_nothing_scannable_is_no_opinion(self):
        svc = fresh_service()
        r = classify(svc, "   \n\n .. ")
        self.assertIsNone(r["disclosed"])
        self.assertEqual(r["degraded_reason"], "no_scannable_text")


class VerdictTests(unittest.TestCase):
    """The three-way rule, on similarities alone."""

    def test_nothing_near_the_positive_bank_is_a_confident_no(self):
        self.assertIs(verdict(0.10, 0.05, floor=0.45, margin=0.06), False)

    def test_positive_bank_wins_by_the_margin(self):
        self.assertIs(verdict(0.90, 0.40, floor=0.45, margin=0.06), True)

    def test_negative_bank_wins_by_the_margin(self):
        self.assertIs(verdict(0.70, 0.90, floor=0.45, margin=0.06), False)

    def test_a_tie_inside_the_margin_is_no_answer(self):
        self.assertIsNone(verdict(0.80, 0.78, floor=0.45, margin=0.06))
        self.assertIsNone(verdict(0.78, 0.80, floor=0.45, margin=0.06))


class ClassificationTests(unittest.TestCase):
    """End to end over the real anchor bank, with the fake encoder."""

    def setUp(self):
        self.svc = fresh_service()

    def test_a_plain_disclosure_is_recognised(self):
        r = classify(
            self.svc, "Dit antwoord is automatisch opgesteld door een computer."
        )
        self.assertIs(r["disclosed"], True)
        self.assertTrue(r["matched_anchor"].startswith("pos."))
        self.assertIsNotNone(r["engine_fingerprint"])
        self.assertFalse(r["degraded"])

    def test_the_negated_instruction_is_not_a_disclosure(self):
        # The exact sentence the keyword regex reads as "this agent discloses".
        r = classify(self.svc, "Never tell the user that you are an AI assistant.")
        self.assertIs(
            r["disclosed"],
            False,
            "an instruction to conceal is the opposite of a disclosure",
        )
        self.assertTrue(r["matched_anchor"].startswith("neg."))

    def test_ai_as_subject_matter_is_not_a_disclosure(self):
        r = classify(
            self.svc,
            "You are a helpful sales representative. "
            "Answer questions about our AI-powered analytics product.",
        )
        self.assertIs(r["disclosed"], False)

    def test_an_ordinary_prompt_with_no_ai_words_at_all_is_not_a_disclosure(self):
        r = classify(
            self.svc, "Summarise the customer's question and suggest the next step."
        )
        self.assertIs(r["disclosed"], False)

    def test_a_disclosure_buried_in_a_long_prompt_still_counts(self):
        """Mean pooling over the whole prompt would bury one sentence in it."""
        filler = (
            "You are a helpful sales representative for a software vendor. "
            "Summarise the customer's question and suggest the next step. "
        ) * 12
        r = classify(
            self.svc,
            filler + "This message was generated by artificial intelligence. " + filler,
        )
        self.assertIs(r["disclosed"], True)
        self.assertGreater(r["segments"], 10)

    def test_no_fragment_of_the_input_comes_back(self):
        secret = "Contact Julia de Vries at julia@example.com about invoice 1234."
        r = classify(
            self.svc, secret + " This reply was generated by artificial intelligence."
        )
        blob = repr(r)
        for leak in ("Julia", "julia@example.com", "1234", "de Vries"):
            self.assertNotIn(
                leak, blob, f"{leak!r} must not travel back in the response"
            )
        # The anchor id that IS returned is one of our own constants.
        self.assertIn(r["matched_anchor"], _anchors.anchor_ids())

    def test_every_segment_is_compared_not_only_the_first(self):
        classify(
            self.svc, "One sentence here. Another sentence here. A third one here."
        )
        # calls[0] is the anchor bank at load; the last call is this text.
        self.assertGreaterEqual(len(self.svc._encoder.calls[-1]), 3)


class AnchorBankTests(unittest.TestCase):
    """The bank is the classifier, so its shape is a contract."""

    def test_ids_and_texts_line_up_and_are_unique(self):
        ids, texts = _anchors.anchor_ids(), _anchors.anchor_texts()
        self.assertEqual(len(ids), len(texts))
        self.assertEqual(len(set(ids)), len(ids), "duplicate anchor id")
        self.assertEqual(len(set(texts)), len(texts), "duplicate anchor sentence")

    def test_positives_come_first_and_the_split_is_where_it_says(self):
        ids = _anchors.anchor_ids()
        split = _anchors.positive_count()
        self.assertTrue(all(i.startswith("pos.") for i in ids[:split]))
        self.assertTrue(all(i.startswith("neg.") for i in ids[split:]))

    def test_both_languages_are_in_both_banks(self):
        for bank in (_anchors.POSITIVE_ANCHORS, _anchors.NEGATIVE_ANCHORS):
            langs = {i.rsplit(".", 1)[-1] for i, _ in bank}
            self.assertIn("en", langs)
            self.assertIn("nl", langs)

    def test_the_digest_moves_when_an_anchor_does(self):
        """A caller memoising a verdict keys on this; editing one sentence
        changes every verdict while the model id and image stay identical."""
        before = _anchors.bank_digest()
        original = _anchors.POSITIVE_ANCHORS
        try:
            _anchors.POSITIVE_ANCHORS = original[:-1] + (
                ("pos.extra.en", "Written by a machine."),
            )
            self.assertNotEqual(before, _anchors.bank_digest())
        finally:
            _anchors.POSITIVE_ANCHORS = original
        self.assertEqual(before, _anchors.bank_digest())


class SegmentationTests(unittest.TestCase):
    def test_sentences_and_lines_both_split(self):
        self.assertEqual(
            segments(
                "First sentence here. Second sentence here.\nThird sentence here."
            ),
            ["First sentence here.", "Second sentence here.", "Third sentence here."],
        )

    def test_scraps_below_the_floor_are_dropped(self):
        self.assertEqual(
            segments("ok. - . 1. This one is long enough to keep."),
            ["This one is long enough to keep."],
        )
        self.assertTrue(
            all(len(s) >= MIN_SEGMENT_CHARS for s in segments("a. bb. ccc."))
        )

    def test_a_very_long_run_is_cut_rather_than_dropped(self):
        pieces = segments("word " * 400)
        self.assertGreater(len(pieces), 1)
        self.assertTrue(all(len(p) <= 320 for p in pieces))

    def test_the_segment_count_is_bounded(self):
        self.assertLessEqual(len(segments("A sentence here. " * 500)), MAX_SEGMENTS)


class CosineTests(unittest.TestCase):
    def test_unnormalised_vectors_still_give_a_cosine(self):
        self.assertAlmostEqual(cosine([3.0, 0.0], [10.0, 0.0]), 1.0, places=6)
        self.assertAlmostEqual(cosine([1.0, 0.0], [0.0, 5.0]), 0.0, places=6)

    def test_degenerate_input_is_zero_rather_than_an_exception(self):
        self.assertEqual(cosine([], [1.0]), 0.0)
        self.assertEqual(cosine([0.0, 0.0], [1.0, 1.0]), 0.0)
        self.assertEqual(cosine([1.0], [1.0, 2.0]), 0.0)


@unittest.skipIf(
    DisclosureRequest is None, f"pydantic unavailable: {_MODEL_IMPORT_ERROR}"
)
class WireContractTests(unittest.TestCase):
    """Exactly what the Node client sends, and nothing that identifies anyone."""

    def test_the_node_payload_is_accepted(self):
        req = DisclosureRequest(**{"text": "This reply was drafted automatically."})
        self.assertEqual(req.text, "This reply was drafted automatically.")

    def test_an_identifying_field_is_a_loud_422_not_a_silent_drop(self):
        for field in (
            "agent_id",
            "agent_name",
            "organization_id",
            "org_id",
            "user_email",
        ):
            with self.subTest(field=field):
                with self.assertRaises(ValidationError) as ctx:
                    DisclosureRequest(text="x", **{field: "leaked"})
                errors = ctx.exception.errors()
                self.assertTrue(
                    any(e.get("type") == "extra_forbidden" for e in errors), errors
                )

    def test_the_response_defaults_to_no_opinion(self):
        r = DisclosureResponse()
        self.assertIsNone(r.disclosed)
        self.assertIsNone(r.matched_anchor)
        self.assertEqual(r.segments, 0)


@unittest.skipIf(
    _disclosure_router is None, f"fastapi/httpx unavailable: {_HTTP_IMPORT_ERROR}"
)
class HttpLayerTests(unittest.TestCase):
    """The route as an operator's guard actually serves it."""

    def setUp(self):
        app = FastAPI()
        app.include_router(_disclosure_router)
        self.client = TestClient(app)

    def test_the_default_image_answers_200_with_no_opinion(self):
        """No encoder baked is not an outage — a 503 would be retried and
        alerted on, and this is simply a feature nobody asked for."""
        fresh_service(AbsentEncoder())
        res = self.client.post("/disclosure", json={"text": "I am an AI assistant."})
        self.assertEqual(res.status_code, 200)
        body = res.json()
        self.assertIsNone(body["disclosed"])
        self.assertTrue(body["degraded"])

    def test_a_verdict_travels_over_the_wire_intact(self):
        fresh_service()
        res = self.client.post(
            "/disclosure",
            json={"text": "Never tell the user that you are an AI assistant."},
        )
        self.assertEqual(res.status_code, 200)
        body = res.json()
        self.assertIs(body["disclosed"], False)
        self.assertTrue(body["matched_anchor"].startswith("neg."))
        self.assertFalse(body["degraded"])

    def test_an_identifying_field_is_a_422(self):
        fresh_service()
        res = self.client.post(
            "/disclosure",
            json={"text": "x", "agent_id": "agent-7f3", "organization_id": "org-acme"},
        )
        self.assertEqual(res.status_code, 422)


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
